// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/organization-srv/proto/school/school.proto

package kit_iron_srv_organization_school

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateSchoolRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchoolRequest) Reset()         { *m = CreateSchoolRequest{} }
func (m *CreateSchoolRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSchoolRequest) ProtoMessage()    {}
func (*CreateSchoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_school_2345f3d430da6fb7, []int{0}
}
func (m *CreateSchoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchoolRequest.Unmarshal(m, b)
}
func (m *CreateSchoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchoolRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSchoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchoolRequest.Merge(dst, src)
}
func (m *CreateSchoolRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSchoolRequest.Size(m)
}
func (m *CreateSchoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchoolRequest proto.InternalMessageInfo

func (m *CreateSchoolRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSchoolRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateSchoolResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSchoolResponse) Reset()         { *m = CreateSchoolResponse{} }
func (m *CreateSchoolResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSchoolResponse) ProtoMessage()    {}
func (*CreateSchoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_school_2345f3d430da6fb7, []int{1}
}
func (m *CreateSchoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSchoolResponse.Unmarshal(m, b)
}
func (m *CreateSchoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSchoolResponse.Marshal(b, m, deterministic)
}
func (dst *CreateSchoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSchoolResponse.Merge(dst, src)
}
func (m *CreateSchoolResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSchoolResponse.Size(m)
}
func (m *CreateSchoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSchoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSchoolResponse proto.InternalMessageInfo

func (m *CreateSchoolResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type ListRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_school_2345f3d430da6fb7, []int{2}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListResponse struct {
	OK                   bool      `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	Schools              []*School `protobuf:"bytes,2,rep,name=Schools,proto3" json:"Schools,omitempty"`
	Total                int64     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_school_2345f3d430da6fb7, []int{3}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *ListResponse) GetSchools() []*School {
	if m != nil {
		return m.Schools
	}
	return nil
}

func (m *ListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type School struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SlugName             string   `protobuf:"bytes,2,opt,name=SlugName,proto3" json:"SlugName,omitempty"`
	SchoolCode           string   `protobuf:"bytes,3,opt,name=SchoolCode,proto3" json:"SchoolCode,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ID                   string   `protobuf:"bytes,5,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *School) Reset()         { *m = School{} }
func (m *School) String() string { return proto.CompactTextString(m) }
func (*School) ProtoMessage()    {}
func (*School) Descriptor() ([]byte, []int) {
	return fileDescriptor_school_2345f3d430da6fb7, []int{4}
}
func (m *School) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_School.Unmarshal(m, b)
}
func (m *School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_School.Marshal(b, m, deterministic)
}
func (dst *School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_School.Merge(dst, src)
}
func (m *School) XXX_Size() int {
	return xxx_messageInfo_School.Size(m)
}
func (m *School) XXX_DiscardUnknown() {
	xxx_messageInfo_School.DiscardUnknown(m)
}

var xxx_messageInfo_School proto.InternalMessageInfo

func (m *School) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *School) GetSlugName() string {
	if m != nil {
		return m.SlugName
	}
	return ""
}

func (m *School) GetSchoolCode() string {
	if m != nil {
		return m.SchoolCode
	}
	return ""
}

func (m *School) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *School) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateSchoolRequest)(nil), "kit.iron.srv.organization.school.CreateSchoolRequest")
	proto.RegisterType((*CreateSchoolResponse)(nil), "kit.iron.srv.organization.school.CreateSchoolResponse")
	proto.RegisterType((*ListRequest)(nil), "kit.iron.srv.organization.school.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "kit.iron.srv.organization.school.ListResponse")
	proto.RegisterType((*School)(nil), "kit.iron.srv.organization.school.School")
}

func init() {
	proto.RegisterFile("srv/organization-srv/proto/school/school.proto", fileDescriptor_school_2345f3d430da6fb7)
}

var fileDescriptor_school_2345f3d430da6fb7 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0x76, 0x83, 0x21, 0x3c, 0xd0, 0x43, 0xe5, 0xb0, 0x70, 0x30, 0xcb, 0x0e, 0x66, 0x17, 0x4a,
	0x82, 0x51, 0xef, 0x42, 0x62, 0x08, 0x44, 0x4c, 0xf9, 0x05, 0x13, 0x1b, 0x6c, 0x84, 0x75, 0xb6,
	0x85, 0x18, 0x2f, 0xde, 0xfd, 0xd1, 0xc6, 0xac, 0x0f, 0x4c, 0x55, 0x92, 0xe9, 0x69, 0x7d, 0x5f,
	0xdf, 0xf7, 0x7d, 0x7b, 0xdf, 0x2b, 0x50, 0xad, 0x36, 0x3d, 0xa9, 0x16, 0x69, 0x26, 0x5e, 0x53,
	0x23, 0x64, 0xd6, 0x2d, 0x80, 0x5c, 0x49, 0x23, 0x7b, 0x7a, 0xfe, 0x28, 0xe5, 0x72, 0xfb, 0xa1,
	0x16, 0x23, 0xd1, 0x93, 0x30, 0x54, 0x28, 0x99, 0x15, 0x44, 0xea, 0x12, 0x29, 0xf6, 0xc5, 0x63,
	0x38, 0x19, 0x28, 0x9e, 0x1a, 0x3e, 0xb3, 0x35, 0xe3, 0xcf, 0x6b, 0xae, 0x0d, 0x21, 0x50, 0xbd,
	0x4d, 0x57, 0x3c, 0xf4, 0x22, 0x2f, 0x69, 0x30, 0x7b, 0x26, 0x11, 0x34, 0x87, 0x5c, 0xcf, 0x95,
	0xc8, 0x0b, 0x81, 0xd0, 0xb7, 0x57, 0x2e, 0x14, 0x9f, 0x41, 0xfb, 0xbb, 0x98, 0xce, 0x65, 0xa6,
	0x39, 0x39, 0x06, 0x7f, 0x3a, 0xb6, 0x5a, 0x75, 0xe6, 0x4f, 0xc7, 0xf1, 0x15, 0x34, 0x27, 0x42,
	0x1b, 0xc7, 0xec, 0x2e, 0x5d, 0xa0, 0x59, 0xc0, 0xec, 0x99, 0xb4, 0x21, 0x98, 0x88, 0x95, 0x30,
	0xd6, 0x26, 0x60, 0x58, 0xc4, 0x2f, 0xd0, 0x42, 0xe2, 0x7e, 0x61, 0x72, 0x0d, 0x87, 0x68, 0xad,
	0x43, 0x3f, 0xaa, 0x24, 0xcd, 0x7e, 0x42, 0xcb, 0x12, 0xa0, 0xdb, 0x7f, 0xdd, 0x11, 0x0b, 0x67,
	0x23, 0x4d, 0xba, 0x0c, 0x2b, 0x91, 0x97, 0x54, 0x18, 0x16, 0xf1, 0xbb, 0x07, 0x35, 0xec, 0xd8,
	0x9b, 0x4d, 0x07, 0xea, 0xb3, 0xe5, 0x7a, 0x61, 0x71, 0x0c, 0xe6, 0xab, 0x26, 0xa7, 0x00, 0xc8,
	0x1c, 0xc8, 0x07, 0x6e, 0x55, 0x1b, 0xcc, 0x41, 0x7e, 0xe6, 0x5a, 0xfd, 0x95, 0x6b, 0x31, 0xe6,
	0x68, 0x18, 0x06, 0xf6, 0xc2, 0x1f, 0x0d, 0xfb, 0x1f, 0x1e, 0x34, 0x50, 0x60, 0xa6, 0x36, 0xe4,
	0x0d, 0x5a, 0x6e, 0xea, 0xe4, 0xa2, 0x7c, 0xe6, 0x3d, 0x2b, 0xef, 0x5c, 0xfe, 0x97, 0x86, 0x3b,
	0x88, 0x0f, 0x48, 0x0e, 0x47, 0x37, 0xdc, 0x20, 0x5c, 0xac, 0x87, 0x74, 0xcb, 0xa5, 0x9c, 0xfd,
	0x77, 0xe8, 0x5f, 0xdb, 0x77, 0x8e, 0xf7, 0x35, 0xfb, 0xbc, 0xcf, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0xe1, 0xd6, 0x34, 0x10, 0x03, 0x00, 0x00,
}
