version: '3.1'

services:
  api-gateway:
    build: ./api-gateway
    network_mode: host
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
  user-srv:
    build: ./user-srv
    network_mode: host
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "localhost:27017"
      DB_NAME: "unite"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27018:27017
  