// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/permission/permission.proto

package iunite_club_srv_core_permission

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ByIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByIDRequest) Reset()         { *m = ByIDRequest{} }
func (m *ByIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByIDRequest) ProtoMessage()    {}
func (*ByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_1d78ab640f3c79e5, []int{0}
}
func (m *ByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIDRequest.Unmarshal(m, b)
}
func (m *ByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIDRequest.Marshal(b, m, deterministic)
}
func (dst *ByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIDRequest.Merge(dst, src)
}
func (m *ByIDRequest) XXX_Size() int {
	return xxx_messageInfo_ByIDRequest.Size(m)
}
func (m *ByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByIDRequest proto.InternalMessageInfo

func (m *ByIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeletedResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletedResponse) Reset()         { *m = DeletedResponse{} }
func (m *DeletedResponse) String() string { return proto.CompactTextString(m) }
func (*DeletedResponse) ProtoMessage()    {}
func (*DeletedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_1d78ab640f3c79e5, []int{1}
}
func (m *DeletedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedResponse.Unmarshal(m, b)
}
func (m *DeletedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedResponse.Marshal(b, m, deterministic)
}
func (dst *DeletedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedResponse.Merge(dst, src)
}
func (m *DeletedResponse) XXX_Size() int {
	return xxx_messageInfo_DeletedResponse.Size(m)
}
func (m *DeletedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedResponse proto.InternalMessageInfo

func (m *DeletedResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *DeletedResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CreateRequest struct {
	PermissionName       string   `protobuf:"bytes,1,opt,name=PermissionName,proto3" json:"PermissionName,omitempty"`
	PathRule             string   `protobuf:"bytes,2,opt,name=PathRule,proto3" json:"PathRule,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_1d78ab640f3c79e5, []int{2}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPermissionName() string {
	if m != nil {
		return m.PermissionName
	}
	return ""
}

func (m *CreateRequest) GetPathRule() string {
	if m != nil {
		return m.PathRule
	}
	return ""
}

func (m *CreateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type CreatedPermissionResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedPermissionResponse) Reset()         { *m = CreatedPermissionResponse{} }
func (m *CreatedPermissionResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedPermissionResponse) ProtoMessage()    {}
func (*CreatedPermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_1d78ab640f3c79e5, []int{3}
}
func (m *CreatedPermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedPermissionResponse.Unmarshal(m, b)
}
func (m *CreatedPermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedPermissionResponse.Marshal(b, m, deterministic)
}
func (dst *CreatedPermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedPermissionResponse.Merge(dst, src)
}
func (m *CreatedPermissionResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedPermissionResponse.Size(m)
}
func (m *CreatedPermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedPermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedPermissionResponse proto.InternalMessageInfo

func (m *CreatedPermissionResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *CreatedPermissionResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*ByIDRequest)(nil), "iunite.club.srv.core.permission.ByIDRequest")
	proto.RegisterType((*DeletedResponse)(nil), "iunite.club.srv.core.permission.DeletedResponse")
	proto.RegisterType((*CreateRequest)(nil), "iunite.club.srv.core.permission.CreateRequest")
	proto.RegisterType((*CreatedPermissionResponse)(nil), "iunite.club.srv.core.permission.CreatedPermissionResponse")
}

func init() {
	proto.RegisterFile("proto/permission/permission.proto", fileDescriptor_permission_1d78ab640f3c79e5)
}

var fileDescriptor_permission_1d78ab640f3c79e5 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x2d, 0xca, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0x43, 0x62, 0xea, 0x81,
	0xe5, 0x84, 0xe4, 0x33, 0x4b, 0xf3, 0x32, 0x4b, 0x52, 0xf5, 0x92, 0x73, 0x4a, 0x93, 0xf4, 0x8a,
	0x8b, 0xca, 0xf4, 0x92, 0xf3, 0x8b, 0x52, 0xf5, 0x10, 0xca, 0x94, 0x64, 0xb9, 0xb8, 0x9d, 0x2a,
	0x3d, 0x5d, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x3c, 0x5d, 0x94, 0x0c, 0xb9, 0xf8, 0x5d, 0x52, 0x73,
	0x52, 0x4b, 0x52, 0x53, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x41, 0x4a, 0xfc, 0xbd,
	0xc1, 0x4a, 0x38, 0x82, 0x98, 0xfc, 0xbd, 0xa1, 0x5a, 0x98, 0xe0, 0x5a, 0xb2, 0xb9, 0x78, 0x9d,
	0x8b, 0x52, 0x13, 0x4b, 0x52, 0x61, 0x66, 0xaa, 0x71, 0xf1, 0x05, 0xc0, 0x2d, 0xf4, 0x4b, 0xcc,
	0x4d, 0x85, 0x9a, 0x8f, 0x26, 0x2a, 0x24, 0xc5, 0xc5, 0x11, 0x90, 0x58, 0x92, 0x11, 0x54, 0x9a,
	0x93, 0x0a, 0x35, 0x0e, 0xce, 0x17, 0x12, 0xe3, 0x62, 0xf3, 0x4d, 0x2d, 0xc9, 0xc8, 0x4f, 0x91,
	0x60, 0x06, 0xcb, 0x40, 0x79, 0x4a, 0xd6, 0x5c, 0x92, 0x10, 0xcb, 0x52, 0x10, 0x86, 0x11, 0xeb,
	0x52, 0xa3, 0x56, 0x26, 0x2e, 0x2e, 0x84, 0x36, 0xa1, 0x06, 0x46, 0x2e, 0x01, 0x88, 0x61, 0x48,
	0x82, 0x7a, 0x7a, 0x04, 0x42, 0x50, 0x0f, 0xc5, 0xb3, 0x52, 0x56, 0x44, 0xaa, 0xc7, 0xe2, 0x5e,
	0x25, 0x06, 0xa1, 0x12, 0x2e, 0x01, 0x48, 0x70, 0x23, 0xb9, 0x40, 0x87, 0xa0, 0x89, 0x48, 0x11,
	0x28, 0x65, 0x40, 0x50, 0x35, 0x5a, 0x7c, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0xd3, 0x8a, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x3f, 0x1f, 0x50, 0x95, 0x50, 0x02, 0x00, 0x00,
}
