// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/club/club.proto

package iunite_club_srv_organization_club

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"
import proto1 "iunite.club/services/organization/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserClubProfileDetailsByIDRequest struct {
	OrganizationID       string   `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserClubProfileDetailsByIDRequest) Reset()         { *m = GetUserClubProfileDetailsByIDRequest{} }
func (m *GetUserClubProfileDetailsByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserClubProfileDetailsByIDRequest) ProtoMessage()    {}
func (*GetUserClubProfileDetailsByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{0}
}
func (m *GetUserClubProfileDetailsByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserClubProfileDetailsByIDRequest.Unmarshal(m, b)
}
func (m *GetUserClubProfileDetailsByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserClubProfileDetailsByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserClubProfileDetailsByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserClubProfileDetailsByIDRequest.Merge(dst, src)
}
func (m *GetUserClubProfileDetailsByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserClubProfileDetailsByIDRequest.Size(m)
}
func (m *GetUserClubProfileDetailsByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserClubProfileDetailsByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserClubProfileDetailsByIDRequest proto.InternalMessageInfo

func (m *GetUserClubProfileDetailsByIDRequest) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *GetUserClubProfileDetailsByIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserClubProfileResponse struct {
	UserClubProfile      *proto1.UserClubProfile `protobuf:"bytes,1,opt,name=UserClubProfile,proto3" json:"UserClubProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UserClubProfileResponse) Reset()         { *m = UserClubProfileResponse{} }
func (m *UserClubProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UserClubProfileResponse) ProtoMessage()    {}
func (*UserClubProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{1}
}
func (m *UserClubProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserClubProfileResponse.Unmarshal(m, b)
}
func (m *UserClubProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserClubProfileResponse.Marshal(b, m, deterministic)
}
func (dst *UserClubProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserClubProfileResponse.Merge(dst, src)
}
func (m *UserClubProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UserClubProfileResponse.Size(m)
}
func (m *UserClubProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserClubProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserClubProfileResponse proto.InternalMessageInfo

func (m *UserClubProfileResponse) GetUserClubProfile() *proto1.UserClubProfile {
	if m != nil {
		return m.UserClubProfile
	}
	return nil
}

type GetUserClubProfilesByUserIDRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserClubProfilesByUserIDRequest) Reset()         { *m = GetUserClubProfilesByUserIDRequest{} }
func (m *GetUserClubProfilesByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserClubProfilesByUserIDRequest) ProtoMessage()    {}
func (*GetUserClubProfilesByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{2}
}
func (m *GetUserClubProfilesByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserClubProfilesByUserIDRequest.Unmarshal(m, b)
}
func (m *GetUserClubProfilesByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserClubProfilesByUserIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserClubProfilesByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserClubProfilesByUserIDRequest.Merge(dst, src)
}
func (m *GetUserClubProfilesByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserClubProfilesByUserIDRequest.Size(m)
}
func (m *GetUserClubProfilesByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserClubProfilesByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserClubProfilesByUserIDRequest proto.InternalMessageInfo

func (m *GetUserClubProfilesByUserIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserClubProfilesListResponse struct {
	Total                int64                     `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	UserClubProfiles     []*proto1.UserClubProfile `protobuf:"bytes,2,rep,name=UserClubProfiles,proto3" json:"UserClubProfiles,omitempty"`
	FirstID              string                    `protobuf:"bytes,3,opt,name=FirstID,proto3" json:"FirstID,omitempty"`
	LastID               string                    `protobuf:"bytes,4,opt,name=LastID,proto3" json:"LastID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UserClubProfilesListResponse) Reset()         { *m = UserClubProfilesListResponse{} }
func (m *UserClubProfilesListResponse) String() string { return proto.CompactTextString(m) }
func (*UserClubProfilesListResponse) ProtoMessage()    {}
func (*UserClubProfilesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{3}
}
func (m *UserClubProfilesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserClubProfilesListResponse.Unmarshal(m, b)
}
func (m *UserClubProfilesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserClubProfilesListResponse.Marshal(b, m, deterministic)
}
func (dst *UserClubProfilesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserClubProfilesListResponse.Merge(dst, src)
}
func (m *UserClubProfilesListResponse) XXX_Size() int {
	return xxx_messageInfo_UserClubProfilesListResponse.Size(m)
}
func (m *UserClubProfilesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserClubProfilesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserClubProfilesListResponse proto.InternalMessageInfo

func (m *UserClubProfilesListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserClubProfilesListResponse) GetUserClubProfiles() []*proto1.UserClubProfile {
	if m != nil {
		return m.UserClubProfiles
	}
	return nil
}

func (m *UserClubProfilesListResponse) GetFirstID() string {
	if m != nil {
		return m.FirstID
	}
	return ""
}

func (m *UserClubProfilesListResponse) GetLastID() string {
	if m != nil {
		return m.LastID
	}
	return ""
}

type GetClubsBySchoolIDRequest struct {
	SchoolID             string   `protobuf:"bytes,1,opt,name=SchoolID,proto3" json:"SchoolID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClubsBySchoolIDRequest) Reset()         { *m = GetClubsBySchoolIDRequest{} }
func (m *GetClubsBySchoolIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetClubsBySchoolIDRequest) ProtoMessage()    {}
func (*GetClubsBySchoolIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{4}
}
func (m *GetClubsBySchoolIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClubsBySchoolIDRequest.Unmarshal(m, b)
}
func (m *GetClubsBySchoolIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClubsBySchoolIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetClubsBySchoolIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClubsBySchoolIDRequest.Merge(dst, src)
}
func (m *GetClubsBySchoolIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetClubsBySchoolIDRequest.Size(m)
}
func (m *GetClubsBySchoolIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClubsBySchoolIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClubsBySchoolIDRequest proto.InternalMessageInfo

func (m *GetClubsBySchoolIDRequest) GetSchoolID() string {
	if m != nil {
		return m.SchoolID
	}
	return ""
}

type UpdateClubInfoRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ToSet                []byte   `protobuf:"bytes,2,opt,name=ToSet,proto3" json:"ToSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClubInfoRequest) Reset()         { *m = UpdateClubInfoRequest{} }
func (m *UpdateClubInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClubInfoRequest) ProtoMessage()    {}
func (*UpdateClubInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{5}
}
func (m *UpdateClubInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClubInfoRequest.Unmarshal(m, b)
}
func (m *UpdateClubInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClubInfoRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateClubInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClubInfoRequest.Merge(dst, src)
}
func (m *UpdateClubInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClubInfoRequest.Size(m)
}
func (m *UpdateClubInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClubInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClubInfoRequest proto.InternalMessageInfo

func (m *UpdateClubInfoRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateClubInfoRequest) GetToSet() []byte {
	if m != nil {
		return m.ToSet
	}
	return nil
}

type UpdatedResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	UpdateAt             string   `protobuf:"bytes,2,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatedResponse) Reset()         { *m = UpdatedResponse{} }
func (m *UpdatedResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatedResponse) ProtoMessage()    {}
func (*UpdatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{6}
}
func (m *UpdatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedResponse.Unmarshal(m, b)
}
func (m *UpdatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedResponse.Merge(dst, src)
}
func (m *UpdatedResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatedResponse.Size(m)
}
func (m *UpdatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedResponse proto.InternalMessageInfo

func (m *UpdatedResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *UpdatedResponse) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

type GetClubByIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClubByIDRequest) Reset()         { *m = GetClubByIDRequest{} }
func (m *GetClubByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetClubByIDRequest) ProtoMessage()    {}
func (*GetClubByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{7}
}
func (m *GetClubByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClubByIDRequest.Unmarshal(m, b)
}
func (m *GetClubByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClubByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetClubByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClubByIDRequest.Merge(dst, src)
}
func (m *GetClubByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetClubByIDRequest.Size(m)
}
func (m *GetClubByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClubByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClubByIDRequest proto.InternalMessageInfo

func (m *GetClubByIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ClubDetailsResponse struct {
	Club                 *proto1.Organization `protobuf:"bytes,1,opt,name=Club,proto3" json:"Club,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClubDetailsResponse) Reset()         { *m = ClubDetailsResponse{} }
func (m *ClubDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*ClubDetailsResponse) ProtoMessage()    {}
func (*ClubDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{8}
}
func (m *ClubDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubDetailsResponse.Unmarshal(m, b)
}
func (m *ClubDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubDetailsResponse.Marshal(b, m, deterministic)
}
func (dst *ClubDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubDetailsResponse.Merge(dst, src)
}
func (m *ClubDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_ClubDetailsResponse.Size(m)
}
func (m *ClubDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClubDetailsResponse proto.InternalMessageInfo

func (m *ClubDetailsResponse) GetClub() *proto1.Organization {
	if m != nil {
		return m.Club
	}
	return nil
}

type FindRefusedAcceptRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRefusedAcceptRequest) Reset()         { *m = FindRefusedAcceptRequest{} }
func (m *FindRefusedAcceptRequest) String() string { return proto.CompactTextString(m) }
func (*FindRefusedAcceptRequest) ProtoMessage()    {}
func (*FindRefusedAcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{9}
}
func (m *FindRefusedAcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRefusedAcceptRequest.Unmarshal(m, b)
}
func (m *FindRefusedAcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRefusedAcceptRequest.Marshal(b, m, deterministic)
}
func (dst *FindRefusedAcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRefusedAcceptRequest.Merge(dst, src)
}
func (m *FindRefusedAcceptRequest) XXX_Size() int {
	return xxx_messageInfo_FindRefusedAcceptRequest.Size(m)
}
func (m *FindRefusedAcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRefusedAcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRefusedAcceptRequest proto.InternalMessageInfo

func (m *FindRefusedAcceptRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *FindRefusedAcceptRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindRefusedAcceptRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type SearchClubRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=Search,proto3" json:"Search,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchClubRequest) Reset()         { *m = SearchClubRequest{} }
func (m *SearchClubRequest) String() string { return proto.CompactTextString(m) }
func (*SearchClubRequest) ProtoMessage()    {}
func (*SearchClubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{10}
}
func (m *SearchClubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchClubRequest.Unmarshal(m, b)
}
func (m *SearchClubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchClubRequest.Marshal(b, m, deterministic)
}
func (dst *SearchClubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchClubRequest.Merge(dst, src)
}
func (m *SearchClubRequest) XXX_Size() int {
	return xxx_messageInfo_SearchClubRequest.Size(m)
}
func (m *SearchClubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchClubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchClubRequest proto.InternalMessageInfo

func (m *SearchClubRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *SearchClubRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchClubRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ExecuteJoinClubAcceptRequest struct {
	IsPassed             bool     `protobuf:"varint,1,opt,name=IsPassed,proto3" json:"IsPassed,omitempty"`
	AcceptID             string   `protobuf:"bytes,2,opt,name=AcceptID,proto3" json:"AcceptID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteJoinClubAcceptRequest) Reset()         { *m = ExecuteJoinClubAcceptRequest{} }
func (m *ExecuteJoinClubAcceptRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteJoinClubAcceptRequest) ProtoMessage()    {}
func (*ExecuteJoinClubAcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{11}
}
func (m *ExecuteJoinClubAcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteJoinClubAcceptRequest.Unmarshal(m, b)
}
func (m *ExecuteJoinClubAcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteJoinClubAcceptRequest.Marshal(b, m, deterministic)
}
func (dst *ExecuteJoinClubAcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteJoinClubAcceptRequest.Merge(dst, src)
}
func (m *ExecuteJoinClubAcceptRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteJoinClubAcceptRequest.Size(m)
}
func (m *ExecuteJoinClubAcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteJoinClubAcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteJoinClubAcceptRequest proto.InternalMessageInfo

func (m *ExecuteJoinClubAcceptRequest) GetIsPassed() bool {
	if m != nil {
		return m.IsPassed
	}
	return false
}

func (m *ExecuteJoinClubAcceptRequest) GetAcceptID() string {
	if m != nil {
		return m.AcceptID
	}
	return ""
}

type Response struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{12}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type AcceptJoinOneClubRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ClubID               string   `protobuf:"bytes,2,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	JobID                string   `protobuf:"bytes,3,opt,name=JobID,proto3" json:"JobID,omitempty"`
	DepartmentID         string   `protobuf:"bytes,4,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptJoinOneClubRequest) Reset()         { *m = AcceptJoinOneClubRequest{} }
func (m *AcceptJoinOneClubRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptJoinOneClubRequest) ProtoMessage()    {}
func (*AcceptJoinOneClubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{13}
}
func (m *AcceptJoinOneClubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptJoinOneClubRequest.Unmarshal(m, b)
}
func (m *AcceptJoinOneClubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptJoinOneClubRequest.Marshal(b, m, deterministic)
}
func (dst *AcceptJoinOneClubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptJoinOneClubRequest.Merge(dst, src)
}
func (m *AcceptJoinOneClubRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptJoinOneClubRequest.Size(m)
}
func (m *AcceptJoinOneClubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptJoinOneClubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptJoinOneClubRequest proto.InternalMessageInfo

func (m *AcceptJoinOneClubRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AcceptJoinOneClubRequest) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

func (m *AcceptJoinOneClubRequest) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *AcceptJoinOneClubRequest) GetDepartmentID() string {
	if m != nil {
		return m.DepartmentID
	}
	return ""
}

type GetClubsByUserIDRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClubsByUserIDRequest) Reset()         { *m = GetClubsByUserIDRequest{} }
func (m *GetClubsByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetClubsByUserIDRequest) ProtoMessage()    {}
func (*GetClubsByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{14}
}
func (m *GetClubsByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClubsByUserIDRequest.Unmarshal(m, b)
}
func (m *GetClubsByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClubsByUserIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetClubsByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClubsByUserIDRequest.Merge(dst, src)
}
func (m *GetClubsByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetClubsByUserIDRequest.Size(m)
}
func (m *GetClubsByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClubsByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClubsByUserIDRequest proto.InternalMessageInfo

func (m *GetClubsByUserIDRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetClubsByUserIDRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetClubsByUserIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CreateClubRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SchoolID             string   `protobuf:"bytes,2,opt,name=SchoolID,proto3" json:"SchoolID,omitempty"`
	Scale                int32    `protobuf:"varint,3,opt,name=Scale,proto3" json:"Scale,omitempty"`
	Paperworks           []string `protobuf:"bytes,4,rep,name=Paperworks,proto3" json:"Paperworks,omitempty"`
	CreatorID            string   `protobuf:"bytes,5,opt,name=CreatorID,proto3" json:"CreatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClubRequest) Reset()         { *m = CreateClubRequest{} }
func (m *CreateClubRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClubRequest) ProtoMessage()    {}
func (*CreateClubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{15}
}
func (m *CreateClubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClubRequest.Unmarshal(m, b)
}
func (m *CreateClubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClubRequest.Marshal(b, m, deterministic)
}
func (dst *CreateClubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClubRequest.Merge(dst, src)
}
func (m *CreateClubRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClubRequest.Size(m)
}
func (m *CreateClubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClubRequest proto.InternalMessageInfo

func (m *CreateClubRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClubRequest) GetSchoolID() string {
	if m != nil {
		return m.SchoolID
	}
	return ""
}

func (m *CreateClubRequest) GetScale() int32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *CreateClubRequest) GetPaperworks() []string {
	if m != nil {
		return m.Paperworks
	}
	return nil
}

func (m *CreateClubRequest) GetCreatorID() string {
	if m != nil {
		return m.CreatorID
	}
	return ""
}

type CreateClubResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClubResponse) Reset()         { *m = CreateClubResponse{} }
func (m *CreateClubResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClubResponse) ProtoMessage()    {}
func (*CreateClubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{16}
}
func (m *CreateClubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClubResponse.Unmarshal(m, b)
}
func (m *CreateClubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClubResponse.Marshal(b, m, deterministic)
}
func (dst *CreateClubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClubResponse.Merge(dst, src)
}
func (m *CreateClubResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClubResponse.Size(m)
}
func (m *CreateClubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClubResponse proto.InternalMessageInfo

func (m *CreateClubResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type GetClubListRequest struct {
	SinceFlag            string   `protobuf:"bytes,1,opt,name=SinceFlag,proto3" json:"SinceFlag,omitempty"`
	MaxFlag              string   `protobuf:"bytes,2,opt,name=MaxFlag,proto3" json:"MaxFlag,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClubListRequest) Reset()         { *m = GetClubListRequest{} }
func (m *GetClubListRequest) String() string { return proto.CompactTextString(m) }
func (*GetClubListRequest) ProtoMessage()    {}
func (*GetClubListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{17}
}
func (m *GetClubListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClubListRequest.Unmarshal(m, b)
}
func (m *GetClubListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClubListRequest.Marshal(b, m, deterministic)
}
func (dst *GetClubListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClubListRequest.Merge(dst, src)
}
func (m *GetClubListRequest) XXX_Size() int {
	return xxx_messageInfo_GetClubListRequest.Size(m)
}
func (m *GetClubListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClubListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClubListRequest proto.InternalMessageInfo

func (m *GetClubListRequest) GetSinceFlag() string {
	if m != nil {
		return m.SinceFlag
	}
	return ""
}

func (m *GetClubListRequest) GetMaxFlag() string {
	if m != nil {
		return m.MaxFlag
	}
	return ""
}

func (m *GetClubListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetClubListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ClubListResponse struct {
	Total                int64                  `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Organizations        []*proto1.Organization `protobuf:"bytes,2,rep,name=Organizations,proto3" json:"Organizations,omitempty"`
	FirstID              string                 `protobuf:"bytes,3,opt,name=FirstID,proto3" json:"FirstID,omitempty"`
	LastID               string                 `protobuf:"bytes,4,opt,name=LastID,proto3" json:"LastID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ClubListResponse) Reset()         { *m = ClubListResponse{} }
func (m *ClubListResponse) String() string { return proto.CompactTextString(m) }
func (*ClubListResponse) ProtoMessage()    {}
func (*ClubListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{18}
}
func (m *ClubListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubListResponse.Unmarshal(m, b)
}
func (m *ClubListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubListResponse.Marshal(b, m, deterministic)
}
func (dst *ClubListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubListResponse.Merge(dst, src)
}
func (m *ClubListResponse) XXX_Size() int {
	return xxx_messageInfo_ClubListResponse.Size(m)
}
func (m *ClubListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClubListResponse proto.InternalMessageInfo

func (m *ClubListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ClubListResponse) GetOrganizations() []*proto1.Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func (m *ClubListResponse) GetFirstID() string {
	if m != nil {
		return m.FirstID
	}
	return ""
}

func (m *ClubListResponse) GetLastID() string {
	if m != nil {
		return m.LastID
	}
	return ""
}

type AcceptListResponse struct {
	Total                int64                `protobuf:"varint,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Accepts              []*proto1.ClubAccept `protobuf:"bytes,2,rep,name=Accepts,proto3" json:"Accepts,omitempty"`
	FirstID              string               `protobuf:"bytes,3,opt,name=FirstID,proto3" json:"FirstID,omitempty"`
	LastID               string               `protobuf:"bytes,4,opt,name=LastID,proto3" json:"LastID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AcceptListResponse) Reset()         { *m = AcceptListResponse{} }
func (m *AcceptListResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptListResponse) ProtoMessage()    {}
func (*AcceptListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_club_7e58954a3366a0cc, []int{19}
}
func (m *AcceptListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptListResponse.Unmarshal(m, b)
}
func (m *AcceptListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptListResponse.Marshal(b, m, deterministic)
}
func (dst *AcceptListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptListResponse.Merge(dst, src)
}
func (m *AcceptListResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptListResponse.Size(m)
}
func (m *AcceptListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptListResponse proto.InternalMessageInfo

func (m *AcceptListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *AcceptListResponse) GetAccepts() []*proto1.ClubAccept {
	if m != nil {
		return m.Accepts
	}
	return nil
}

func (m *AcceptListResponse) GetFirstID() string {
	if m != nil {
		return m.FirstID
	}
	return ""
}

func (m *AcceptListResponse) GetLastID() string {
	if m != nil {
		return m.LastID
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserClubProfileDetailsByIDRequest)(nil), "iunite.club.srv.organization.club.GetUserClubProfileDetailsByIDRequest")
	proto.RegisterType((*UserClubProfileResponse)(nil), "iunite.club.srv.organization.club.UserClubProfileResponse")
	proto.RegisterType((*GetUserClubProfilesByUserIDRequest)(nil), "iunite.club.srv.organization.club.GetUserClubProfilesByUserIDRequest")
	proto.RegisterType((*UserClubProfilesListResponse)(nil), "iunite.club.srv.organization.club.UserClubProfilesListResponse")
	proto.RegisterType((*GetClubsBySchoolIDRequest)(nil), "iunite.club.srv.organization.club.GetClubsBySchoolIDRequest")
	proto.RegisterType((*UpdateClubInfoRequest)(nil), "iunite.club.srv.organization.club.UpdateClubInfoRequest")
	proto.RegisterType((*UpdatedResponse)(nil), "iunite.club.srv.organization.club.UpdatedResponse")
	proto.RegisterType((*GetClubByIDRequest)(nil), "iunite.club.srv.organization.club.GetClubByIDRequest")
	proto.RegisterType((*ClubDetailsResponse)(nil), "iunite.club.srv.organization.club.ClubDetailsResponse")
	proto.RegisterType((*FindRefusedAcceptRequest)(nil), "iunite.club.srv.organization.club.FindRefusedAcceptRequest")
	proto.RegisterType((*SearchClubRequest)(nil), "iunite.club.srv.organization.club.SearchClubRequest")
	proto.RegisterType((*ExecuteJoinClubAcceptRequest)(nil), "iunite.club.srv.organization.club.ExecuteJoinClubAcceptRequest")
	proto.RegisterType((*Response)(nil), "iunite.club.srv.organization.club.Response")
	proto.RegisterType((*AcceptJoinOneClubRequest)(nil), "iunite.club.srv.organization.club.AcceptJoinOneClubRequest")
	proto.RegisterType((*GetClubsByUserIDRequest)(nil), "iunite.club.srv.organization.club.GetClubsByUserIDRequest")
	proto.RegisterType((*CreateClubRequest)(nil), "iunite.club.srv.organization.club.CreateClubRequest")
	proto.RegisterType((*CreateClubResponse)(nil), "iunite.club.srv.organization.club.CreateClubResponse")
	proto.RegisterType((*GetClubListRequest)(nil), "iunite.club.srv.organization.club.GetClubListRequest")
	proto.RegisterType((*ClubListResponse)(nil), "iunite.club.srv.organization.club.ClubListResponse")
	proto.RegisterType((*AcceptListResponse)(nil), "iunite.club.srv.organization.club.AcceptListResponse")
}

func init() { proto.RegisterFile("proto/club/club.proto", fileDescriptor_club_7e58954a3366a0cc) }

var fileDescriptor_club_7e58954a3366a0cc = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xd8, 0x4e, 0x9a, 0xbc, 0xb6, 0x69, 0x32, 0x25, 0xad, 0xb3, 0x04, 0x14, 0x46, 0x15,
	0x8a, 0x40, 0xd8, 0x52, 0xca, 0x97, 0x42, 0x0b, 0xaa, 0xeb, 0x26, 0x72, 0x1b, 0x88, 0xb5, 0x26,
	0x20, 0x04, 0x97, 0xf5, 0x7a, 0xec, 0xae, 0xd8, 0xec, 0x9a, 0x9d, 0x71, 0xa8, 0xcb, 0x01, 0x84,
	0xf8, 0x90, 0xb8, 0x71, 0xca, 0x95, 0x13, 0x5c, 0xf8, 0x27, 0xf8, 0xcf, 0xd0, 0xcc, 0xec, 0xc7,
	0xec, 0x6e, 0xe2, 0xec, 0xfa, 0x62, 0xf9, 0xbd, 0x99, 0xf7, 0x9b, 0xdf, 0xfb, 0xdc, 0x19, 0xd8,
	0x9c, 0x04, 0x3e, 0xf7, 0x5b, 0xb6, 0x3b, 0x1d, 0xc8, 0x9f, 0xa6, 0x94, 0xf1, 0x1b, 0xce, 0xd4,
	0x73, 0x38, 0x6d, 0x4a, 0x15, 0x0b, 0xce, 0x9a, 0x7e, 0x30, 0xb6, 0x3c, 0xe7, 0xa5, 0xc5, 0x1d,
	0xdf, 0x93, 0x5a, 0x63, 0x5f, 0xdb, 0xd2, 0x62, 0x34, 0x38, 0x73, 0x6c, 0xca, 0x5a, 0xfa, 0xbe,
	0x96, 0xc2, 0x4e, 0x99, 0x4a, 0x95, 0xb1, 0x35, 0xf6, 0xfd, 0xb1, 0x4b, 0xd5, 0x86, 0xc1, 0x74,
	0xd4, 0xb2, 0xbc, 0x99, 0x5a, 0x22, 0x23, 0xb8, 0x77, 0x48, 0xf9, 0x09, 0xa3, 0xc1, 0x63, 0x77,
	0x3a, 0xe8, 0x05, 0xfe, 0xc8, 0x71, 0x69, 0x87, 0x72, 0xcb, 0x71, 0x59, 0x7b, 0xd6, 0xed, 0x98,
	0xf4, 0xbb, 0x29, 0x65, 0x1c, 0xbf, 0x09, 0x6b, 0xc7, 0x1a, 0x70, 0xb7, 0xd3, 0x40, 0x3b, 0x68,
	0x77, 0xd5, 0xcc, 0x68, 0xf1, 0x1d, 0x58, 0x16, 0x60, 0xdd, 0x4e, 0xa3, 0x2a, 0xd7, 0x43, 0x89,
	0x04, 0x70, 0x37, 0x73, 0x88, 0x49, 0xd9, 0xc4, 0xf7, 0x18, 0xc5, 0x5f, 0xc2, 0xad, 0xcc, 0x92,
	0xc4, 0xbe, 0xbe, 0xf7, 0x4e, 0x73, 0x6e, 0x58, 0xb2, 0x78, 0x59, 0x14, 0xf2, 0x00, 0x48, 0xde,
	0x37, 0xd6, 0x9e, 0x29, 0x4a, 0x91, 0x67, 0x09, 0x63, 0x94, 0x62, 0xfc, 0x1f, 0x82, 0xed, 0xac,
	0xed, 0x91, 0xc3, 0x78, 0xcc, 0xfb, 0x15, 0x58, 0xfa, 0xdc, 0xe7, 0x96, 0x2b, 0xed, 0x6a, 0xa6,
	0x12, 0xf0, 0x57, 0xb0, 0x9e, 0xb5, 0x6a, 0x54, 0x77, 0x6a, 0xe5, 0xdd, 0xc9, 0xc1, 0xe0, 0x06,
	0x5c, 0x3b, 0x70, 0x02, 0xc6, 0xbb, 0x9d, 0x46, 0x4d, 0x52, 0x8d, 0x44, 0xe1, 0xc3, 0x91, 0x25,
	0x17, 0xea, 0xca, 0x07, 0x25, 0x91, 0x0f, 0x60, 0xeb, 0x90, 0x72, 0x01, 0xc2, 0xda, 0xb3, 0xbe,
	0xfd, 0xdc, 0xf7, 0xdd, 0xc4, 0x71, 0x03, 0x56, 0x22, 0x55, 0xe8, 0x7a, 0x2c, 0x93, 0x87, 0xb0,
	0x79, 0x32, 0x19, 0x5a, 0x9c, 0x0a, 0xdb, 0xae, 0x37, 0xf2, 0x23, 0xa3, 0x35, 0xa8, 0xc6, 0xdb,
	0xab, 0xdd, 0x8e, 0x0a, 0x42, 0x9f, 0x72, 0x99, 0xee, 0x1b, 0xa6, 0x12, 0xc8, 0x43, 0xb8, 0xa5,
	0xcc, 0x87, 0x71, 0xb4, 0xd6, 0xa0, 0x7a, 0xfc, 0x4c, 0x1a, 0xae, 0x98, 0xd5, 0xe3, 0x67, 0xe2,
	0x74, 0xb5, 0xe5, 0x11, 0x0f, 0x4b, 0x25, 0x96, 0xc9, 0x3d, 0xc0, 0x21, 0x6d, 0xbd, 0x04, 0x33,
	0x47, 0x93, 0x13, 0xb8, 0x2d, 0xb6, 0x84, 0xc5, 0x1a, 0x1f, 0xf4, 0x31, 0xd4, 0x85, 0x3a, 0xac,
	0xa1, 0xb7, 0xe6, 0x07, 0x5d, 0xaf, 0x5e, 0x53, 0xda, 0x91, 0x6f, 0xa0, 0x71, 0xe0, 0x78, 0x43,
	0x93, 0x8e, 0xa6, 0x8c, 0x0e, 0x1f, 0xd9, 0x36, 0x9d, 0xf0, 0x2b, 0x6a, 0x05, 0x63, 0xa8, 0xf7,
	0xac, 0x31, 0x95, 0x8e, 0xd4, 0x4c, 0xf9, 0x5f, 0x44, 0xe6, 0xc8, 0x39, 0x75, 0xb8, 0xcc, 0x55,
	0xcd, 0x54, 0x02, 0x39, 0x81, 0x8d, 0x3e, 0xb5, 0x02, 0xfb, 0xb9, 0x38, 0x4b, 0x83, 0x55, 0xca,
	0x08, 0x56, 0x49, 0x25, 0x60, 0xbf, 0x80, 0xed, 0x27, 0x2f, 0xa8, 0x3d, 0xe5, 0xf4, 0xa9, 0xef,
	0x78, 0x02, 0x3b, 0x4d, 0xdc, 0x80, 0x95, 0x2e, 0xeb, 0x59, 0x8c, 0xd1, 0x61, 0x98, 0x83, 0x58,
	0x16, 0x6b, 0x6a, 0x73, 0xdc, 0xb4, 0xb1, 0x4c, 0x0c, 0x58, 0xb9, 0x2c, 0x83, 0xe4, 0x17, 0x04,
	0x0d, 0xb5, 0x51, 0x9c, 0x79, 0xec, 0xd1, 0x8c, 0x4b, 0x17, 0x46, 0xea, 0x0e, 0x2c, 0xcb, 0x92,
	0x8a, 0xe7, 0x83, 0x92, 0x84, 0x5b, 0x4f, 0xfd, 0x41, 0x5c, 0xd9, 0x4a, 0xc0, 0x04, 0x6e, 0x74,
	0xe8, 0xc4, 0x0a, 0xf8, 0x29, 0xf5, 0x92, 0xea, 0x4e, 0xe9, 0xc8, 0xd7, 0x70, 0x37, 0xa9, 0xf1,
	0x74, 0x6b, 0x47, 0xf1, 0x43, 0x17, 0xc5, 0xaf, 0xaa, 0xc5, 0x4f, 0xa3, 0x5b, 0x4b, 0x0d, 0x81,
	0x73, 0x04, 0x1b, 0x8f, 0x03, 0x1a, 0x36, 0x82, 0x86, 0xfb, 0x99, 0x75, 0x4a, 0x43, 0xd7, 0xe4,
	0xff, 0x54, 0x37, 0x55, 0xd3, 0xdd, 0x24, 0xce, 0xec, 0xdb, 0x96, 0x4b, 0x25, 0xf8, 0x92, 0xa9,
	0x04, 0xfc, 0x3a, 0x40, 0xcf, 0x9a, 0xd0, 0xe0, 0x7b, 0x3f, 0xf8, 0x96, 0x35, 0xea, 0x3b, 0xb5,
	0xdd, 0x55, 0x53, 0xd3, 0xe0, 0x6d, 0x58, 0x95, 0x47, 0xfb, 0x82, 0xd6, 0x92, 0x84, 0x4c, 0x14,
	0xa2, 0x47, 0x74, 0x62, 0x97, 0xe4, 0xe8, 0x2c, 0xee, 0x24, 0x35, 0xba, 0x14, 0xff, 0x6d, 0x58,
	0xed, 0x3b, 0x9e, 0x4d, 0x0f, 0x5c, 0x6b, 0x1c, 0x3a, 0x91, 0x28, 0xc4, 0x98, 0xf9, 0xd4, 0x7a,
	0x21, 0xd7, 0x94, 0x23, 0x91, 0x28, 0xfc, 0x9e, 0x88, 0x78, 0xaa, 0xd2, 0x93, 0xff, 0x85, 0x6f,
	0xae, 0x8c, 0x67, 0x5d, 0xc5, 0x53, 0x0a, 0xe4, 0x5f, 0x04, 0xeb, 0xc9, 0xa9, 0x73, 0x07, 0x66,
	0x0f, 0x6e, 0xea, 0x5d, 0x18, 0x4d, 0xcb, 0x32, 0x8d, 0x9b, 0x06, 0x58, 0x60, 0x4e, 0xfe, 0x85,
	0x00, 0xab, 0x52, 0x2e, 0x40, 0xb8, 0x0d, 0xd7, 0xd4, 0xde, 0x88, 0xea, 0xee, 0x7c, 0xaa, 0x5a,
	0x37, 0x46, 0x86, 0xe5, 0x29, 0xee, 0x9d, 0xdf, 0x54, 0x73, 0x0d, 0xff, 0x00, 0x90, 0x24, 0x1e,
	0xbf, 0xdb, 0xbc, 0xf2, 0xea, 0xd0, 0xcc, 0x15, 0xb0, 0xf1, 0x5e, 0x49, 0x2b, 0x15, 0x0f, 0x52,
	0xc1, 0x3f, 0x23, 0xc0, 0x62, 0x3a, 0x46, 0xb9, 0x6d, 0xcf, 0x64, 0x53, 0x15, 0xc1, 0xcb, 0xd7,
	0xa1, 0x71, 0xbf, 0x08, 0x8d, 0x4c, 0x15, 0x91, 0x0a, 0xfe, 0x15, 0xc1, 0x7a, 0xb6, 0xe5, 0xf1,
	0x7e, 0x71, 0x0a, 0xd9, 0x39, 0xb1, 0x28, 0x8f, 0x1f, 0x61, 0x23, 0x37, 0xff, 0xf0, 0x47, 0x05,
	0xb0, 0x2e, 0x9b, 0x9a, 0xc6, 0xdb, 0x05, 0x8c, 0x35, 0x02, 0xbf, 0x23, 0xd8, 0xbc, 0x70, 0xec,
	0xe3, 0x4f, 0x0a, 0x00, 0xcd, 0xfb, 0x60, 0x94, 0x65, 0xf2, 0x12, 0xae, 0x27, 0x9f, 0x35, 0x56,
	0xa8, 0x2a, 0x73, 0x9f, 0xc1, 0x45, 0xd3, 0xf0, 0x27, 0x82, 0xad, 0xdc, 0x17, 0x3b, 0xae, 0x8b,
	0x22, 0xf9, 0xb8, 0xec, 0x7b, 0x5f, 0xa8, 0x4f, 0xf2, 0x73, 0x83, 0x54, 0xf0, 0x6f, 0x08, 0x6e,
	0x47, 0x7d, 0xa2, 0xdd, 0xa6, 0xcb, 0x34, 0x8a, 0x76, 0xf5, 0x31, 0xde, 0x2f, 0x18, 0x99, 0xcc,
	0x5d, 0x88, 0x54, 0xf0, 0x4f, 0x08, 0xd6, 0xd2, 0x37, 0x39, 0xfc, 0x61, 0x01, 0xb0, 0x0b, 0x2f,
	0x7f, 0xc6, 0x5e, 0x61, 0xcb, 0xa1, 0x46, 0xe1, 0x0f, 0x2d, 0x16, 0xda, 0x35, 0x14, 0x3f, 0x28,
	0xd5, 0xb1, 0x99, 0xdb, 0xeb, 0xa2, 0xc5, 0xf2, 0x0f, 0x82, 0x57, 0xe7, 0x3c, 0x0a, 0xf0, 0x93,
	0x62, 0xa4, 0xae, 0x78, 0x54, 0x18, 0x45, 0xfa, 0x6f, 0xde, 0xe3, 0x82, 0x54, 0xf0, 0xdf, 0x08,
	0x5e, 0x9b, 0xfb, 0x34, 0xc3, 0x87, 0x0b, 0x71, 0xcd, 0x3f, 0xee, 0x8c, 0xfd, 0xf2, 0x6c, 0x13,
	0xa2, 0x83, 0x65, 0xf9, 0x92, 0xbc, 0xff, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x84, 0xf5,
	0x35, 0xdc, 0x0e, 0x00, 0x00,
}
