// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/recruitment/recruitment.proto

package iunite_club_srv_core_recruitment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import proto1 "iunite.club/services/organization/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreatedResponse struct {
	OK                   bool               `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	Record               *RecruitmentRecord `protobuf:"bytes,2,opt,name=Record,proto3" json:"Record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreatedResponse) Reset()         { *m = CreatedResponse{} }
func (m *CreatedResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedResponse) ProtoMessage()    {}
func (*CreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{0}
}
func (m *CreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedResponse.Unmarshal(m, b)
}
func (m *CreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedResponse.Marshal(b, m, deterministic)
}
func (dst *CreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedResponse.Merge(dst, src)
}
func (m *CreatedResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedResponse.Size(m)
}
func (m *CreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedResponse proto.InternalMessageInfo

func (m *CreatedResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *CreatedResponse) GetRecord() *RecruitmentRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type FindRecruitmentFormRecordRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Department           string   `protobuf:"bytes,3,opt,name=Department,proto3" json:"Department,omitempty"`
	State                int32    `protobuf:"varint,4,opt,name=State,proto3" json:"State,omitempty"`
	RecordID             string   `protobuf:"bytes,5,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRecruitmentFormRecordRequest) Reset()         { *m = FindRecruitmentFormRecordRequest{} }
func (m *FindRecruitmentFormRecordRequest) String() string { return proto.CompactTextString(m) }
func (*FindRecruitmentFormRecordRequest) ProtoMessage()    {}
func (*FindRecruitmentFormRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{1}
}
func (m *FindRecruitmentFormRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRecruitmentFormRecordRequest.Unmarshal(m, b)
}
func (m *FindRecruitmentFormRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRecruitmentFormRecordRequest.Marshal(b, m, deterministic)
}
func (dst *FindRecruitmentFormRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRecruitmentFormRecordRequest.Merge(dst, src)
}
func (m *FindRecruitmentFormRecordRequest) XXX_Size() int {
	return xxx_messageInfo_FindRecruitmentFormRecordRequest.Size(m)
}
func (m *FindRecruitmentFormRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRecruitmentFormRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRecruitmentFormRecordRequest proto.InternalMessageInfo

func (m *FindRecruitmentFormRecordRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindRecruitmentFormRecordRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindRecruitmentFormRecordRequest) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *FindRecruitmentFormRecordRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *FindRecruitmentFormRecordRequest) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

type RecruitmentFormRecordsResponse struct {
	Records              []*RecruitmentFormRecord `protobuf:"bytes,1,rep,name=Records,proto3" json:"Records,omitempty"`
	Total                int32                    `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RecruitmentFormRecordsResponse) Reset()         { *m = RecruitmentFormRecordsResponse{} }
func (m *RecruitmentFormRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*RecruitmentFormRecordsResponse) ProtoMessage()    {}
func (*RecruitmentFormRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{2}
}
func (m *RecruitmentFormRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentFormRecordsResponse.Unmarshal(m, b)
}
func (m *RecruitmentFormRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentFormRecordsResponse.Marshal(b, m, deterministic)
}
func (dst *RecruitmentFormRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentFormRecordsResponse.Merge(dst, src)
}
func (m *RecruitmentFormRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_RecruitmentFormRecordsResponse.Size(m)
}
func (m *RecruitmentFormRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentFormRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentFormRecordsResponse proto.InternalMessageInfo

func (m *RecruitmentFormRecordsResponse) GetRecords() []*RecruitmentFormRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *RecruitmentFormRecordsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Response struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type AdjustOnePostRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DepartmentID         string   `protobuf:"bytes,2,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdjustOnePostRequest) Reset()         { *m = AdjustOnePostRequest{} }
func (m *AdjustOnePostRequest) String() string { return proto.CompactTextString(m) }
func (*AdjustOnePostRequest) ProtoMessage()    {}
func (*AdjustOnePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{4}
}
func (m *AdjustOnePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdjustOnePostRequest.Unmarshal(m, b)
}
func (m *AdjustOnePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdjustOnePostRequest.Marshal(b, m, deterministic)
}
func (dst *AdjustOnePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdjustOnePostRequest.Merge(dst, src)
}
func (m *AdjustOnePostRequest) XXX_Size() int {
	return xxx_messageInfo_AdjustOnePostRequest.Size(m)
}
func (m *AdjustOnePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdjustOnePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdjustOnePostRequest proto.InternalMessageInfo

func (m *AdjustOnePostRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AdjustOnePostRequest) GetDepartmentID() string {
	if m != nil {
		return m.DepartmentID
	}
	return ""
}

type PassedOnePostRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassedOnePostRequest) Reset()         { *m = PassedOnePostRequest{} }
func (m *PassedOnePostRequest) String() string { return proto.CompactTextString(m) }
func (*PassedOnePostRequest) ProtoMessage()    {}
func (*PassedOnePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{5}
}
func (m *PassedOnePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassedOnePostRequest.Unmarshal(m, b)
}
func (m *PassedOnePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassedOnePostRequest.Marshal(b, m, deterministic)
}
func (dst *PassedOnePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassedOnePostRequest.Merge(dst, src)
}
func (m *PassedOnePostRequest) XXX_Size() int {
	return xxx_messageInfo_PassedOnePostRequest.Size(m)
}
func (m *PassedOnePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PassedOnePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PassedOnePostRequest proto.InternalMessageInfo

func (m *PassedOnePostRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RefusedOnePostRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefusedOnePostRequest) Reset()         { *m = RefusedOnePostRequest{} }
func (m *RefusedOnePostRequest) String() string { return proto.CompactTextString(m) }
func (*RefusedOnePostRequest) ProtoMessage()    {}
func (*RefusedOnePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{6}
}
func (m *RefusedOnePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefusedOnePostRequest.Unmarshal(m, b)
}
func (m *RefusedOnePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefusedOnePostRequest.Marshal(b, m, deterministic)
}
func (dst *RefusedOnePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefusedOnePostRequest.Merge(dst, src)
}
func (m *RefusedOnePostRequest) XXX_Size() int {
	return xxx_messageInfo_RefusedOnePostRequest.Size(m)
}
func (m *RefusedOnePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefusedOnePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefusedOnePostRequest proto.InternalMessageInfo

func (m *RefusedOnePostRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ByClubIDRequest struct {
	ClubID               string   `protobuf:"bytes,1,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByClubIDRequest) Reset()         { *m = ByClubIDRequest{} }
func (m *ByClubIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByClubIDRequest) ProtoMessage()    {}
func (*ByClubIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{7}
}
func (m *ByClubIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByClubIDRequest.Unmarshal(m, b)
}
func (m *ByClubIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByClubIDRequest.Marshal(b, m, deterministic)
}
func (dst *ByClubIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByClubIDRequest.Merge(dst, src)
}
func (m *ByClubIDRequest) XXX_Size() int {
	return xxx_messageInfo_ByClubIDRequest.Size(m)
}
func (m *ByClubIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByClubIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByClubIDRequest proto.InternalMessageInfo

func (m *ByClubIDRequest) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

type RecruitmentForm struct {
	ID                   string                  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp    `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp    `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Name                 string                  `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	RecordID             string                  `protobuf:"bytes,5,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Fields               []*RecruitmentFormField `protobuf:"bytes,6,rep,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RecruitmentForm) Reset()         { *m = RecruitmentForm{} }
func (m *RecruitmentForm) String() string { return proto.CompactTextString(m) }
func (*RecruitmentForm) ProtoMessage()    {}
func (*RecruitmentForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{8}
}
func (m *RecruitmentForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentForm.Unmarshal(m, b)
}
func (m *RecruitmentForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentForm.Marshal(b, m, deterministic)
}
func (dst *RecruitmentForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentForm.Merge(dst, src)
}
func (m *RecruitmentForm) XXX_Size() int {
	return xxx_messageInfo_RecruitmentForm.Size(m)
}
func (m *RecruitmentForm) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentForm.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentForm proto.InternalMessageInfo

func (m *RecruitmentForm) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecruitmentForm) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RecruitmentForm) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RecruitmentForm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecruitmentForm) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *RecruitmentForm) GetFields() []*RecruitmentFormField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type RecruitmentAnswer struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FormID               string   `protobuf:"bytes,2,opt,name=FormID,proto3" json:"FormID,omitempty"`
	ItemKey              string   `protobuf:"bytes,3,opt,name=ItemKey,proto3" json:"ItemKey,omitempty"`
	Answer               string   `protobuf:"bytes,4,opt,name=Answer,proto3" json:"Answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecruitmentAnswer) Reset()         { *m = RecruitmentAnswer{} }
func (m *RecruitmentAnswer) String() string { return proto.CompactTextString(m) }
func (*RecruitmentAnswer) ProtoMessage()    {}
func (*RecruitmentAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{9}
}
func (m *RecruitmentAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentAnswer.Unmarshal(m, b)
}
func (m *RecruitmentAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentAnswer.Marshal(b, m, deterministic)
}
func (dst *RecruitmentAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentAnswer.Merge(dst, src)
}
func (m *RecruitmentAnswer) XXX_Size() int {
	return xxx_messageInfo_RecruitmentAnswer.Size(m)
}
func (m *RecruitmentAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentAnswer proto.InternalMessageInfo

func (m *RecruitmentAnswer) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecruitmentAnswer) GetFormID() string {
	if m != nil {
		return m.FormID
	}
	return ""
}

func (m *RecruitmentAnswer) GetItemKey() string {
	if m != nil {
		return m.ItemKey
	}
	return ""
}

func (m *RecruitmentAnswer) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type RecruitmentFormRecord struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Mobile               string               `protobuf:"bytes,4,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Major                string               `protobuf:"bytes,6,opt,name=Major,proto3" json:"Major,omitempty"`
	Age                  int32                `protobuf:"varint,7,opt,name=Age,proto3" json:"Age,omitempty"`
	SchoolStudentID      string               `protobuf:"bytes,8,opt,name=SchoolStudentID,proto3" json:"SchoolStudentID,omitempty"`
	DepartmentID         string               `protobuf:"bytes,9,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	RecordID             string               `protobuf:"bytes,10,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	Status               int32                `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`
	Answers              []*RecruitmentAnswer `protobuf:"bytes,12,rep,name=Answers,proto3" json:"Answers,omitempty"`
	Department           *proto1.Organization `protobuf:"bytes,13,opt,name=Department,proto3" json:"Department,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecruitmentFormRecord) Reset()         { *m = RecruitmentFormRecord{} }
func (m *RecruitmentFormRecord) String() string { return proto.CompactTextString(m) }
func (*RecruitmentFormRecord) ProtoMessage()    {}
func (*RecruitmentFormRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{10}
}
func (m *RecruitmentFormRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentFormRecord.Unmarshal(m, b)
}
func (m *RecruitmentFormRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentFormRecord.Marshal(b, m, deterministic)
}
func (dst *RecruitmentFormRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentFormRecord.Merge(dst, src)
}
func (m *RecruitmentFormRecord) XXX_Size() int {
	return xxx_messageInfo_RecruitmentFormRecord.Size(m)
}
func (m *RecruitmentFormRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentFormRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentFormRecord proto.InternalMessageInfo

func (m *RecruitmentFormRecord) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecruitmentFormRecord) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RecruitmentFormRecord) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RecruitmentFormRecord) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RecruitmentFormRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecruitmentFormRecord) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func (m *RecruitmentFormRecord) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RecruitmentFormRecord) GetSchoolStudentID() string {
	if m != nil {
		return m.SchoolStudentID
	}
	return ""
}

func (m *RecruitmentFormRecord) GetDepartmentID() string {
	if m != nil {
		return m.DepartmentID
	}
	return ""
}

func (m *RecruitmentFormRecord) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

func (m *RecruitmentFormRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RecruitmentFormRecord) GetAnswers() []*RecruitmentAnswer {
	if m != nil {
		return m.Answers
	}
	return nil
}

func (m *RecruitmentFormRecord) GetDepartment() *proto1.Organization {
	if m != nil {
		return m.Department
	}
	return nil
}

type RecruitmentFormField struct {
	ID                   string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Subject              string          `protobuf:"bytes,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Kind                 string          `protobuf:"bytes,3,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Options              *_struct.Struct `protobuf:"bytes,4,opt,name=Options,proto3" json:"Options,omitempty"`
	Key                  string          `protobuf:"bytes,5,opt,name=Key,proto3" json:"Key,omitempty"`
	Sort                 int32           `protobuf:"varint,7,opt,name=Sort,proto3" json:"Sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecruitmentFormField) Reset()         { *m = RecruitmentFormField{} }
func (m *RecruitmentFormField) String() string { return proto.CompactTextString(m) }
func (*RecruitmentFormField) ProtoMessage()    {}
func (*RecruitmentFormField) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{11}
}
func (m *RecruitmentFormField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentFormField.Unmarshal(m, b)
}
func (m *RecruitmentFormField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentFormField.Marshal(b, m, deterministic)
}
func (dst *RecruitmentFormField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentFormField.Merge(dst, src)
}
func (m *RecruitmentFormField) XXX_Size() int {
	return xxx_messageInfo_RecruitmentFormField.Size(m)
}
func (m *RecruitmentFormField) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentFormField.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentFormField proto.InternalMessageInfo

func (m *RecruitmentFormField) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecruitmentFormField) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *RecruitmentFormField) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *RecruitmentFormField) GetOptions() *_struct.Struct {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *RecruitmentFormField) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RecruitmentFormField) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type RecruitmentRecord struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ClubID               string               `protobuf:"bytes,4,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	CreateUserID         string               `protobuf:"bytes,5,opt,name=CreateUserID,proto3" json:"CreateUserID,omitempty"`
	Form                 *RecruitmentForm     `protobuf:"bytes,6,opt,name=Form,proto3" json:"Form,omitempty"`
	HasStart             bool                 `protobuf:"varint,7,opt,name=HasStart,proto3" json:"HasStart,omitempty"`
	HasEnd               bool                 `protobuf:"varint,8,opt,name=HasEnd,proto3" json:"HasEnd,omitempty"`
	HasUploadForm        bool                 `protobuf:"varint,9,opt,name=HasUploadForm,proto3" json:"HasUploadForm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecruitmentRecord) Reset()         { *m = RecruitmentRecord{} }
func (m *RecruitmentRecord) String() string { return proto.CompactTextString(m) }
func (*RecruitmentRecord) ProtoMessage()    {}
func (*RecruitmentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{12}
}
func (m *RecruitmentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentRecord.Unmarshal(m, b)
}
func (m *RecruitmentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentRecord.Marshal(b, m, deterministic)
}
func (dst *RecruitmentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentRecord.Merge(dst, src)
}
func (m *RecruitmentRecord) XXX_Size() int {
	return xxx_messageInfo_RecruitmentRecord.Size(m)
}
func (m *RecruitmentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentRecord proto.InternalMessageInfo

func (m *RecruitmentRecord) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RecruitmentRecord) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RecruitmentRecord) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RecruitmentRecord) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

func (m *RecruitmentRecord) GetCreateUserID() string {
	if m != nil {
		return m.CreateUserID
	}
	return ""
}

func (m *RecruitmentRecord) GetForm() *RecruitmentForm {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *RecruitmentRecord) GetHasStart() bool {
	if m != nil {
		return m.HasStart
	}
	return false
}

func (m *RecruitmentRecord) GetHasEnd() bool {
	if m != nil {
		return m.HasEnd
	}
	return false
}

func (m *RecruitmentRecord) GetHasUploadForm() bool {
	if m != nil {
		return m.HasUploadForm
	}
	return false
}

type RecruitmentRecordResponse struct {
	Record               *RecruitmentRecord `protobuf:"bytes,1,opt,name=Record,proto3" json:"Record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RecruitmentRecordResponse) Reset()         { *m = RecruitmentRecordResponse{} }
func (m *RecruitmentRecordResponse) String() string { return proto.CompactTextString(m) }
func (*RecruitmentRecordResponse) ProtoMessage()    {}
func (*RecruitmentRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{13}
}
func (m *RecruitmentRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentRecordResponse.Unmarshal(m, b)
}
func (m *RecruitmentRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentRecordResponse.Marshal(b, m, deterministic)
}
func (dst *RecruitmentRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentRecordResponse.Merge(dst, src)
}
func (m *RecruitmentRecordResponse) XXX_Size() int {
	return xxx_messageInfo_RecruitmentRecordResponse.Size(m)
}
func (m *RecruitmentRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentRecordResponse proto.InternalMessageInfo

func (m *RecruitmentRecordResponse) GetRecord() *RecruitmentRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type RecruitmentRecordFromResponse struct {
	Form                 *RecruitmentForm `protobuf:"bytes,2,opt,name=Form,proto3" json:"Form,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RecruitmentRecordFromResponse) Reset()         { *m = RecruitmentRecordFromResponse{} }
func (m *RecruitmentRecordFromResponse) String() string { return proto.CompactTextString(m) }
func (*RecruitmentRecordFromResponse) ProtoMessage()    {}
func (*RecruitmentRecordFromResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{14}
}
func (m *RecruitmentRecordFromResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecruitmentRecordFromResponse.Unmarshal(m, b)
}
func (m *RecruitmentRecordFromResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecruitmentRecordFromResponse.Marshal(b, m, deterministic)
}
func (dst *RecruitmentRecordFromResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecruitmentRecordFromResponse.Merge(dst, src)
}
func (m *RecruitmentRecordFromResponse) XXX_Size() int {
	return xxx_messageInfo_RecruitmentRecordFromResponse.Size(m)
}
func (m *RecruitmentRecordFromResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecruitmentRecordFromResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecruitmentRecordFromResponse proto.InternalMessageInfo

func (m *RecruitmentRecordFromResponse) GetForm() *RecruitmentForm {
	if m != nil {
		return m.Form
	}
	return nil
}

type ByRecruitmentRecordBundle struct {
	// RecruitmentRecord Record = 1;
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// string FormID = 2;
	ClubID               string   `protobuf:"bytes,3,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByRecruitmentRecordBundle) Reset()         { *m = ByRecruitmentRecordBundle{} }
func (m *ByRecruitmentRecordBundle) String() string { return proto.CompactTextString(m) }
func (*ByRecruitmentRecordBundle) ProtoMessage()    {}
func (*ByRecruitmentRecordBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{15}
}
func (m *ByRecruitmentRecordBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByRecruitmentRecordBundle.Unmarshal(m, b)
}
func (m *ByRecruitmentRecordBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByRecruitmentRecordBundle.Marshal(b, m, deterministic)
}
func (dst *ByRecruitmentRecordBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByRecruitmentRecordBundle.Merge(dst, src)
}
func (m *ByRecruitmentRecordBundle) XXX_Size() int {
	return xxx_messageInfo_ByRecruitmentRecordBundle.Size(m)
}
func (m *ByRecruitmentRecordBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_ByRecruitmentRecordBundle.DiscardUnknown(m)
}

var xxx_messageInfo_ByRecruitmentRecordBundle proto.InternalMessageInfo

func (m *ByRecruitmentRecordBundle) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ByRecruitmentRecordBundle) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

type ByRecruitmentFormBundle struct {
	RecordForm           *RecruitmentForm `protobuf:"bytes,1,opt,name=RecordForm,proto3" json:"RecordForm,omitempty"`
	UserID               string           `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ClubID               string           `protobuf:"bytes,3,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	RecordID             string           `protobuf:"bytes,4,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ByRecruitmentFormBundle) Reset()         { *m = ByRecruitmentFormBundle{} }
func (m *ByRecruitmentFormBundle) String() string { return proto.CompactTextString(m) }
func (*ByRecruitmentFormBundle) ProtoMessage()    {}
func (*ByRecruitmentFormBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{16}
}
func (m *ByRecruitmentFormBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByRecruitmentFormBundle.Unmarshal(m, b)
}
func (m *ByRecruitmentFormBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByRecruitmentFormBundle.Marshal(b, m, deterministic)
}
func (dst *ByRecruitmentFormBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByRecruitmentFormBundle.Merge(dst, src)
}
func (m *ByRecruitmentFormBundle) XXX_Size() int {
	return xxx_messageInfo_ByRecruitmentFormBundle.Size(m)
}
func (m *ByRecruitmentFormBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_ByRecruitmentFormBundle.DiscardUnknown(m)
}

var xxx_messageInfo_ByRecruitmentFormBundle proto.InternalMessageInfo

func (m *ByRecruitmentFormBundle) GetRecordForm() *RecruitmentForm {
	if m != nil {
		return m.RecordForm
	}
	return nil
}

func (m *ByRecruitmentFormBundle) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ByRecruitmentFormBundle) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

func (m *ByRecruitmentFormBundle) GetRecordID() string {
	if m != nil {
		return m.RecordID
	}
	return ""
}

type ByRecruitmentFormID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByRecruitmentFormID) Reset()         { *m = ByRecruitmentFormID{} }
func (m *ByRecruitmentFormID) String() string { return proto.CompactTextString(m) }
func (*ByRecruitmentFormID) ProtoMessage()    {}
func (*ByRecruitmentFormID) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{17}
}
func (m *ByRecruitmentFormID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByRecruitmentFormID.Unmarshal(m, b)
}
func (m *ByRecruitmentFormID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByRecruitmentFormID.Marshal(b, m, deterministic)
}
func (dst *ByRecruitmentFormID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByRecruitmentFormID.Merge(dst, src)
}
func (m *ByRecruitmentFormID) XXX_Size() int {
	return xxx_messageInfo_ByRecruitmentFormID.Size(m)
}
func (m *ByRecruitmentFormID) XXX_DiscardUnknown() {
	xxx_messageInfo_ByRecruitmentFormID.DiscardUnknown(m)
}

var xxx_messageInfo_ByRecruitmentFormID proto.InternalMessageInfo

func (m *ByRecruitmentFormID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ByRecruitmentID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByRecruitmentID) Reset()         { *m = ByRecruitmentID{} }
func (m *ByRecruitmentID) String() string { return proto.CompactTextString(m) }
func (*ByRecruitmentID) ProtoMessage()    {}
func (*ByRecruitmentID) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{18}
}
func (m *ByRecruitmentID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByRecruitmentID.Unmarshal(m, b)
}
func (m *ByRecruitmentID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByRecruitmentID.Marshal(b, m, deterministic)
}
func (dst *ByRecruitmentID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByRecruitmentID.Merge(dst, src)
}
func (m *ByRecruitmentID) XXX_Size() int {
	return xxx_messageInfo_ByRecruitmentID.Size(m)
}
func (m *ByRecruitmentID) XXX_DiscardUnknown() {
	xxx_messageInfo_ByRecruitmentID.DiscardUnknown(m)
}

var xxx_messageInfo_ByRecruitmentID proto.InternalMessageInfo

func (m *ByRecruitmentID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ByRecruitmentFormRecord struct {
	RecordFormRecord     *RecruitmentFormRecord `protobuf:"bytes,1,opt,name=RecordFormRecord,proto3" json:"RecordFormRecord,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ByRecruitmentFormRecord) Reset()         { *m = ByRecruitmentFormRecord{} }
func (m *ByRecruitmentFormRecord) String() string { return proto.CompactTextString(m) }
func (*ByRecruitmentFormRecord) ProtoMessage()    {}
func (*ByRecruitmentFormRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_recruitment_a6e0e7ea289a85ec, []int{19}
}
func (m *ByRecruitmentFormRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByRecruitmentFormRecord.Unmarshal(m, b)
}
func (m *ByRecruitmentFormRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByRecruitmentFormRecord.Marshal(b, m, deterministic)
}
func (dst *ByRecruitmentFormRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByRecruitmentFormRecord.Merge(dst, src)
}
func (m *ByRecruitmentFormRecord) XXX_Size() int {
	return xxx_messageInfo_ByRecruitmentFormRecord.Size(m)
}
func (m *ByRecruitmentFormRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ByRecruitmentFormRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ByRecruitmentFormRecord proto.InternalMessageInfo

func (m *ByRecruitmentFormRecord) GetRecordFormRecord() *RecruitmentFormRecord {
	if m != nil {
		return m.RecordFormRecord
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatedResponse)(nil), "iunite.club.srv.core.recruitment.CreatedResponse")
	proto.RegisterType((*FindRecruitmentFormRecordRequest)(nil), "iunite.club.srv.core.recruitment.FindRecruitmentFormRecordRequest")
	proto.RegisterType((*RecruitmentFormRecordsResponse)(nil), "iunite.club.srv.core.recruitment.RecruitmentFormRecordsResponse")
	proto.RegisterType((*Response)(nil), "iunite.club.srv.core.recruitment.Response")
	proto.RegisterType((*AdjustOnePostRequest)(nil), "iunite.club.srv.core.recruitment.AdjustOnePostRequest")
	proto.RegisterType((*PassedOnePostRequest)(nil), "iunite.club.srv.core.recruitment.PassedOnePostRequest")
	proto.RegisterType((*RefusedOnePostRequest)(nil), "iunite.club.srv.core.recruitment.RefusedOnePostRequest")
	proto.RegisterType((*ByClubIDRequest)(nil), "iunite.club.srv.core.recruitment.ByClubIDRequest")
	proto.RegisterType((*RecruitmentForm)(nil), "iunite.club.srv.core.recruitment.RecruitmentForm")
	proto.RegisterType((*RecruitmentAnswer)(nil), "iunite.club.srv.core.recruitment.RecruitmentAnswer")
	proto.RegisterType((*RecruitmentFormRecord)(nil), "iunite.club.srv.core.recruitment.RecruitmentFormRecord")
	proto.RegisterType((*RecruitmentFormField)(nil), "iunite.club.srv.core.recruitment.RecruitmentFormField")
	proto.RegisterType((*RecruitmentRecord)(nil), "iunite.club.srv.core.recruitment.RecruitmentRecord")
	proto.RegisterType((*RecruitmentRecordResponse)(nil), "iunite.club.srv.core.recruitment.RecruitmentRecordResponse")
	proto.RegisterType((*RecruitmentRecordFromResponse)(nil), "iunite.club.srv.core.recruitment.RecruitmentRecordFromResponse")
	proto.RegisterType((*ByRecruitmentRecordBundle)(nil), "iunite.club.srv.core.recruitment.ByRecruitmentRecordBundle")
	proto.RegisterType((*ByRecruitmentFormBundle)(nil), "iunite.club.srv.core.recruitment.ByRecruitmentFormBundle")
	proto.RegisterType((*ByRecruitmentFormID)(nil), "iunite.club.srv.core.recruitment.ByRecruitmentFormID")
	proto.RegisterType((*ByRecruitmentID)(nil), "iunite.club.srv.core.recruitment.ByRecruitmentID")
	proto.RegisterType((*ByRecruitmentFormRecord)(nil), "iunite.club.srv.core.recruitment.ByRecruitmentFormRecord")
}

func init() {
	proto.RegisterFile("proto/recruitment/recruitment.proto", fileDescriptor_recruitment_a6e0e7ea289a85ec)
}

var fileDescriptor_recruitment_a6e0e7ea289a85ec = []byte{
	// 1170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x4b, 0x73, 0xdb, 0x54,
	0x14, 0x8e, 0x1c, 0x3f, 0xe2, 0xe3, 0x26, 0x29, 0x97, 0x90, 0xaa, 0xa2, 0x04, 0x23, 0x5e, 0xa1,
	0x0b, 0x65, 0x9a, 0x0e, 0xcf, 0x2e, 0x20, 0xa9, 0x93, 0x89, 0xeb, 0xa4, 0x49, 0xe5, 0xe6, 0x07,
	0xc8, 0xd6, 0x8d, 0xab, 0x8c, 0x2c, 0xb9, 0xba, 0x57, 0xed, 0x84, 0x19, 0xd8, 0xb0, 0x81, 0x19,
	0x66, 0x60, 0x03, 0x4b, 0xd6, 0x6c, 0xd8, 0xf3, 0x73, 0xf8, 0x11, 0xfc, 0x00, 0xe6, 0x3e, 0x64,
	0x3d, 0xa9, 0x2d, 0x67, 0xd3, 0xdd, 0x3d, 0x57, 0xe7, 0xf1, 0xdd, 0x73, 0xbe, 0x7b, 0xee, 0x11,
	0xbc, 0x3f, 0x09, 0x7c, 0xea, 0xef, 0x04, 0x78, 0x18, 0x84, 0x0e, 0x1d, 0x63, 0x8f, 0x26, 0xd7,
	0x06, 0xff, 0x8a, 0xda, 0x4e, 0xe8, 0x39, 0x14, 0x1b, 0x43, 0x37, 0x1c, 0x18, 0x24, 0x78, 0x61,
	0x0c, 0xfd, 0x00, 0x1b, 0x09, 0x3d, 0xed, 0xdd, 0x91, 0xef, 0x8f, 0x5c, 0xbc, 0xc3, 0xf5, 0x07,
	0xe1, 0xc5, 0x0e, 0x75, 0xc6, 0x98, 0x50, 0x6b, 0x3c, 0x11, 0x2e, 0xb4, 0x3b, 0x59, 0x05, 0x42,
	0x83, 0x70, 0x28, 0x03, 0x68, 0x5f, 0x25, 0x02, 0xec, 0x10, 0x1c, 0xbc, 0x70, 0x86, 0x98, 0xec,
	0xf8, 0xc1, 0xc8, 0xf2, 0x9c, 0x6f, 0x2d, 0xea, 0xf8, 0x9e, 0x30, 0x4c, 0x6d, 0x09, 0x5b, 0xdd,
	0x83, 0xf5, 0x87, 0x01, 0xb6, 0x28, 0xb6, 0x4d, 0x4c, 0x26, 0xbe, 0x47, 0x30, 0x5a, 0x83, 0xca,
	0x69, 0x4f, 0x55, 0xda, 0xca, 0xf6, 0x8a, 0x59, 0x39, 0xed, 0xa1, 0x1e, 0xd4, 0x4d, 0x3c, 0xf4,
	0x03, 0x5b, 0xad, 0xb4, 0x95, 0xed, 0xd6, 0xee, 0x7d, 0x63, 0xd6, 0x81, 0x0c, 0x33, 0x5e, 0x0b,
	0x53, 0x53, 0xba, 0xd0, 0xff, 0x50, 0xa0, 0x7d, 0xe8, 0x78, 0x76, 0x42, 0xe3, 0xd0, 0x0f, 0xc6,
	0x52, 0x0b, 0x3f, 0x0f, 0x31, 0xa1, 0x08, 0x41, 0xf5, 0xcc, 0x1a, 0x61, 0x8e, 0xa1, 0x66, 0xf2,
	0x35, 0xda, 0x80, 0xda, 0xb1, 0x33, 0x76, 0x28, 0x07, 0x51, 0x33, 0x85, 0x80, 0xb6, 0x00, 0x3a,
	0x78, 0x62, 0x05, 0xdc, 0x91, 0xba, 0xdc, 0x56, 0xb6, 0x9b, 0x66, 0x62, 0x87, 0x59, 0xf5, 0xa9,
	0x45, 0xb1, 0x5a, 0x15, 0x56, 0x5c, 0x40, 0x1a, 0xac, 0x88, 0x80, 0xdd, 0x8e, 0x5a, 0xe3, 0x36,
	0x53, 0x59, 0xff, 0x49, 0x81, 0xad, 0x42, 0x70, 0x64, 0x9a, 0xa0, 0x27, 0xd0, 0x90, 0x5b, 0xaa,
	0xd2, 0x5e, 0xde, 0x6e, 0xed, 0x7e, 0x5e, 0x2a, 0x23, 0x89, 0xf3, 0x46, 0x7e, 0x18, 0xce, 0xa7,
	0x3e, 0xb5, 0xdc, 0xe8, 0x74, 0x5c, 0xd0, 0x39, 0xce, 0xe2, 0xaa, 0xe8, 0x8f, 0x60, 0x63, 0xcf,
	0xbe, 0x0c, 0x09, 0x3d, 0xf5, 0xf0, 0x99, 0x4f, 0x68, 0x94, 0xbb, 0x35, 0xa8, 0x74, 0x3b, 0x5c,
	0xaf, 0x69, 0x56, 0xba, 0x1d, 0xa4, 0xc3, 0x8d, 0x38, 0x1f, 0xdd, 0x0e, 0x0f, 0xd0, 0x34, 0x53,
	0x7b, 0xfa, 0x47, 0xb0, 0x71, 0x66, 0x11, 0x82, 0xed, 0x57, 0xfb, 0xd2, 0x3f, 0x86, 0xb7, 0x4c,
	0x7c, 0x11, 0xce, 0x56, 0xfc, 0x04, 0xd6, 0xf7, 0xaf, 0x1e, 0xba, 0xe1, 0xa0, 0xdb, 0x89, 0x54,
	0x36, 0xa1, 0x2e, 0x36, 0xa4, 0x9a, 0x94, 0xf4, 0xdf, 0x2a, 0xb0, 0x9e, 0x49, 0x4e, 0xee, 0x0c,
	0x5f, 0x40, 0x53, 0x92, 0x74, 0x8f, 0x4a, 0x12, 0x6a, 0x86, 0xb8, 0x12, 0x46, 0x74, 0x25, 0x8c,
	0xa7, 0xd1, 0x9d, 0x31, 0x63, 0x65, 0x66, 0x79, 0x3e, 0xb1, 0xa5, 0xe5, 0xf2, 0x6c, 0xcb, 0xa9,
	0x32, 0xe3, 0xe0, 0x63, 0x6b, 0x2c, 0x88, 0xd3, 0x34, 0xf9, 0xfa, 0x55, 0xbc, 0x41, 0x8f, 0xa1,
	0x7e, 0xe8, 0x60, 0xd7, 0x26, 0x6a, 0x9d, 0x73, 0xe2, 0xb3, 0xd2, 0x9c, 0xe0, 0xe6, 0xa6, 0xf4,
	0xa2, 0x8f, 0xe1, 0x8d, 0xc4, 0xf7, 0x3d, 0x8f, 0xbc, 0xc4, 0x41, 0x2e, 0x31, 0x9b, 0x50, 0x67,
	0x96, 0xd3, 0xb2, 0x4a, 0x09, 0xa9, 0xd0, 0xe8, 0x52, 0x3c, 0xee, 0xe1, 0x2b, 0x79, 0x27, 0x22,
	0x91, 0x59, 0x08, 0x5f, 0xf2, 0x60, 0x52, 0xd2, 0x7f, 0xae, 0xb2, 0xda, 0x16, 0x70, 0xf4, 0xb5,
	0x28, 0xc6, 0x26, 0xd4, 0x4f, 0xfc, 0x81, 0xe3, 0x46, 0xe5, 0x90, 0xd2, 0xb4, 0x48, 0xb5, 0x44,
	0x91, 0x36, 0xa0, 0x76, 0x62, 0x5d, 0xfa, 0x81, 0x5a, 0xe7, 0x9b, 0x42, 0x40, 0x37, 0x61, 0x79,
	0x6f, 0x84, 0xd5, 0x06, 0xbf, 0x5e, 0x6c, 0x89, 0xb6, 0x61, 0xbd, 0x3f, 0x7c, 0xe6, 0xfb, 0x6e,
	0x9f, 0x86, 0xb6, 0xb8, 0x1b, 0x2b, 0xdc, 0x22, 0xbb, 0x9d, 0xbb, 0x42, 0xcd, 0xfc, 0x15, 0x4a,
	0x51, 0x03, 0x32, 0xd4, 0xd8, 0x84, 0x3a, 0xeb, 0x3b, 0x21, 0x51, 0x5b, 0x3c, 0xbc, 0x94, 0xd0,
	0x09, 0x34, 0x44, 0xf6, 0x89, 0x7a, 0x83, 0x73, 0xa6, 0x5c, 0x67, 0x15, 0xb6, 0x66, 0xe4, 0x03,
	0x3d, 0x4a, 0xf5, 0xc2, 0x55, 0x9e, 0xdf, 0xbb, 0x39, 0x8f, 0xa9, 0x37, 0xe0, 0x34, 0x21, 0x24,
	0xfb, 0xa6, 0xfe, 0x97, 0x02, 0x1b, 0x45, 0xf4, 0xcc, 0xb1, 0x41, 0x85, 0x46, 0x3f, 0x1c, 0x5c,
	0xe2, 0x21, 0x95, 0x14, 0x8c, 0x44, 0x56, 0x9b, 0x9e, 0xe3, 0xd9, 0x92, 0x80, 0x7c, 0x8d, 0xee,
	0x41, 0xe3, 0x74, 0xc2, 0x82, 0x11, 0x5e, 0xc8, 0xd6, 0xee, 0xad, 0x5c, 0xfd, 0xfb, 0xfc, 0x65,
	0x33, 0x23, 0x3d, 0x56, 0x38, 0x46, 0x63, 0x51, 0x61, 0xb6, 0x64, 0x8e, 0xfb, 0x7e, 0x40, 0x65,
	0x2d, 0xf9, 0x5a, 0xff, 0xb7, 0x92, 0xba, 0x2e, 0xaf, 0x17, 0x75, 0x65, 0xdf, 0xab, 0x26, 0xfb,
	0x1e, 0x23, 0x95, 0x70, 0x7f, 0x4e, 0x70, 0x30, 0xed, 0x27, 0xa9, 0x3d, 0x74, 0x00, 0x55, 0x96,
	0x79, 0xce, 0xe4, 0xd6, 0xee, 0xbd, 0xf2, 0xaf, 0x0c, 0x37, 0x67, 0xdc, 0x3c, 0xb2, 0x48, 0x9f,
	0x5a, 0x32, 0x69, 0x2b, 0xe6, 0x54, 0x66, 0xf0, 0x8e, 0x2c, 0x72, 0xe0, 0xd9, 0x9c, 0xfc, 0x2b,
	0xa6, 0x94, 0xd0, 0x07, 0xb0, 0x7a, 0x64, 0x91, 0xf3, 0x89, 0xeb, 0x5b, 0x36, 0xc7, 0xd0, 0xe4,
	0x9f, 0xd3, 0x9b, 0xfa, 0x33, 0xb8, 0x9d, 0x7f, 0xea, 0xa3, 0x17, 0x2b, 0x9e, 0x1b, 0x94, 0xeb,
	0xcf, 0x0d, 0x17, 0xf0, 0x4e, 0xee, 0xe3, 0x61, 0xe0, 0x8f, 0xa7, 0xd1, 0xa2, 0x5c, 0x55, 0xae,
	0x95, 0x2b, 0xbd, 0x07, 0xb7, 0xf7, 0xaf, 0x72, 0x91, 0xf6, 0x43, 0xcf, 0x76, 0x31, 0x4b, 0x96,
	0xac, 0x96, 0x7c, 0xc3, 0x64, 0x9d, 0xe2, 0x1a, 0x2f, 0xa7, 0xde, 0xb6, 0xbf, 0x15, 0xb8, 0x95,
	0xf2, 0xc6, 0x42, 0x48, 0x5f, 0x4f, 0x00, 0xe4, 0x29, 0x18, 0x6a, 0x65, 0x51, 0xd4, 0x09, 0x27,
	0x09, 0x78, 0x95, 0x79, 0xe0, 0xa5, 0x7a, 0x56, 0x35, 0x33, 0x06, 0x7d, 0x08, 0x6f, 0xe6, 0x90,
	0x77, 0x3b, 0xb9, 0x87, 0xfe, 0x3d, 0xf6, 0xd0, 0x27, 0xd4, 0x0a, 0x54, 0xbe, 0x2f, 0xc8, 0x81,
	0xbc, 0x9f, 0x43, 0xb8, 0x19, 0xc3, 0x4f, 0x71, 0x65, 0xe1, 0x89, 0x2a, 0xe7, 0x70, 0xf7, 0x9f,
	0x16, 0xb4, 0x12, 0xba, 0x28, 0x84, 0xd5, 0xd4, 0xe0, 0x84, 0xe6, 0x78, 0xa9, 0x8b, 0x26, 0x2d,
	0xed, 0xee, 0x3c, 0x18, 0x05, 0x3b, 0xf5, 0x25, 0x16, 0x36, 0x35, 0x63, 0xcd, 0x13, 0xb6, 0x68,
	0x28, 0x2b, 0x19, 0xf6, 0x25, 0xac, 0xa5, 0x47, 0x36, 0x34, 0x57, 0x6a, 0x0b, 0x86, 0xbc, 0x92,
	0x81, 0x7f, 0x51, 0xe0, 0x6d, 0x36, 0xe8, 0x1f, 0x5b, 0x14, 0x33, 0x1f, 0xd9, 0xde, 0x3c, 0x07,
	0xd7, 0x33, 0x23, 0xa4, 0xf6, 0x60, 0x91, 0x06, 0x12, 0x23, 0xfa, 0x51, 0x61, 0x23, 0xb3, 0x9d,
	0x87, 0xf2, 0x60, 0x1e, 0x28, 0xff, 0xd3, 0x13, 0xb4, 0x39, 0xce, 0x91, 0xf9, 0xc1, 0xd2, 0x97,
	0xd0, 0x77, 0x80, 0xd2, 0x48, 0xf8, 0xfd, 0xfd, 0xb2, 0x24, 0x8e, 0xb8, 0x9b, 0x94, 0xac, 0xcd,
	0xef, 0x0a, 0x68, 0x05, 0x3f, 0x61, 0x1d, 0x4c, 0x2d, 0xc7, 0x25, 0xe8, 0xd3, 0x05, 0x70, 0x74,
	0x3b, 0xda, 0xd7, 0x0b, 0x94, 0x27, 0xd9, 0xc2, 0xf5, 0x25, 0xf4, 0x83, 0x02, 0x6a, 0x3e, 0x31,
	0xb2, 0x4c, 0x8b, 0xa4, 0x47, 0x98, 0x96, 0x4c, 0xcf, 0x73, 0x58, 0x3b, 0x48, 0x25, 0x67, 0x3e,
	0xb2, 0xa6, 0xda, 0x60, 0xc9, 0x90, 0xbf, 0x2a, 0x70, 0x27, 0x53, 0x11, 0x01, 0x3d, 0xaa, 0xc9,
	0x02, 0x08, 0xae, 0x79, 0x5d, 0xfe, 0x54, 0x60, 0x2b, 0x03, 0x89, 0xc4, 0x29, 0x3d, 0x76, 0x08,
	0x45, 0xfb, 0xb3, 0x23, 0xcc, 0xfa, 0xd7, 0xd7, 0xbe, 0x59, 0xb0, 0xd3, 0x93, 0x18, 0xea, 0xa0,
	0xce, 0x47, 0xb0, 0xfb, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x19, 0xec, 0x3e, 0x90, 0x8f, 0x11,
	0x00, 0x00,
}
