// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package iunite_club_srv_user

/*
import "google/protobuf/timestamp.proto";
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindUsersByClubIDRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	ClubID               string   `protobuf:"bytes,3,opt,name=ClubID,proto3" json:"ClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindUsersByClubIDRequest) Reset()         { *m = FindUsersByClubIDRequest{} }
func (m *FindUsersByClubIDRequest) String() string { return proto.CompactTextString(m) }
func (*FindUsersByClubIDRequest) ProtoMessage()    {}
func (*FindUsersByClubIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{0}
}
func (m *FindUsersByClubIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUsersByClubIDRequest.Unmarshal(m, b)
}
func (m *FindUsersByClubIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUsersByClubIDRequest.Marshal(b, m, deterministic)
}
func (dst *FindUsersByClubIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUsersByClubIDRequest.Merge(dst, src)
}
func (m *FindUsersByClubIDRequest) XXX_Size() int {
	return xxx_messageInfo_FindUsersByClubIDRequest.Size(m)
}
func (m *FindUsersByClubIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUsersByClubIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUsersByClubIDRequest proto.InternalMessageInfo

func (m *FindUsersByClubIDRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindUsersByClubIDRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *FindUsersByClubIDRequest) GetClubID() string {
	if m != nil {
		return m.ClubID
	}
	return ""
}

type ResetPasswordResponse struct {
	UpdatedAt            string   `protobuf:"bytes,1,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{1}
}
func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(dst, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

func (m *ResetPasswordResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ResetPasswordResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type User struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	SchoolID             string   `protobuf:"bytes,4,opt,name=SchoolID,proto3" json:"SchoolID,omitempty"`
	Profile              *Profile `protobuf:"bytes,5,opt,name=Profile,proto3" json:"Profile,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Deleted              bool     `protobuf:"varint,8,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	Password             string   `protobuf:"bytes,9,opt,name=Password,proto3" json:"Password,omitempty"`
	DefaultClubID        string   `protobuf:"bytes,10,opt,name=DefaultClubID,proto3" json:"DefaultClubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *User) GetSchoolID() string {
	if m != nil {
		return m.SchoolID
	}
	return ""
}

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetDefaultClubID() string {
	if m != nil {
		return m.DefaultClubID
	}
	return ""
}

type Profile struct {
	ID                   string   `protobuf:"bytes,11,opt,name=ID,proto3" json:"ID,omitempty"`
	Avatar               string   `protobuf:"bytes,1,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Birthday             string   `protobuf:"bytes,5,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Nickname             string   `protobuf:"bytes,6,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	UserID               string   `protobuf:"bytes,7,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{3}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Profile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Profile) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Profile) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Profile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Profile) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Profile) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Profile) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Profile) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ResetPasswordRequest struct {
	Mobile string `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	// string MobileAreaCode = 2;
	// string Code = 3;
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	UserID               string   `protobuf:"bytes,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{4}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *ResetPasswordRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SigninByMobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninByMobileRequest) Reset()         { *m = SigninByMobileRequest{} }
func (m *SigninByMobileRequest) String() string { return proto.CompactTextString(m) }
func (*SigninByMobileRequest) ProtoMessage()    {}
func (*SigninByMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{5}
}
func (m *SigninByMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninByMobileRequest.Unmarshal(m, b)
}
func (m *SigninByMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninByMobileRequest.Marshal(b, m, deterministic)
}
func (dst *SigninByMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninByMobileRequest.Merge(dst, src)
}
func (m *SigninByMobileRequest) XXX_Size() int {
	return xxx_messageInfo_SigninByMobileRequest.Size(m)
}
func (m *SigninByMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninByMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SigninByMobileRequest proto.InternalMessageInfo

func (m *SigninByMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SigninByMobileRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserRequest struct {
	SchoolID             string   `protobuf:"bytes,1,opt,name=SchoolID,proto3" json:"SchoolID,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Firstname            string   `protobuf:"bytes,4,opt,name=Firstname,proto3" json:"Firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,5,opt,name=Lastname,proto3" json:"Lastname,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=Password,proto3" json:"Password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,7,opt,name=ConfirmPassword,proto3" json:"ConfirmPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{6}
}
func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(dst, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetSchoolID() string {
	if m != nil {
		return m.SchoolID
	}
	return ""
}

func (m *RegisterUserRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterUserRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RegisterUserRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterUserRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterUserRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type RegisterUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	OK                   bool     `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{7}
}
func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(dst, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

func (m *RegisterUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterUserResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type Response struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{8}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type UserListResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{9}
}
func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (dst *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(dst, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UserListResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserListResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UserListResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PagerRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagerRequest) Reset()         { *m = PagerRequest{} }
func (m *PagerRequest) String() string { return proto.CompactTextString(m) }
func (*PagerRequest) ProtoMessage()    {}
func (*PagerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{10}
}
func (m *PagerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagerRequest.Unmarshal(m, b)
}
func (m *PagerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagerRequest.Marshal(b, m, deterministic)
}
func (dst *PagerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagerRequest.Merge(dst, src)
}
func (m *PagerRequest) XXX_Size() int {
	return xxx_messageInfo_PagerRequest.Size(m)
}
func (m *PagerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PagerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PagerRequest proto.InternalMessageInfo

func (m *PagerRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PagerRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UpdateUserRequest struct {
	// User userInfo = 1;
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	User                 []byte   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Profile              []byte   `protobuf:"bytes,3,opt,name=Profile,proto3" json:"Profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{11}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateUserRequest) GetUser() []byte {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetProfile() []byte {
	if m != nil {
		return m.Profile
	}
	return nil
}

type QueryUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserRequest) Reset()         { *m = QueryUserRequest{} }
func (m *QueryUserRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserRequest) ProtoMessage()    {}
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{12}
}
func (m *QueryUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserRequest.Unmarshal(m, b)
}
func (m *QueryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserRequest.Marshal(b, m, deterministic)
}
func (dst *QueryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserRequest.Merge(dst, src)
}
func (m *QueryUserRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserRequest.Size(m)
}
func (m *QueryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserRequest proto.InternalMessageInfo

func (m *QueryUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{13}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type QueryProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryProfileRequest) Reset()         { *m = QueryProfileRequest{} }
func (m *QueryProfileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProfileRequest) ProtoMessage()    {}
func (*QueryProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{14}
}
func (m *QueryProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProfileRequest.Unmarshal(m, b)
}
func (m *QueryProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProfileRequest.Marshal(b, m, deterministic)
}
func (dst *QueryProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProfileRequest.Merge(dst, src)
}
func (m *QueryProfileRequest) XXX_Size() int {
	return xxx_messageInfo_QueryProfileRequest.Size(m)
}
func (m *QueryProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProfileRequest proto.InternalMessageInfo

func (m *QueryProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfileResponse struct {
	Profile              *Profile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_f3766a6c99d4d7c2, []int{15}
}
func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (dst *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(dst, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*FindUsersByClubIDRequest)(nil), "iunite.club.srv.user.FindUsersByClubIDRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "iunite.club.srv.user.ResetPasswordResponse")
	proto.RegisterType((*User)(nil), "iunite.club.srv.user.User")
	proto.RegisterType((*Profile)(nil), "iunite.club.srv.user.Profile")
	proto.RegisterType((*ResetPasswordRequest)(nil), "iunite.club.srv.user.ResetPasswordRequest")
	proto.RegisterType((*SigninByMobileRequest)(nil), "iunite.club.srv.user.SigninByMobileRequest")
	proto.RegisterType((*RegisterUserRequest)(nil), "iunite.club.srv.user.RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "iunite.club.srv.user.RegisterUserResponse")
	proto.RegisterType((*Response)(nil), "iunite.club.srv.user.Response")
	proto.RegisterType((*UserListResponse)(nil), "iunite.club.srv.user.UserListResponse")
	proto.RegisterType((*PagerRequest)(nil), "iunite.club.srv.user.PagerRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "iunite.club.srv.user.UpdateUserRequest")
	proto.RegisterType((*QueryUserRequest)(nil), "iunite.club.srv.user.QueryUserRequest")
	proto.RegisterType((*UserResponse)(nil), "iunite.club.srv.user.UserResponse")
	proto.RegisterType((*QueryProfileRequest)(nil), "iunite.club.srv.user.QueryProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "iunite.club.srv.user.ProfileResponse")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_user_f3766a6c99d4d7c2) }

var fileDescriptor_user_f3766a6c99d4d7c2 = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0xc7, 0xbe, 0x3f, 0xbe, 0x9b, 0xa4, 0x4d, 0xba, 0x4d, 0x2b, 0xcb, 0x02, 0x74, 0x5a, 0xd1,
	0x72, 0x80, 0x64, 0x50, 0x78, 0x28, 0x4f, 0x48, 0xbd, 0x73, 0x8b, 0xae, 0x09, 0x34, 0x75, 0x54,
	0x10, 0x52, 0x5f, 0x7c, 0xe7, 0x4d, 0xba, 0xc2, 0x67, 0x1f, 0x6b, 0x3b, 0xe8, 0xde, 0x79, 0xe4,
	0x7b, 0xf0, 0x19, 0xf8, 0x30, 0xbc, 0xf0, 0x49, 0xd0, 0xfe, 0xf1, 0x9e, 0xed, 0xd8, 0x17, 0x4b,
	0x7d, 0xdb, 0x99, 0x9d, 0xfd, 0xcd, 0xcc, 0x6f, 0x66, 0x67, 0x17, 0x8e, 0x37, 0x2c, 0xc9, 0x92,
	0xaf, 0xf3, 0x94, 0x30, 0x57, 0x2c, 0xd1, 0x09, 0xcd, 0x63, 0x9a, 0x11, 0x77, 0x15, 0xe5, 0x4b,
	0x37, 0x65, 0x37, 0x2e, 0xdf, 0xc3, 0xef, 0xc0, 0x7e, 0x49, 0xe3, 0xf0, 0x6d, 0x4a, 0x58, 0x3a,
	0xdb, 0xce, 0xa3, 0x7c, 0xb9, 0xf0, 0x7c, 0xf2, 0x7b, 0x4e, 0xd2, 0x0c, 0x21, 0xe8, 0x5f, 0x04,
	0xd7, 0xc4, 0x36, 0x26, 0xc6, 0xb4, 0xe7, 0x8b, 0x35, 0x3a, 0x81, 0xc1, 0x39, 0x5d, 0xd3, 0xcc,
	0x36, 0x85, 0x52, 0x0a, 0xe8, 0x31, 0x0c, 0xe5, 0x51, 0xbb, 0x37, 0x31, 0xa6, 0x63, 0x5f, 0x49,
	0xf8, 0x05, 0x3c, 0xf2, 0x49, 0x4a, 0xb2, 0x8b, 0x20, 0x4d, 0xff, 0x48, 0x58, 0xe8, 0x93, 0x74,
	0x93, 0xc4, 0x29, 0x41, 0x1f, 0xc3, 0xf8, 0xed, 0x26, 0x0c, 0x32, 0x12, 0x3e, 0xcf, 0x04, 0xfe,
	0xd8, 0xdf, 0x29, 0xd0, 0x7d, 0x30, 0x17, 0x9e, 0xf0, 0x30, 0xf6, 0xcd, 0x85, 0x87, 0xff, 0x31,
	0xa1, 0xcf, 0x23, 0x54, 0x1b, 0x46, 0xb1, 0x81, 0x1c, 0x18, 0x71, 0x7d, 0x1c, 0xac, 0x89, 0x32,
	0xd7, 0x32, 0xb2, 0xc1, 0x7a, 0x11, 0x07, 0xcb, 0x88, 0x84, 0x22, 0xa8, 0x91, 0x5f, 0x88, 0xfc,
	0xd4, 0xe5, 0xea, 0x7d, 0x92, 0x44, 0x0b, 0xcf, 0xee, 0xcb, 0x53, 0x85, 0x8c, 0x9e, 0x81, 0x75,
	0xc1, 0x92, 0x2b, 0x1a, 0x11, 0x7b, 0x30, 0x31, 0xa6, 0x07, 0xa7, 0x9f, 0xb8, 0x4d, 0xbc, 0xb9,
	0xca, 0xc8, 0x2f, 0xac, 0x79, 0x46, 0x73, 0x46, 0x54, 0x46, 0x43, 0x99, 0x91, 0x56, 0x54, 0xf3,
	0xb5, 0xea, 0xf9, 0xda, 0x60, 0x79, 0x24, 0x22, 0x19, 0x09, 0xed, 0x91, 0x0c, 0x55, 0x89, 0x3c,
	0xd4, 0x82, 0x3b, 0x7b, 0x2c, 0x43, 0x2d, 0x64, 0xf4, 0x19, 0xdc, 0xf3, 0xc8, 0x55, 0x90, 0x47,
	0x99, 0xe2, 0x1e, 0x84, 0x41, 0x55, 0x89, 0xff, 0x36, 0x75, 0x46, 0x8a, 0xbe, 0x03, 0x4d, 0xdf,
	0x63, 0x18, 0x3e, 0xbf, 0x09, 0xb2, 0x80, 0x29, 0x4a, 0x95, 0xc4, 0xa3, 0x7d, 0x49, 0x59, 0x9a,
	0x95, 0x78, 0xdd, 0x29, 0x78, 0x4c, 0xe7, 0x81, 0xda, 0x94, 0xe5, 0xd6, 0x32, 0x47, 0xfc, 0x81,
	0xc4, 0x21, 0x61, 0x8a, 0x58, 0x25, 0xf1, 0x33, 0x33, 0xca, 0xb2, 0xf7, 0x61, 0xb0, 0x15, 0xbc,
	0x8e, 0x7d, 0x2d, 0xf3, 0xbd, 0x9f, 0xe8, 0xea, 0x37, 0x81, 0x27, 0x89, 0xd3, 0x32, 0xc7, 0xe3,
	0x05, 0x5d, 0x78, 0x8a, 0x34, 0x25, 0x71, 0xfd, 0x8f, 0xc9, 0x92, 0x57, 0x69, 0x24, 0xf5, 0x52,
	0xaa, 0x56, 0x61, 0xbc, 0xb7, 0x0a, 0x50, 0xab, 0x02, 0xfe, 0xcb, 0x80, 0x93, 0x5a, 0xb7, 0xca,
	0x7b, 0xb0, 0x73, 0x66, 0x54, 0x9c, 0x95, 0x8b, 0x63, 0xd6, 0x8a, 0x33, 0x85, 0xa3, 0x79, 0x12,
	0x5f, 0x51, 0xb6, 0xd6, 0x26, 0x92, 0xab, 0xba, 0xba, 0x94, 0x62, 0xbf, 0x9c, 0x22, 0x3e, 0x83,
	0x47, 0x97, 0xf4, 0x3a, 0xa6, 0xf1, 0x6c, 0x2b, 0xfd, 0x7d, 0x40, 0x38, 0xf8, 0x5f, 0x03, 0x1e,
	0xfa, 0xe4, 0x9a, 0xa6, 0x19, 0x61, 0x1c, 0xbf, 0xc0, 0x2a, 0x5f, 0x05, 0xa3, 0x76, 0x15, 0x76,
	0x7e, 0xcc, 0x8a, 0x1f, 0x04, 0xfd, 0x79, 0x12, 0x16, 0xb5, 0x17, 0xeb, 0x6a, 0xc7, 0xf4, 0xf7,
	0x75, 0xcc, 0xa0, 0xd6, 0x31, 0xe5, 0xa8, 0x87, 0x77, 0x93, 0x68, 0x35, 0x92, 0x88, 0x7f, 0xe6,
	0xa5, 0x2b, 0xa7, 0xa7, 0xe6, 0x8c, 0x2b, 0x07, 0x87, 0xc8, 0xed, 0xe0, 0xd4, 0x69, 0xbe, 0xcb,
	0xe2, 0x84, 0x1e, 0x30, 0xaf, 0xcf, 0x44, 0xbe, 0x23, 0xdf, 0x7c, 0x7d, 0x86, 0x1d, 0x18, 0x69,
	0x2c, 0xb9, 0x67, 0xe8, 0xbd, 0x3f, 0x0d, 0x38, 0xe6, 0x87, 0xce, 0x69, 0x9a, 0x69, 0xa3, 0x6f,
	0x60, 0xc0, 0x31, 0x53, 0xdb, 0x98, 0xf4, 0xee, 0xf0, 0x28, 0x0d, 0x39, 0x9d, 0x1b, 0x3e, 0x65,
	0xb9, 0xd3, 0x81, 0x2f, 0xd6, 0x7c, 0xca, 0x46, 0x62, 0xca, 0xf6, 0x84, 0x52, 0x0a, 0x5c, 0xbb,
	0x4a, 0xf2, 0x38, 0x13, 0x04, 0x0f, 0x7c, 0x29, 0xe0, 0xef, 0xe0, 0x90, 0x4f, 0x66, 0x56, 0x9a,
	0xda, 0x9b, 0x62, 0x6a, 0xdf, 0xc2, 0x33, 0x4b, 0x78, 0xf8, 0x0d, 0x3c, 0x90, 0xdd, 0x5f, 0xee,
	0x88, 0xfa, 0x88, 0x45, 0x8a, 0x41, 0x7e, 0xf2, 0x50, 0xb1, 0x64, 0xef, 0x86, 0x64, 0x4f, 0xa8,
	0x0b, 0x11, 0x63, 0x38, 0x7e, 0x93, 0x13, 0xb6, 0xad, 0x21, 0xd2, 0xb0, 0x40, 0xa4, 0x21, 0xfe,
	0x1e, 0x0e, 0xeb, 0x35, 0xca, 0x3b, 0xd6, 0x48, 0x3c, 0x59, 0x4f, 0xe0, 0xa1, 0xf0, 0x51, 0x8c,
	0xe0, 0x16, 0x37, 0xaf, 0xe0, 0x48, 0x5b, 0x28, 0x4f, 0xcf, 0xc0, 0xda, 0xa8, 0xb8, 0x8d, 0x4e,
	0xc3, 0x5d, 0x59, 0x9f, 0xfe, 0x67, 0x81, 0xc5, 0x23, 0xb8, 0x64, 0x37, 0xe8, 0x1d, 0x1c, 0x16,
	0x2f, 0xe6, 0x6c, 0xbb, 0xf0, 0xd0, 0xd3, 0x66, 0x8c, 0x3a, 0x0d, 0x0e, 0xde, 0x93, 0x98, 0x0a,
	0x10, 0x7f, 0x84, 0x08, 0x1c, 0x71, 0x74, 0x15, 0x81, 0x70, 0xf0, 0xc5, 0x1e, 0x07, 0x55, 0x0e,
	0x9c, 0x27, 0xfb, 0xf3, 0xd9, 0xb9, 0x79, 0x05, 0x20, 0xc7, 0xa2, 0xa8, 0xe7, 0x1e, 0xce, 0x9d,
	0x4f, 0x9b, 0xf7, 0x4a, 0x58, 0xbf, 0x00, 0xec, 0xda, 0x08, 0x7d, 0xde, 0x82, 0x55, 0x6f, 0xb4,
	0x0e, 0xc0, 0xbf, 0xf2, 0xa1, 0xa2, 0xfe, 0x26, 0xa8, 0x85, 0xbe, 0x72, 0xeb, 0x3b, 0x4f, 0xdb,
	0xf3, 0x28, 0x5f, 0x52, 0x01, 0x7d, 0x6f, 0x91, 0x72, 0x7d, 0xf1, 0x27, 0xe8, 0x5a, 0xc5, 0xbb,
	0xa3, 0x4e, 0xaa, 0xa3, 0xa8, 0x98, 0xde, 0x6d, 0x65, 0x6c, 0x98, 0xca, 0xce, 0x97, 0x5d, 0x4c,
	0xb5, 0x43, 0x56, 0xfb, 0x64, 0x69, 0x8f, 0xad, 0x30, 0xb7, 0xdf, 0x38, 0xe7, 0xab, 0x4e, 0xb6,
	0xda, 0xe7, 0x0a, 0xee, 0x57, 0x1f, 0x27, 0xd4, 0x02, 0xd0, 0xf8, 0x84, 0x75, 0xbc, 0x0b, 0x6b,
	0x78, 0x70, 0xeb, 0x6f, 0x8a, 0xdc, 0xe6, 0xa3, 0x6d, 0x9f, 0xd8, 0xee, 0x3d, 0xb1, 0x1c, 0x8a,
	0x7f, 0xf2, 0xb7, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x34, 0x46, 0xfb, 0x52, 0x3b, 0x0b, 0x00,
	0x00,
}
