// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/conversation/conversation.proto

package iunite_club_srv_core_conversation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import proto1 "iunite.club/services/user/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WithIDAndMembers struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Members              []string `protobuf:"bytes,2,rep,name=Members,proto3" json:"Members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithIDAndMembers) Reset()         { *m = WithIDAndMembers{} }
func (m *WithIDAndMembers) String() string { return proto.CompactTextString(m) }
func (*WithIDAndMembers) ProtoMessage()    {}
func (*WithIDAndMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{0}
}
func (m *WithIDAndMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithIDAndMembers.Unmarshal(m, b)
}
func (m *WithIDAndMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithIDAndMembers.Marshal(b, m, deterministic)
}
func (dst *WithIDAndMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithIDAndMembers.Merge(dst, src)
}
func (m *WithIDAndMembers) XXX_Size() int {
	return xxx_messageInfo_WithIDAndMembers.Size(m)
}
func (m *WithIDAndMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_WithIDAndMembers.DiscardUnknown(m)
}

var xxx_messageInfo_WithIDAndMembers proto.InternalMessageInfo

func (m *WithIDAndMembers) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *WithIDAndMembers) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type WithIDAndUserID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithIDAndUserID) Reset()         { *m = WithIDAndUserID{} }
func (m *WithIDAndUserID) String() string { return proto.CompactTextString(m) }
func (*WithIDAndUserID) ProtoMessage()    {}
func (*WithIDAndUserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{1}
}
func (m *WithIDAndUserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithIDAndUserID.Unmarshal(m, b)
}
func (m *WithIDAndUserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithIDAndUserID.Marshal(b, m, deterministic)
}
func (dst *WithIDAndUserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithIDAndUserID.Merge(dst, src)
}
func (m *WithIDAndUserID) XXX_Size() int {
	return xxx_messageInfo_WithIDAndUserID.Size(m)
}
func (m *WithIDAndUserID) XXX_DiscardUnknown() {
	xxx_messageInfo_WithIDAndUserID.DiscardUnknown(m)
}

var xxx_messageInfo_WithIDAndUserID proto.InternalMessageInfo

func (m *WithIDAndUserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *WithIDAndUserID) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type WithID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithID) Reset()         { *m = WithID{} }
func (m *WithID) String() string { return proto.CompactTextString(m) }
func (*WithID) ProtoMessage()    {}
func (*WithID) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{2}
}
func (m *WithID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithID.Unmarshal(m, b)
}
func (m *WithID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithID.Marshal(b, m, deterministic)
}
func (dst *WithID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithID.Merge(dst, src)
}
func (m *WithID) XXX_Size() int {
	return xxx_messageInfo_WithID.Size(m)
}
func (m *WithID) XXX_DiscardUnknown() {
	xxx_messageInfo_WithID.DiscardUnknown(m)
}

var xxx_messageInfo_WithID proto.InternalMessageInfo

func (m *WithID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UpdatedOK struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatedOK) Reset()         { *m = UpdatedOK{} }
func (m *UpdatedOK) String() string { return proto.CompactTextString(m) }
func (*UpdatedOK) ProtoMessage()    {}
func (*UpdatedOK) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{3}
}
func (m *UpdatedOK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedOK.Unmarshal(m, b)
}
func (m *UpdatedOK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedOK.Marshal(b, m, deterministic)
}
func (dst *UpdatedOK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedOK.Merge(dst, src)
}
func (m *UpdatedOK) XXX_Size() int {
	return xxx_messageInfo_UpdatedOK.Size(m)
}
func (m *UpdatedOK) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedOK.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedOK proto.InternalMessageInfo

func (m *UpdatedOK) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type WithMarkedBundle struct {
	NoticeID             string   `protobuf:"bytes,1,opt,name=NoticeID,proto3" json:"NoticeID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithMarkedBundle) Reset()         { *m = WithMarkedBundle{} }
func (m *WithMarkedBundle) String() string { return proto.CompactTextString(m) }
func (*WithMarkedBundle) ProtoMessage()    {}
func (*WithMarkedBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{4}
}
func (m *WithMarkedBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithMarkedBundle.Unmarshal(m, b)
}
func (m *WithMarkedBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithMarkedBundle.Marshal(b, m, deterministic)
}
func (dst *WithMarkedBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithMarkedBundle.Merge(dst, src)
}
func (m *WithMarkedBundle) XXX_Size() int {
	return xxx_messageInfo_WithMarkedBundle.Size(m)
}
func (m *WithMarkedBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_WithMarkedBundle.DiscardUnknown(m)
}

var xxx_messageInfo_WithMarkedBundle proto.InternalMessageInfo

func (m *WithMarkedBundle) GetNoticeID() string {
	if m != nil {
		return m.NoticeID
	}
	return ""
}

func (m *WithMarkedBundle) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CreatedOK struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedOK) Reset()         { *m = CreatedOK{} }
func (m *CreatedOK) String() string { return proto.CompactTextString(m) }
func (*CreatedOK) ProtoMessage()    {}
func (*CreatedOK) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{5}
}
func (m *CreatedOK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedOK.Unmarshal(m, b)
}
func (m *CreatedOK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedOK.Marshal(b, m, deterministic)
}
func (dst *CreatedOK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedOK.Merge(dst, src)
}
func (m *CreatedOK) XXX_Size() int {
	return xxx_messageInfo_CreatedOK.Size(m)
}
func (m *CreatedOK) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedOK.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedOK proto.InternalMessageInfo

func (m *CreatedOK) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type WithNoticeBundle struct {
	ConversationID       string   `protobuf:"bytes,1,opt,name=ConversationID,proto3" json:"ConversationID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithNoticeBundle) Reset()         { *m = WithNoticeBundle{} }
func (m *WithNoticeBundle) String() string { return proto.CompactTextString(m) }
func (*WithNoticeBundle) ProtoMessage()    {}
func (*WithNoticeBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{6}
}
func (m *WithNoticeBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithNoticeBundle.Unmarshal(m, b)
}
func (m *WithNoticeBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithNoticeBundle.Marshal(b, m, deterministic)
}
func (dst *WithNoticeBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithNoticeBundle.Merge(dst, src)
}
func (m *WithNoticeBundle) XXX_Size() int {
	return xxx_messageInfo_WithNoticeBundle.Size(m)
}
func (m *WithNoticeBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_WithNoticeBundle.DiscardUnknown(m)
}

var xxx_messageInfo_WithNoticeBundle proto.InternalMessageInfo

func (m *WithNoticeBundle) GetConversationID() string {
	if m != nil {
		return m.ConversationID
	}
	return ""
}

func (m *WithNoticeBundle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *WithNoticeBundle) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type NoticePB struct {
	ConversationID       string   `protobuf:"bytes,1,opt,name=ConversationID,proto3" json:"ConversationID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticePB) Reset()         { *m = NoticePB{} }
func (m *NoticePB) String() string { return proto.CompactTextString(m) }
func (*NoticePB) ProtoMessage()    {}
func (*NoticePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{7}
}
func (m *NoticePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticePB.Unmarshal(m, b)
}
func (m *NoticePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticePB.Marshal(b, m, deterministic)
}
func (dst *NoticePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticePB.Merge(dst, src)
}
func (m *NoticePB) XXX_Size() int {
	return xxx_messageInfo_NoticePB.Size(m)
}
func (m *NoticePB) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticePB.DiscardUnknown(m)
}

var xxx_messageInfo_NoticePB proto.InternalMessageInfo

func (m *NoticePB) GetConversationID() string {
	if m != nil {
		return m.ConversationID
	}
	return ""
}

func (m *NoticePB) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoticePB) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type NoticesResponse struct {
	Notices              []*NoticePB `protobuf:"bytes,1,rep,name=Notices,proto3" json:"Notices,omitempty"`
	Total                int64       `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NoticesResponse) Reset()         { *m = NoticesResponse{} }
func (m *NoticesResponse) String() string { return proto.CompactTextString(m) }
func (*NoticesResponse) ProtoMessage()    {}
func (*NoticesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{8}
}
func (m *NoticesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticesResponse.Unmarshal(m, b)
}
func (m *NoticesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticesResponse.Marshal(b, m, deterministic)
}
func (dst *NoticesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticesResponse.Merge(dst, src)
}
func (m *NoticesResponse) XXX_Size() int {
	return xxx_messageInfo_NoticesResponse.Size(m)
}
func (m *NoticesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NoticesResponse proto.InternalMessageInfo

func (m *NoticesResponse) GetNotices() []*NoticePB {
	if m != nil {
		return m.Notices
	}
	return nil
}

func (m *NoticesResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ByIDWithPager struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByIDWithPager) Reset()         { *m = ByIDWithPager{} }
func (m *ByIDWithPager) String() string { return proto.CompactTextString(m) }
func (*ByIDWithPager) ProtoMessage()    {}
func (*ByIDWithPager) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{9}
}
func (m *ByIDWithPager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIDWithPager.Unmarshal(m, b)
}
func (m *ByIDWithPager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIDWithPager.Marshal(b, m, deterministic)
}
func (dst *ByIDWithPager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIDWithPager.Merge(dst, src)
}
func (m *ByIDWithPager) XXX_Size() int {
	return xxx_messageInfo_ByIDWithPager.Size(m)
}
func (m *ByIDWithPager) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIDWithPager.DiscardUnknown(m)
}

var xxx_messageInfo_ByIDWithPager proto.InternalMessageInfo

func (m *ByIDWithPager) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ByIDWithPager) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ByIDWithPager) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ByNoticeID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByNoticeID) Reset()         { *m = ByNoticeID{} }
func (m *ByNoticeID) String() string { return proto.CompactTextString(m) }
func (*ByNoticeID) ProtoMessage()    {}
func (*ByNoticeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{10}
}
func (m *ByNoticeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByNoticeID.Unmarshal(m, b)
}
func (m *ByNoticeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByNoticeID.Marshal(b, m, deterministic)
}
func (dst *ByNoticeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByNoticeID.Merge(dst, src)
}
func (m *ByNoticeID) XXX_Size() int {
	return xxx_messageInfo_ByNoticeID.Size(m)
}
func (m *ByNoticeID) XXX_DiscardUnknown() {
	xxx_messageInfo_ByNoticeID.DiscardUnknown(m)
}

var xxx_messageInfo_ByNoticeID proto.InternalMessageInfo

func (m *ByNoticeID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type MembersResponse struct {
	Members              []*proto1.User `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MembersResponse) Reset()         { *m = MembersResponse{} }
func (m *MembersResponse) String() string { return proto.CompactTextString(m) }
func (*MembersResponse) ProtoMessage()    {}
func (*MembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{11}
}
func (m *MembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MembersResponse.Unmarshal(m, b)
}
func (m *MembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MembersResponse.Marshal(b, m, deterministic)
}
func (dst *MembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MembersResponse.Merge(dst, src)
}
func (m *MembersResponse) XXX_Size() int {
	return xxx_messageInfo_MembersResponse.Size(m)
}
func (m *MembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MembersResponse proto.InternalMessageInfo

func (m *MembersResponse) GetMembers() []*proto1.User {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *MembersResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type WithUpdateBundle struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	GroupName            string   `protobuf:"bytes,3,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	IsTop                string   `protobuf:"bytes,4,opt,name=IsTop,proto3" json:"IsTop,omitempty"`
	IsStartValidate      string   `protobuf:"bytes,5,opt,name=IsStartValidate,proto3" json:"IsStartValidate,omitempty"`
	Master               string   `protobuf:"bytes,6,opt,name=Master,proto3" json:"Master,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithUpdateBundle) Reset()         { *m = WithUpdateBundle{} }
func (m *WithUpdateBundle) String() string { return proto.CompactTextString(m) }
func (*WithUpdateBundle) ProtoMessage()    {}
func (*WithUpdateBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{12}
}
func (m *WithUpdateBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithUpdateBundle.Unmarshal(m, b)
}
func (m *WithUpdateBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithUpdateBundle.Marshal(b, m, deterministic)
}
func (dst *WithUpdateBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithUpdateBundle.Merge(dst, src)
}
func (m *WithUpdateBundle) XXX_Size() int {
	return xxx_messageInfo_WithUpdateBundle.Size(m)
}
func (m *WithUpdateBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_WithUpdateBundle.DiscardUnknown(m)
}

var xxx_messageInfo_WithUpdateBundle proto.InternalMessageInfo

func (m *WithUpdateBundle) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *WithUpdateBundle) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *WithUpdateBundle) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *WithUpdateBundle) GetIsTop() string {
	if m != nil {
		return m.IsTop
	}
	return ""
}

func (m *WithUpdateBundle) GetIsStartValidate() string {
	if m != nil {
		return m.IsStartValidate
	}
	return ""
}

func (m *WithUpdateBundle) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *WithUpdateBundle) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type IsOK struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsOK) Reset()         { *m = IsOK{} }
func (m *IsOK) String() string { return proto.CompactTextString(m) }
func (*IsOK) ProtoMessage()    {}
func (*IsOK) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{13}
}
func (m *IsOK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsOK.Unmarshal(m, b)
}
func (m *IsOK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsOK.Marshal(b, m, deterministic)
}
func (dst *IsOK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsOK.Merge(dst, src)
}
func (m *IsOK) XXX_Size() int {
	return xxx_messageInfo_IsOK.Size(m)
}
func (m *IsOK) XXX_DiscardUnknown() {
	xxx_messageInfo_IsOK.DiscardUnknown(m)
}

var xxx_messageInfo_IsOK proto.InternalMessageInfo

func (m *IsOK) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type ConversationDetails struct {
	Conversation         *ConversationPB `protobuf:"bytes,1,opt,name=Conversation,proto3" json:"Conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConversationDetails) Reset()         { *m = ConversationDetails{} }
func (m *ConversationDetails) String() string { return proto.CompactTextString(m) }
func (*ConversationDetails) ProtoMessage()    {}
func (*ConversationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{14}
}
func (m *ConversationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationDetails.Unmarshal(m, b)
}
func (m *ConversationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationDetails.Marshal(b, m, deterministic)
}
func (dst *ConversationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationDetails.Merge(dst, src)
}
func (m *ConversationDetails) XXX_Size() int {
	return xxx_messageInfo_ConversationDetails.Size(m)
}
func (m *ConversationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationDetails proto.InternalMessageInfo

func (m *ConversationDetails) GetConversation() *ConversationPB {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type ByID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByID) Reset()         { *m = ByID{} }
func (m *ByID) String() string { return proto.CompactTextString(m) }
func (*ByID) ProtoMessage()    {}
func (*ByID) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{15}
}
func (m *ByID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByID.Unmarshal(m, b)
}
func (m *ByID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByID.Marshal(b, m, deterministic)
}
func (dst *ByID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByID.Merge(dst, src)
}
func (m *ByID) XXX_Size() int {
	return xxx_messageInfo_ByID.Size(m)
}
func (m *ByID) XXX_DiscardUnknown() {
	xxx_messageInfo_ByID.DiscardUnknown(m)
}

var xxx_messageInfo_ByID proto.InternalMessageInfo

func (m *ByID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ByIDWithUserID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByIDWithUserID) Reset()         { *m = ByIDWithUserID{} }
func (m *ByIDWithUserID) String() string { return proto.CompactTextString(m) }
func (*ByIDWithUserID) ProtoMessage()    {}
func (*ByIDWithUserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{16}
}
func (m *ByIDWithUserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIDWithUserID.Unmarshal(m, b)
}
func (m *ByIDWithUserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIDWithUserID.Marshal(b, m, deterministic)
}
func (dst *ByIDWithUserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIDWithUserID.Merge(dst, src)
}
func (m *ByIDWithUserID) XXX_Size() int {
	return xxx_messageInfo_ByIDWithUserID.Size(m)
}
func (m *ByIDWithUserID) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIDWithUserID.DiscardUnknown(m)
}

var xxx_messageInfo_ByIDWithUserID proto.InternalMessageInfo

func (m *ByIDWithUserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ByIDWithUserID) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ConversationsResponse struct {
	Conversations        []*ConversationPB `protobuf:"bytes,1,rep,name=Conversations,proto3" json:"Conversations,omitempty"`
	Total                int64             `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConversationsResponse) Reset()         { *m = ConversationsResponse{} }
func (m *ConversationsResponse) String() string { return proto.CompactTextString(m) }
func (*ConversationsResponse) ProtoMessage()    {}
func (*ConversationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{17}
}
func (m *ConversationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationsResponse.Unmarshal(m, b)
}
func (m *ConversationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationsResponse.Marshal(b, m, deterministic)
}
func (dst *ConversationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationsResponse.Merge(dst, src)
}
func (m *ConversationsResponse) XXX_Size() int {
	return xxx_messageInfo_ConversationsResponse.Size(m)
}
func (m *ConversationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationsResponse proto.InternalMessageInfo

func (m *ConversationsResponse) GetConversations() []*ConversationPB {
	if m != nil {
		return m.Conversations
	}
	return nil
}

func (m *ConversationsResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ByUserID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByUserID) Reset()         { *m = ByUserID{} }
func (m *ByUserID) String() string { return proto.CompactTextString(m) }
func (*ByUserID) ProtoMessage()    {}
func (*ByUserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{18}
}
func (m *ByUserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByUserID.Unmarshal(m, b)
}
func (m *ByUserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByUserID.Marshal(b, m, deterministic)
}
func (dst *ByUserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByUserID.Merge(dst, src)
}
func (m *ByUserID) XXX_Size() int {
	return xxx_messageInfo_ByUserID.Size(m)
}
func (m *ByUserID) XXX_DiscardUnknown() {
	xxx_messageInfo_ByUserID.DiscardUnknown(m)
}

var xxx_messageInfo_ByUserID proto.InternalMessageInfo

func (m *ByUserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ConversationPB struct {
	ID                   string                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Kind                 string                `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name                 string                `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar               string                `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Members              []*ConversationMember `protobuf:"bytes,5,rep,name=Members,proto3" json:"Members,omitempty"`
	Master               string                `protobuf:"bytes,6,opt,name=Master,proto3" json:"Master,omitempty"`
	IsStartValidate      bool                  `protobuf:"varint,7,opt,name=IsStartValidate,proto3" json:"IsStartValidate,omitempty"`
	IsTop                bool                  `protobuf:"varint,8,opt,name=IsTop,proto3" json:"IsTop,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp  `protobuf:"bytes,10,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConversationPB) Reset()         { *m = ConversationPB{} }
func (m *ConversationPB) String() string { return proto.CompactTextString(m) }
func (*ConversationPB) ProtoMessage()    {}
func (*ConversationPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{19}
}
func (m *ConversationPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationPB.Unmarshal(m, b)
}
func (m *ConversationPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationPB.Marshal(b, m, deterministic)
}
func (dst *ConversationPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationPB.Merge(dst, src)
}
func (m *ConversationPB) XXX_Size() int {
	return xxx_messageInfo_ConversationPB.Size(m)
}
func (m *ConversationPB) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationPB.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationPB proto.InternalMessageInfo

func (m *ConversationPB) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConversationPB) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ConversationPB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConversationPB) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ConversationPB) GetMembers() []*ConversationMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *ConversationPB) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *ConversationPB) GetIsStartValidate() bool {
	if m != nil {
		return m.IsStartValidate
	}
	return false
}

func (m *ConversationPB) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

func (m *ConversationPB) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ConversationPB) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ConversationMember struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	IsTop                bool     `protobuf:"varint,3,opt,name=IsTop,proto3" json:"IsTop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConversationMember) Reset()         { *m = ConversationMember{} }
func (m *ConversationMember) String() string { return proto.CompactTextString(m) }
func (*ConversationMember) ProtoMessage()    {}
func (*ConversationMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{20}
}
func (m *ConversationMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationMember.Unmarshal(m, b)
}
func (m *ConversationMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationMember.Marshal(b, m, deterministic)
}
func (dst *ConversationMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationMember.Merge(dst, src)
}
func (m *ConversationMember) XXX_Size() int {
	return xxx_messageInfo_ConversationMember.Size(m)
}
func (m *ConversationMember) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationMember.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationMember proto.InternalMessageInfo

func (m *ConversationMember) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ConversationMember) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ConversationMember) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

type WithConversationBundle struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Members              []string `protobuf:"bytes,4,rep,name=Members,proto3" json:"Members,omitempty"`
	Master               string   `protobuf:"bytes,5,opt,name=Master,proto3" json:"Master,omitempty"`
	IsStartValidate      bool     `protobuf:"varint,6,opt,name=IsStartValidate,proto3" json:"IsStartValidate,omitempty"`
	IsTop                bool     `protobuf:"varint,7,opt,name=IsTop,proto3" json:"IsTop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithConversationBundle) Reset()         { *m = WithConversationBundle{} }
func (m *WithConversationBundle) String() string { return proto.CompactTextString(m) }
func (*WithConversationBundle) ProtoMessage()    {}
func (*WithConversationBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_conversation_2d7b3b8c29a9330f, []int{21}
}
func (m *WithConversationBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithConversationBundle.Unmarshal(m, b)
}
func (m *WithConversationBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithConversationBundle.Marshal(b, m, deterministic)
}
func (dst *WithConversationBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithConversationBundle.Merge(dst, src)
}
func (m *WithConversationBundle) XXX_Size() int {
	return xxx_messageInfo_WithConversationBundle.Size(m)
}
func (m *WithConversationBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_WithConversationBundle.DiscardUnknown(m)
}

var xxx_messageInfo_WithConversationBundle proto.InternalMessageInfo

func (m *WithConversationBundle) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *WithConversationBundle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WithConversationBundle) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *WithConversationBundle) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *WithConversationBundle) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *WithConversationBundle) GetIsStartValidate() bool {
	if m != nil {
		return m.IsStartValidate
	}
	return false
}

func (m *WithConversationBundle) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

func init() {
	proto.RegisterType((*WithIDAndMembers)(nil), "iunite.club.srv.core.conversation.WithIDAndMembers")
	proto.RegisterType((*WithIDAndUserID)(nil), "iunite.club.srv.core.conversation.WithIDAndUserID")
	proto.RegisterType((*WithID)(nil), "iunite.club.srv.core.conversation.WithID")
	proto.RegisterType((*UpdatedOK)(nil), "iunite.club.srv.core.conversation.UpdatedOK")
	proto.RegisterType((*WithMarkedBundle)(nil), "iunite.club.srv.core.conversation.WithMarkedBundle")
	proto.RegisterType((*CreatedOK)(nil), "iunite.club.srv.core.conversation.CreatedOK")
	proto.RegisterType((*WithNoticeBundle)(nil), "iunite.club.srv.core.conversation.WithNoticeBundle")
	proto.RegisterType((*NoticePB)(nil), "iunite.club.srv.core.conversation.NoticePB")
	proto.RegisterType((*NoticesResponse)(nil), "iunite.club.srv.core.conversation.NoticesResponse")
	proto.RegisterType((*ByIDWithPager)(nil), "iunite.club.srv.core.conversation.ByIDWithPager")
	proto.RegisterType((*ByNoticeID)(nil), "iunite.club.srv.core.conversation.ByNoticeID")
	proto.RegisterType((*MembersResponse)(nil), "iunite.club.srv.core.conversation.MembersResponse")
	proto.RegisterType((*WithUpdateBundle)(nil), "iunite.club.srv.core.conversation.WithUpdateBundle")
	proto.RegisterType((*IsOK)(nil), "iunite.club.srv.core.conversation.IsOK")
	proto.RegisterType((*ConversationDetails)(nil), "iunite.club.srv.core.conversation.ConversationDetails")
	proto.RegisterType((*ByID)(nil), "iunite.club.srv.core.conversation.ByID")
	proto.RegisterType((*ByIDWithUserID)(nil), "iunite.club.srv.core.conversation.ByIDWithUserID")
	proto.RegisterType((*ConversationsResponse)(nil), "iunite.club.srv.core.conversation.ConversationsResponse")
	proto.RegisterType((*ByUserID)(nil), "iunite.club.srv.core.conversation.ByUserID")
	proto.RegisterType((*ConversationPB)(nil), "iunite.club.srv.core.conversation.ConversationPB")
	proto.RegisterType((*ConversationMember)(nil), "iunite.club.srv.core.conversation.ConversationMember")
	proto.RegisterType((*WithConversationBundle)(nil), "iunite.club.srv.core.conversation.WithConversationBundle")
}

func init() {
	proto.RegisterFile("proto/conversation/conversation.proto", fileDescriptor_conversation_2d7b3b8c29a9330f)
}

var fileDescriptor_conversation_2d7b3b8c29a9330f = []byte{
	// 1051 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5d, 0x6f, 0xe3, 0x44,
	0x17, 0x8e, 0x93, 0x34, 0x69, 0x4e, 0xbf, 0xde, 0x77, 0x60, 0xbb, 0x96, 0xbb, 0x12, 0x65, 0x24,
	0xa0, 0xe2, 0xc3, 0x61, 0xb3, 0x80, 0xba, 0x12, 0x37, 0xf1, 0x7a, 0xb7, 0x98, 0x6e, 0x37, 0x95,
	0x69, 0xd9, 0x1b, 0x40, 0x72, 0xe2, 0xd9, 0x32, 0x5a, 0xc7, 0x8e, 0x3c, 0x93, 0xb0, 0x91, 0x2a,
	0x71, 0x05, 0x3f, 0x83, 0x1f, 0x84, 0xf8, 0x4b, 0x48, 0xc8, 0x33, 0xb6, 0x33, 0xce, 0x07, 0xb5,
	0x91, 0xe0, 0xce, 0xe7, 0x8c, 0xcf, 0x3c, 0xe7, 0xf8, 0x79, 0xce, 0x9c, 0x31, 0xbc, 0x37, 0x89,
	0x23, 0x1e, 0x75, 0x47, 0x51, 0x38, 0x23, 0x31, 0xf3, 0x38, 0x8d, 0xc2, 0x82, 0x61, 0x8a, 0x75,
	0xf4, 0x2e, 0x9d, 0x86, 0x94, 0x13, 0x73, 0x14, 0x4c, 0x87, 0x26, 0x8b, 0x67, 0xe6, 0x28, 0x8a,
	0x89, 0xa9, 0xbe, 0x68, 0xbc, 0x73, 0x13, 0x45, 0x37, 0x01, 0xe9, 0x8a, 0x80, 0xe1, 0xf4, 0x55,
	0x97, 0xd3, 0x31, 0x61, 0xdc, 0x1b, 0x4f, 0xe4, 0x1e, 0xc6, 0x87, 0xca, 0x1e, 0x5d, 0x46, 0xe2,
	0x19, 0x1d, 0x11, 0xd6, 0x9d, 0x32, 0x12, 0xcb, 0x18, 0xf1, 0x28, 0xdf, 0xc5, 0x5f, 0xc2, 0xff,
	0x5e, 0x52, 0xfe, 0xa3, 0x63, 0xf7, 0x43, 0xff, 0x82, 0x8c, 0x87, 0x24, 0x66, 0x68, 0x1f, 0xea,
	0x8e, 0xad, 0x6b, 0xc7, 0xda, 0x49, 0xc7, 0xad, 0x3b, 0x36, 0xd2, 0xa1, 0x9d, 0x2e, 0xe9, 0xf5,
	0xe3, 0xc6, 0x49, 0xc7, 0xcd, 0x4c, 0xfc, 0x18, 0x0e, 0xf2, 0xe8, 0x6b, 0x46, 0x62, 0xc7, 0x5e,
	0x09, 0x3e, 0x84, 0x96, 0x5c, 0xd1, 0xeb, 0xc2, 0x97, 0x5a, 0x58, 0x87, 0x96, 0x0c, 0x5d, 0x8e,
	0xc0, 0x47, 0xd0, 0xb9, 0x9e, 0xf8, 0x1e, 0x27, 0xfe, 0xe0, 0x3c, 0x59, 0x1c, 0x9c, 0x8b, 0xc5,
	0x6d, 0xb7, 0x3e, 0x38, 0xc7, 0xcf, 0x64, 0xbe, 0x17, 0x5e, 0xfc, 0x9a, 0xf8, 0xd6, 0x34, 0xf4,
	0x03, 0x82, 0x0c, 0xd8, 0x7e, 0x11, 0x71, 0x3a, 0x22, 0xf9, 0x36, 0xb9, 0xbd, 0x11, 0xfe, 0x08,
	0x3a, 0x4f, 0x62, 0xb2, 0x01, 0xc4, 0x97, 0x20, 0x72, 0x93, 0x14, 0xe4, 0x7d, 0xd8, 0x7f, 0xa2,
	0xb0, 0x90, 0x43, 0x2d, 0x79, 0xd1, 0xdb, 0xb0, 0x75, 0x45, 0x79, 0x40, 0x52, 0x3c, 0x69, 0x20,
	0x04, 0x4d, 0x2b, 0xf2, 0xe7, 0x7a, 0x43, 0x38, 0xc5, 0x33, 0xfe, 0x2e, 0x4b, 0xfb, 0xd2, 0xfa,
	0x17, 0x76, 0x0f, 0xe1, 0x40, 0xee, 0xce, 0x5c, 0xc2, 0x26, 0x51, 0xc8, 0x08, 0x7a, 0x0a, 0xed,
	0xd4, 0xa5, 0x6b, 0xc7, 0x8d, 0x93, 0x9d, 0xde, 0x47, 0xe6, 0x9d, 0x6a, 0x33, 0xb3, 0x14, 0xdd,
	0x2c, 0x56, 0xe4, 0x10, 0x71, 0x2f, 0x10, 0x39, 0x34, 0x5c, 0x69, 0x60, 0x07, 0xf6, 0xac, 0xb9,
	0x63, 0x27, 0xdf, 0xed, 0xd2, 0xbb, 0x21, 0xf1, 0x8a, 0x10, 0x10, 0x34, 0x93, 0x85, 0x34, 0x4a,
	0x3c, 0x27, 0x5b, 0x3d, 0xa7, 0x63, 0xca, 0x45, 0xe6, 0x0d, 0x57, 0x1a, 0xf8, 0x01, 0x80, 0x35,
	0xcf, 0x19, 0x5c, 0x96, 0xc7, 0xf7, 0x70, 0x90, 0xca, 0x2f, 0x2f, 0xec, 0xb3, 0x85, 0x40, 0x65,
	0x61, 0xc6, 0x4a, 0x61, 0x42, 0xf2, 0x09, 0xf7, 0xb9, 0x78, 0x37, 0xd4, 0xf1, 0x87, 0x26, 0xc9,
	0x97, 0x12, 0x4c, 0xc9, 0x5f, 0xae, 0x25, 0x51, 0x1c, 0x1d, 0xbd, 0x0e, 0xbd, 0x71, 0xc6, 0x44,
	0x6e, 0xa3, 0x07, 0xd0, 0x39, 0x8b, 0xa3, 0xe9, 0xe4, 0x45, 0xb2, 0x28, 0x19, 0x59, 0x38, 0x12,
	0x50, 0x87, 0x5d, 0x45, 0x13, 0xbd, 0x29, 0x09, 0x14, 0x06, 0x3a, 0x81, 0x03, 0x87, 0x7d, 0xc3,
	0xbd, 0x98, 0x7f, 0xeb, 0x05, 0x34, 0x01, 0xd6, 0xb7, 0xc4, 0xfa, 0xb2, 0x3b, 0xd1, 0xf3, 0x85,
	0xc7, 0x38, 0x89, 0xf5, 0x96, 0xd4, 0xb3, 0xb4, 0x12, 0x7f, 0x7f, 0xe6, 0x71, 0x2f, 0xd6, 0xdb,
	0xd2, 0x2f, 0x2d, 0x7c, 0x08, 0x4d, 0x87, 0xad, 0x91, 0x78, 0x00, 0x6f, 0xa9, 0xd2, 0xb2, 0x09,
	0xf7, 0x68, 0xc0, 0xd0, 0x35, 0xec, 0xaa, 0x6e, 0x11, 0xb0, 0xd3, 0x7b, 0x58, 0x42, 0x27, 0x6a,
	0xd8, 0xa5, 0xe5, 0x16, 0xb6, 0x49, 0xb2, 0x48, 0xc4, 0xb1, 0xc2, 0xe5, 0x29, 0xec, 0x67, 0xa2,
	0xa9, 0x78, 0x7c, 0xfc, 0xaa, 0xc1, 0x3d, 0x15, 0x62, 0x21, 0x86, 0x97, 0xb0, 0x57, 0x58, 0x48,
	0x25, 0xf1, 0x0f, 0x6a, 0x28, 0xee, 0xb3, 0x41, 0x2f, 0x06, 0x6c, 0x5b, 0xf3, 0xf5, 0xc9, 0xe3,
	0x3f, 0xeb, 0xc5, 0xb6, 0xbe, 0xb4, 0xd6, 0x75, 0xc5, 0x39, 0x0d, 0xfd, 0xb4, 0x3a, 0xf1, 0x9c,
	0xf8, 0x14, 0xf1, 0x88, 0x67, 0x85, 0xdf, 0xa6, 0xca, 0x2f, 0x1a, 0x2c, 0xa4, 0xbf, 0x25, 0xea,
	0xfc, 0xbc, 0x62, 0x9d, 0x32, 0x7a, 0xd1, 0x15, 0x9b, 0x04, 0xb6, 0x46, 0xa2, 0x6d, 0xa1, 0xa6,
	0x15, 0x89, 0xe6, 0x12, 0xdf, 0x16, 0xeb, 0xa9, 0xc4, 0x4f, 0xf3, 0x03, 0xb7, 0xcf, 0xf5, 0x8e,
	0x90, 0x95, 0x61, 0xca, 0x49, 0x66, 0x66, 0x93, 0xcc, 0xbc, 0xca, 0x26, 0x99, 0xbb, 0x78, 0x39,
	0x89, 0x4c, 0xe7, 0x41, 0x9f, 0xeb, 0x70, 0x77, 0x64, 0xfe, 0x32, 0xfe, 0x01, 0xd0, 0x6a, 0xa9,
	0x8a, 0xa4, 0x34, 0x55, 0x52, 0x7f, 0xdb, 0xd4, 0x79, 0x4d, 0x0d, 0xa5, 0x26, 0xfc, 0xbb, 0x06,
	0x87, 0x89, 0x76, 0x55, 0x90, 0xf4, 0xc4, 0xc8, 0x78, 0xd5, 0xd6, 0xf0, 0x5a, 0x5f, 0xcb, 0x6b,
	0xa3, 0xc0, 0xab, 0x32, 0x73, 0x9b, 0x85, 0x99, 0xab, 0x10, 0xb4, 0x75, 0x17, 0x41, 0xad, 0x3b,
	0x08, 0x6a, 0x2b, 0xc5, 0xf4, 0x7e, 0xdb, 0x2b, 0xf6, 0x3e, 0xfa, 0x19, 0x90, 0x24, 0xa1, 0xe0,
	0x7d, 0x5c, 0x42, 0x5f, 0xeb, 0xbf, 0x89, 0xf1, 0x71, 0x19, 0x69, 0x66, 0x43, 0x19, 0xd7, 0xd0,
	0x2f, 0x1a, 0x18, 0x67, 0x84, 0x17, 0xba, 0xd0, 0x9a, 0xcb, 0xef, 0xe0, 0xd8, 0xa8, 0xcc, 0xf4,
	0xca, 0x5a, 0xd3, 0x38, 0xad, 0xd8, 0x16, 0xf9, 0x79, 0x82, 0x6b, 0xe8, 0x16, 0xee, 0x3f, 0xa3,
	0xa1, 0xbf, 0xee, 0xbc, 0xfc, 0xa0, 0x54, 0x0e, 0x8e, 0x6d, 0x7c, 0x51, 0x11, 0x3f, 0x05, 0xc0,
	0x35, 0x44, 0xa1, 0xf3, 0xf4, 0x0d, 0xe5, 0x62, 0x84, 0xa0, 0x87, 0x25, 0xf1, 0x16, 0x27, 0xaa,
	0x51, 0x26, 0xc5, 0x64, 0x44, 0xe0, 0x1a, 0x1a, 0xc2, 0xae, 0x4d, 0xd9, 0x98, 0x32, 0x26, 0xd1,
	0x4a, 0x57, 0x57, 0x01, 0x63, 0x0e, 0xf7, 0x65, 0x83, 0x0a, 0x88, 0x82, 0xb4, 0x1e, 0x95, 0x94,
	0x96, 0x3a, 0x9a, 0xab, 0x40, 0xdf, 0xc2, 0xd1, 0x19, 0xe1, 0xfd, 0x20, 0x48, 0x5b, 0x69, 0xf0,
	0xaa, 0x00, 0x5f, 0xba, 0xda, 0x5e, 0x89, 0x17, 0x97, 0xae, 0x28, 0xb8, 0x86, 0x38, 0xe8, 0x2e,
	0x19, 0x47, 0xb3, 0x42, 0x3b, 0xc9, 0x5b, 0x0e, 0xfa, 0xa4, 0x14, 0x74, 0x76, 0x25, 0xaa, 0x52,
	0xf3, 0x4f, 0xb0, 0x77, 0x46, 0xb8, 0x8c, 0x7c, 0x4e, 0x19, 0x47, 0x9f, 0x56, 0x50, 0x90, 0xb8,
	0xc8, 0x95, 0x2a, 0x77, 0xe9, 0xaa, 0x89, 0x6b, 0x88, 0xc1, 0xae, 0xec, 0xe5, 0xb4, 0xc4, 0xb2,
	0xe4, 0xaa, 0x97, 0xee, 0xca, 0x27, 0xc6, 0x2d, 0xdc, 0x93, 0x7f, 0x06, 0x72, 0x97, 0xab, 0xe8,
	0x2b, 0x8f, 0xb9, 0xc4, 0xf3, 0x4b, 0xa3, 0xab, 0xff, 0x15, 0xa5, 0xd0, 0xf3, 0x3f, 0x15, 0x5c,
	0x43, 0x53, 0xd8, 0xef, 0xfb, 0xbe, 0xd0, 0x75, 0x3a, 0x6a, 0xca, 0xc2, 0xaa, 0xbf, 0x5f, 0x95,
	0x61, 0xdf, 0xc0, 0xff, 0xa5, 0xb0, 0xfe, 0x73, 0xe4, 0x00, 0x76, 0xbe, 0x8e, 0x68, 0xe8, 0x84,
	0xf2, 0xb8, 0xe8, 0x55, 0xc1, 0xac, 0x7c, 0x3a, 0x0d, 0x5b, 0x62, 0xd8, 0x3f, 0xfa, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x68, 0xc4, 0x43, 0x7c, 0x4a, 0x0f, 0x00, 0x00,
}
