// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/role/role.proto

package iunite_club_srv_core_role

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import proto1 "iunite.club/services/user/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoleGroupPB struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	GroupDescription     string   `protobuf:"bytes,2,opt,name=GroupDescription,proto3" json:"GroupDescription,omitempty"`
	Organization         string   `protobuf:"bytes,3,opt,name=Organization,proto3" json:"Organization,omitempty"`
	ID                   string   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleGroupPB) Reset()         { *m = RoleGroupPB{} }
func (m *RoleGroupPB) String() string { return proto.CompactTextString(m) }
func (*RoleGroupPB) ProtoMessage()    {}
func (*RoleGroupPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{0}
}
func (m *RoleGroupPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleGroupPB.Unmarshal(m, b)
}
func (m *RoleGroupPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleGroupPB.Marshal(b, m, deterministic)
}
func (dst *RoleGroupPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleGroupPB.Merge(dst, src)
}
func (m *RoleGroupPB) XXX_Size() int {
	return xxx_messageInfo_RoleGroupPB.Size(m)
}
func (m *RoleGroupPB) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleGroupPB.DiscardUnknown(m)
}

var xxx_messageInfo_RoleGroupPB proto.InternalMessageInfo

func (m *RoleGroupPB) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *RoleGroupPB) GetGroupDescription() string {
	if m != nil {
		return m.GroupDescription
	}
	return ""
}

func (m *RoleGroupPB) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *RoleGroupPB) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RolePB struct {
	ID                   string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                string       `protobuf:"bytes,3,opt,name=Level,proto3" json:"Level,omitempty"`
	GroupID              string       `protobuf:"bytes,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Organization         string       `protobuf:"bytes,5,opt,name=Organization,proto3" json:"Organization,omitempty"`
	Group                *RoleGroupPB `protobuf:"bytes,6,opt,name=Group,proto3" json:"Group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RolePB) Reset()         { *m = RolePB{} }
func (m *RolePB) String() string { return proto.CompactTextString(m) }
func (*RolePB) ProtoMessage()    {}
func (*RolePB) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{1}
}
func (m *RolePB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolePB.Unmarshal(m, b)
}
func (m *RolePB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolePB.Marshal(b, m, deterministic)
}
func (dst *RolePB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePB.Merge(dst, src)
}
func (m *RolePB) XXX_Size() int {
	return xxx_messageInfo_RolePB.Size(m)
}
func (m *RolePB) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePB.DiscardUnknown(m)
}

var xxx_messageInfo_RolePB proto.InternalMessageInfo

func (m *RolePB) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RolePB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RolePB) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *RolePB) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *RolePB) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *RolePB) GetGroup() *RoleGroupPB {
	if m != nil {
		return m.Group
	}
	return nil
}

type UpdateRoleRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                string   `protobuf:"bytes,3,opt,name=Level,proto3" json:"Level,omitempty"`
	GroupID              string   `protobuf:"bytes,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Organization         string   `protobuf:"bytes,5,opt,name=Organization,proto3" json:"Organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoleRequest) Reset()         { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()    {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{2}
}
func (m *UpdateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleRequest.Unmarshal(m, b)
}
func (m *UpdateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleRequest.Merge(dst, src)
}
func (m *UpdateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleRequest.Size(m)
}
func (m *UpdateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleRequest proto.InternalMessageInfo

func (m *UpdateRoleRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRoleRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *UpdateRoleRequest) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *UpdateRoleRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type UpdateRoleResponse struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateRoleResponse) Reset()         { *m = UpdateRoleResponse{} }
func (m *UpdateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleResponse) ProtoMessage()    {}
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{3}
}
func (m *UpdateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleResponse.Unmarshal(m, b)
}
func (m *UpdateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleResponse.Merge(dst, src)
}
func (m *UpdateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleResponse.Size(m)
}
func (m *UpdateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleResponse proto.InternalMessageInfo

func (m *UpdateRoleResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateRoleResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ByIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByIDRequest) Reset()         { *m = ByIDRequest{} }
func (m *ByIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByIDRequest) ProtoMessage()    {}
func (*ByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{4}
}
func (m *ByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByIDRequest.Unmarshal(m, b)
}
func (m *ByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByIDRequest.Marshal(b, m, deterministic)
}
func (dst *ByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByIDRequest.Merge(dst, src)
}
func (m *ByIDRequest) XXX_Size() int {
	return xxx_messageInfo_ByIDRequest.Size(m)
}
func (m *ByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByIDRequest proto.InternalMessageInfo

func (m *ByIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeletedResponse struct {
	OK                   bool                 `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeletedResponse) Reset()         { *m = DeletedResponse{} }
func (m *DeletedResponse) String() string { return proto.CompactTextString(m) }
func (*DeletedResponse) ProtoMessage()    {}
func (*DeletedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{5}
}
func (m *DeletedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedResponse.Unmarshal(m, b)
}
func (m *DeletedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedResponse.Marshal(b, m, deterministic)
}
func (dst *DeletedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedResponse.Merge(dst, src)
}
func (m *DeletedResponse) XXX_Size() int {
	return xxx_messageInfo_DeletedResponse.Size(m)
}
func (m *DeletedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedResponse proto.InternalMessageInfo

func (m *DeletedResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *DeletedResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateRoleRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                string   `protobuf:"bytes,2,opt,name=Level,proto3" json:"Level,omitempty"`
	GroupID              string   `protobuf:"bytes,3,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Organization         string   `protobuf:"bytes,4,opt,name=Organization,proto3" json:"Organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleRequest) Reset()         { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()    {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{6}
}
func (m *CreateRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleRequest.Unmarshal(m, b)
}
func (m *CreateRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleRequest.Merge(dst, src)
}
func (m *CreateRoleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleRequest.Size(m)
}
func (m *CreateRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleRequest proto.InternalMessageInfo

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *CreateRoleRequest) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

func (m *CreateRoleRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type CreatedRoleResponse struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatedRoleResponse) Reset()         { *m = CreatedRoleResponse{} }
func (m *CreatedRoleResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedRoleResponse) ProtoMessage()    {}
func (*CreatedRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{7}
}
func (m *CreatedRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedRoleResponse.Unmarshal(m, b)
}
func (m *CreatedRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedRoleResponse.Marshal(b, m, deterministic)
}
func (dst *CreatedRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedRoleResponse.Merge(dst, src)
}
func (m *CreatedRoleResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedRoleResponse.Size(m)
}
func (m *CreatedRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedRoleResponse proto.InternalMessageInfo

func (m *CreatedRoleResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreatedRoleResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UsersAndRoleRequest struct {
	Users                []string `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersAndRoleRequest) Reset()         { *m = UsersAndRoleRequest{} }
func (m *UsersAndRoleRequest) String() string { return proto.CompactTextString(m) }
func (*UsersAndRoleRequest) ProtoMessage()    {}
func (*UsersAndRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{8}
}
func (m *UsersAndRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAndRoleRequest.Unmarshal(m, b)
}
func (m *UsersAndRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAndRoleRequest.Marshal(b, m, deterministic)
}
func (dst *UsersAndRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAndRoleRequest.Merge(dst, src)
}
func (m *UsersAndRoleRequest) XXX_Size() int {
	return xxx_messageInfo_UsersAndRoleRequest.Size(m)
}
func (m *UsersAndRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAndRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAndRoleRequest proto.InternalMessageInfo

func (m *UsersAndRoleRequest) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UsersAndRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CreatedResponse struct {
	OK                   bool                 `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatedResponse) Reset()         { *m = CreatedResponse{} }
func (m *CreatedResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedResponse) ProtoMessage()    {}
func (*CreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{9}
}
func (m *CreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedResponse.Unmarshal(m, b)
}
func (m *CreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedResponse.Marshal(b, m, deterministic)
}
func (dst *CreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedResponse.Merge(dst, src)
}
func (m *CreatedResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedResponse.Size(m)
}
func (m *CreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedResponse proto.InternalMessageInfo

func (m *CreatedResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *CreatedResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UpdateRoleGroupRequest struct {
	RoleGroup            *RoleGroupPB `protobuf:"bytes,1,opt,name=RoleGroup,proto3" json:"RoleGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateRoleGroupRequest) Reset()         { *m = UpdateRoleGroupRequest{} }
func (m *UpdateRoleGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoleGroupRequest) ProtoMessage()    {}
func (*UpdateRoleGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{10}
}
func (m *UpdateRoleGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoleGroupRequest.Unmarshal(m, b)
}
func (m *UpdateRoleGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoleGroupRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRoleGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoleGroupRequest.Merge(dst, src)
}
func (m *UpdateRoleGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoleGroupRequest.Size(m)
}
func (m *UpdateRoleGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoleGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoleGroupRequest proto.InternalMessageInfo

func (m *UpdateRoleGroupRequest) GetRoleGroup() *RoleGroupPB {
	if m != nil {
		return m.RoleGroup
	}
	return nil
}

type UpdatedResponse struct {
	OK                   bool                 `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdatedResponse) Reset()         { *m = UpdatedResponse{} }
func (m *UpdatedResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatedResponse) ProtoMessage()    {}
func (*UpdatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{11}
}
func (m *UpdatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedResponse.Unmarshal(m, b)
}
func (m *UpdatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedResponse.Merge(dst, src)
}
func (m *UpdatedResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatedResponse.Size(m)
}
func (m *UpdatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedResponse proto.InternalMessageInfo

func (m *UpdatedResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *UpdatedResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ByGroupIDRequest struct {
	GroupID              string   `protobuf:"bytes,1,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByGroupIDRequest) Reset()         { *m = ByGroupIDRequest{} }
func (m *ByGroupIDRequest) String() string { return proto.CompactTextString(m) }
func (*ByGroupIDRequest) ProtoMessage()    {}
func (*ByGroupIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{12}
}
func (m *ByGroupIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByGroupIDRequest.Unmarshal(m, b)
}
func (m *ByGroupIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByGroupIDRequest.Marshal(b, m, deterministic)
}
func (dst *ByGroupIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByGroupIDRequest.Merge(dst, src)
}
func (m *ByGroupIDRequest) XXX_Size() int {
	return xxx_messageInfo_ByGroupIDRequest.Size(m)
}
func (m *ByGroupIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByGroupIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByGroupIDRequest proto.InternalMessageInfo

func (m *ByGroupIDRequest) GetGroupID() string {
	if m != nil {
		return m.GroupID
	}
	return ""
}

type DeletedRoleGroupResponse struct {
	OK                   bool                 `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeletedRoleGroupResponse) Reset()         { *m = DeletedRoleGroupResponse{} }
func (m *DeletedRoleGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeletedRoleGroupResponse) ProtoMessage()    {}
func (*DeletedRoleGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{13}
}
func (m *DeletedRoleGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedRoleGroupResponse.Unmarshal(m, b)
}
func (m *DeletedRoleGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedRoleGroupResponse.Marshal(b, m, deterministic)
}
func (dst *DeletedRoleGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedRoleGroupResponse.Merge(dst, src)
}
func (m *DeletedRoleGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeletedRoleGroupResponse.Size(m)
}
func (m *DeletedRoleGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedRoleGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedRoleGroupResponse proto.InternalMessageInfo

func (m *DeletedRoleGroupResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *DeletedRoleGroupResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type ByRoleRequest struct {
	Role                 string   `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByRoleRequest) Reset()         { *m = ByRoleRequest{} }
func (m *ByRoleRequest) String() string { return proto.CompactTextString(m) }
func (*ByRoleRequest) ProtoMessage()    {}
func (*ByRoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{14}
}
func (m *ByRoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByRoleRequest.Unmarshal(m, b)
}
func (m *ByRoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByRoleRequest.Marshal(b, m, deterministic)
}
func (dst *ByRoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByRoleRequest.Merge(dst, src)
}
func (m *ByRoleRequest) XXX_Size() int {
	return xxx_messageInfo_ByRoleRequest.Size(m)
}
func (m *ByRoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByRoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByRoleRequest proto.InternalMessageInfo

func (m *ByRoleRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type UsersResponse struct {
	Users                []*proto1.User `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	Total                int32          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{15}
}
func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (dst *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(dst, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*proto1.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UsersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ByOrganizationRequest struct {
	Organization         string   `protobuf:"bytes,1,opt,name=Organization,proto3" json:"Organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByOrganizationRequest) Reset()         { *m = ByOrganizationRequest{} }
func (m *ByOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*ByOrganizationRequest) ProtoMessage()    {}
func (*ByOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{16}
}
func (m *ByOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByOrganizationRequest.Unmarshal(m, b)
}
func (m *ByOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByOrganizationRequest.Marshal(b, m, deterministic)
}
func (dst *ByOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByOrganizationRequest.Merge(dst, src)
}
func (m *ByOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_ByOrganizationRequest.Size(m)
}
func (m *ByOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByOrganizationRequest proto.InternalMessageInfo

func (m *ByOrganizationRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type RolesResponse struct {
	Roles                []*RolePB `protobuf:"bytes,1,rep,name=Roles,proto3" json:"Roles,omitempty"`
	Total                int32     `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RolesResponse) Reset()         { *m = RolesResponse{} }
func (m *RolesResponse) String() string { return proto.CompactTextString(m) }
func (*RolesResponse) ProtoMessage()    {}
func (*RolesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{17}
}
func (m *RolesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RolesResponse.Unmarshal(m, b)
}
func (m *RolesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RolesResponse.Marshal(b, m, deterministic)
}
func (dst *RolesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolesResponse.Merge(dst, src)
}
func (m *RolesResponse) XXX_Size() int {
	return xxx_messageInfo_RolesResponse.Size(m)
}
func (m *RolesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RolesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RolesResponse proto.InternalMessageInfo

func (m *RolesResponse) GetRoles() []*RolePB {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *RolesResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GroupsResponse struct {
	Groups               []*RoleGroupPB `protobuf:"bytes,1,rep,name=Groups,proto3" json:"Groups,omitempty"`
	Total                int32          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GroupsResponse) Reset()         { *m = GroupsResponse{} }
func (m *GroupsResponse) String() string { return proto.CompactTextString(m) }
func (*GroupsResponse) ProtoMessage()    {}
func (*GroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{18}
}
func (m *GroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupsResponse.Unmarshal(m, b)
}
func (m *GroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupsResponse.Marshal(b, m, deterministic)
}
func (dst *GroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupsResponse.Merge(dst, src)
}
func (m *GroupsResponse) XXX_Size() int {
	return xxx_messageInfo_GroupsResponse.Size(m)
}
func (m *GroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupsResponse proto.InternalMessageInfo

func (m *GroupsResponse) GetGroups() []*RoleGroupPB {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *GroupsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type CreateRoleGroupRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Organization         string   `protobuf:"bytes,3,opt,name=Organization,proto3" json:"Organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleGroupRequest) Reset()         { *m = CreateRoleGroupRequest{} }
func (m *CreateRoleGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoleGroupRequest) ProtoMessage()    {}
func (*CreateRoleGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{19}
}
func (m *CreateRoleGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleGroupRequest.Unmarshal(m, b)
}
func (m *CreateRoleGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleGroupRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRoleGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleGroupRequest.Merge(dst, src)
}
func (m *CreateRoleGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoleGroupRequest.Size(m)
}
func (m *CreateRoleGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleGroupRequest proto.InternalMessageInfo

func (m *CreateRoleGroupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoleGroupRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRoleGroupRequest) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type CreatedGroupResponse struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatedGroupResponse) Reset()         { *m = CreatedGroupResponse{} }
func (m *CreatedGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreatedGroupResponse) ProtoMessage()    {}
func (*CreatedGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_3b32c89e150019d7, []int{20}
}
func (m *CreatedGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedGroupResponse.Unmarshal(m, b)
}
func (m *CreatedGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedGroupResponse.Marshal(b, m, deterministic)
}
func (dst *CreatedGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedGroupResponse.Merge(dst, src)
}
func (m *CreatedGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreatedGroupResponse.Size(m)
}
func (m *CreatedGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedGroupResponse proto.InternalMessageInfo

func (m *CreatedGroupResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreatedGroupResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*RoleGroupPB)(nil), "iunite.club.srv.core.role.RoleGroupPB")
	proto.RegisterType((*RolePB)(nil), "iunite.club.srv.core.role.RolePB")
	proto.RegisterType((*UpdateRoleRequest)(nil), "iunite.club.srv.core.role.UpdateRoleRequest")
	proto.RegisterType((*UpdateRoleResponse)(nil), "iunite.club.srv.core.role.UpdateRoleResponse")
	proto.RegisterType((*ByIDRequest)(nil), "iunite.club.srv.core.role.ByIDRequest")
	proto.RegisterType((*DeletedResponse)(nil), "iunite.club.srv.core.role.DeletedResponse")
	proto.RegisterType((*CreateRoleRequest)(nil), "iunite.club.srv.core.role.CreateRoleRequest")
	proto.RegisterType((*CreatedRoleResponse)(nil), "iunite.club.srv.core.role.CreatedRoleResponse")
	proto.RegisterType((*UsersAndRoleRequest)(nil), "iunite.club.srv.core.role.UsersAndRoleRequest")
	proto.RegisterType((*CreatedResponse)(nil), "iunite.club.srv.core.role.CreatedResponse")
	proto.RegisterType((*UpdateRoleGroupRequest)(nil), "iunite.club.srv.core.role.UpdateRoleGroupRequest")
	proto.RegisterType((*UpdatedResponse)(nil), "iunite.club.srv.core.role.UpdatedResponse")
	proto.RegisterType((*ByGroupIDRequest)(nil), "iunite.club.srv.core.role.ByGroupIDRequest")
	proto.RegisterType((*DeletedRoleGroupResponse)(nil), "iunite.club.srv.core.role.DeletedRoleGroupResponse")
	proto.RegisterType((*ByRoleRequest)(nil), "iunite.club.srv.core.role.ByRoleRequest")
	proto.RegisterType((*UsersResponse)(nil), "iunite.club.srv.core.role.UsersResponse")
	proto.RegisterType((*ByOrganizationRequest)(nil), "iunite.club.srv.core.role.ByOrganizationRequest")
	proto.RegisterType((*RolesResponse)(nil), "iunite.club.srv.core.role.RolesResponse")
	proto.RegisterType((*GroupsResponse)(nil), "iunite.club.srv.core.role.GroupsResponse")
	proto.RegisterType((*CreateRoleGroupRequest)(nil), "iunite.club.srv.core.role.CreateRoleGroupRequest")
	proto.RegisterType((*CreatedGroupResponse)(nil), "iunite.club.srv.core.role.CreatedGroupResponse")
}

func init() { proto.RegisterFile("proto/role/role.proto", fileDescriptor_role_3b32c89e150019d7) }

var fileDescriptor_role_3b32c89e150019d7 = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xed, 0x6e, 0xd3, 0x48,
	0x14, 0x8d, 0xd3, 0x26, 0xbb, 0xb9, 0xd9, 0x76, 0x9b, 0x69, 0x5a, 0x65, 0xad, 0x45, 0x84, 0x41,
	0xaa, 0x42, 0x28, 0x4e, 0x69, 0x7f, 0x80, 0x04, 0x02, 0x25, 0x44, 0xa0, 0xa8, 0x88, 0x56, 0x56,
	0x2b, 0x7e, 0x20, 0x15, 0x92, 0x78, 0x5a, 0x59, 0x38, 0x71, 0x6a, 0x3b, 0x41, 0x69, 0x1f, 0x81,
	0x77, 0xe2, 0x99, 0x78, 0x04, 0x34, 0xd7, 0x1e, 0x7f, 0x24, 0x8e, 0x63, 0x4a, 0x11, 0x7f, 0x22,
	0xcf, 0xcc, 0x99, 0x9c, 0x73, 0xee, 0x9c, 0xb9, 0x36, 0x6c, 0x8d, 0x2c, 0xd3, 0x31, 0x1b, 0x96,
	0x69, 0x30, 0xfc, 0x51, 0x70, 0x4c, 0xfe, 0xd3, 0xc7, 0x43, 0xdd, 0x61, 0x4a, 0xdf, 0x18, 0xf7,
	0x14, 0xdb, 0x9a, 0x28, 0x7d, 0xd3, 0x62, 0x0a, 0x07, 0xc8, 0x77, 0x2f, 0x4c, 0xf3, 0xc2, 0x60,
	0x0d, 0x04, 0xf6, 0xc6, 0xe7, 0x0d, 0x47, 0x1f, 0x30, 0xdb, 0xe9, 0x0e, 0x46, 0xee, 0x5e, 0xb9,
	0x1e, 0xda, 0xdb, 0xb0, 0x99, 0x35, 0xd1, 0xfb, 0xcc, 0x6e, 0x8c, 0x6d, 0x66, 0xb9, 0x7b, 0xf0,
	0xd1, 0xc5, 0xd2, 0xaf, 0x12, 0x14, 0x55, 0xd3, 0x60, 0x6f, 0x2c, 0x73, 0x3c, 0x3a, 0x6e, 0x91,
	0xff, 0xa1, 0x80, 0x8f, 0xef, 0xba, 0x03, 0x56, 0x91, 0xaa, 0x52, 0xad, 0xa0, 0x06, 0x13, 0xa4,
	0x0e, 0x1b, 0x38, 0x68, 0x33, 0xbb, 0x6f, 0xe9, 0x23, 0x47, 0x37, 0x87, 0x95, 0x2c, 0x82, 0xe6,
	0xe6, 0x09, 0x85, 0x7f, 0x8e, 0xac, 0x8b, 0xee, 0x50, 0xbf, 0xea, 0x22, 0x6e, 0x05, 0x71, 0x91,
	0x39, 0xb2, 0x0e, 0xd9, 0x4e, 0xbb, 0xb2, 0x8a, 0x2b, 0xd9, 0x4e, 0x9b, 0x7e, 0x93, 0x20, 0xcf,
	0xd5, 0x1c, 0xb7, 0xbc, 0x25, 0x49, 0x2c, 0x11, 0x02, 0xab, 0xa8, 0xc9, 0xa5, 0xc3, 0x67, 0x52,
	0x86, 0xdc, 0x5b, 0x36, 0x61, 0x86, 0xf7, 0xdf, 0xee, 0x80, 0x54, 0xe0, 0x2f, 0x14, 0xe3, 0xff,
	0xb3, 0x18, 0xce, 0x49, 0xca, 0xc5, 0x48, 0x7a, 0x0e, 0x39, 0x84, 0x57, 0xf2, 0x55, 0xa9, 0x56,
	0xdc, 0xdf, 0x51, 0x16, 0x1e, 0x84, 0x12, 0xaa, 0x9b, 0xea, 0x6e, 0xe2, 0xe5, 0x2c, 0x9d, 0x8e,
	0xb4, 0xae, 0xc3, 0xf8, 0xa2, 0xca, 0x2e, 0xc7, 0xcc, 0x76, 0xfe, 0x94, 0x17, 0x7a, 0x06, 0x24,
	0x2c, 0xc6, 0x1e, 0x99, 0x43, 0x9b, 0xcd, 0xa9, 0x79, 0x0a, 0x05, 0x17, 0xa5, 0x35, 0x1d, 0x94,
	0x54, 0xdc, 0x97, 0x15, 0x37, 0x63, 0x8a, 0xc8, 0x98, 0x72, 0x22, 0x32, 0xa6, 0x06, 0x60, 0x7a,
	0x07, 0x8a, 0xad, 0x69, 0xa7, 0xbd, 0xc0, 0x26, 0xfd, 0x00, 0xff, 0xb6, 0x99, 0xc1, 0x1c, 0xa6,
	0x85, 0xb9, 0x8f, 0x0e, 0x11, 0xf2, 0xb7, 0x9a, 0x3d, 0x3a, 0xe4, 0xdc, 0x1e, 0x24, 0x1d, 0xb7,
	0x0f, 0xa6, 0xd7, 0x50, 0x7a, 0x65, 0xb1, 0x99, 0x42, 0x8b, 0xc2, 0x4a, 0x71, 0x85, 0xcd, 0x2e,
	0x28, 0xec, 0x4a, 0x72, 0x61, 0x57, 0x63, 0x0a, 0xfb, 0x11, 0x36, 0x5d, 0x72, 0x6d, 0x59, 0x65,
	0x3d, 0x58, 0x3a, 0x77, 0x3e, 0x98, 0xbe, 0x84, 0xcd, 0x53, 0x9b, 0x59, 0x76, 0x73, 0xa8, 0x85,
	0xfd, 0x95, 0x21, 0x87, 0xd3, 0x15, 0xa9, 0xba, 0xc2, 0xbd, 0xe0, 0x80, 0xbb, 0xe6, 0x20, 0x11,
	0x27, 0xfe, 0xcc, 0x6b, 0x2f, 0x14, 0x26, 0xd4, 0xfe, 0x86, 0xea, 0xce, 0x60, 0x3b, 0xc8, 0x15,
	0xd6, 0x4d, 0x08, 0x6c, 0x43, 0xc1, 0x9f, 0x43, 0xaa, 0xf4, 0x37, 0x28, 0xd8, 0xc8, 0xc5, 0x7b,
	0x21, 0x4b, 0x12, 0x7f, 0xc3, 0xd0, 0xee, 0xc2, 0x46, 0x6b, 0xea, 0x1d, 0xb6, 0x90, 0x1d, 0x4a,
	0x83, 0x14, 0x49, 0x03, 0xd5, 0xa0, 0x22, 0x32, 0x1c, 0x78, 0xbd, 0xf5, 0x30, 0xdf, 0x87, 0xb5,
	0xd6, 0x74, 0x26, 0xc8, 0x78, 0xa4, 0x52, 0xe8, 0x48, 0xdf, 0xc3, 0x1a, 0x9e, 0xb7, 0xcf, 0xbf,
	0x17, 0x4e, 0x03, 0xe7, 0x9a, 0x2d, 0x34, 0xf6, 0x79, 0x0e, 0x11, 0x49, 0x29, 0x43, 0xee, 0xc4,
	0x74, 0xba, 0xee, 0x5d, 0xc8, 0xa9, 0xee, 0x80, 0x3e, 0x83, 0xad, 0xd6, 0x34, 0x9c, 0x6f, 0xa1,
	0x62, 0xf6, 0x2a, 0x48, 0xb1, 0x3d, 0x66, 0x8d, 0xab, 0x0b, 0x54, 0x3d, 0x81, 0x1c, 0x4e, 0x78,
	0xaa, 0xee, 0x2d, 0x39, 0x7e, 0xde, 0x3b, 0x11, 0xbf, 0x40, 0xdc, 0x39, 0xac, 0x63, 0xd5, 0x03,
	0x82, 0x17, 0x90, 0x77, 0x67, 0x3c, 0x86, 0xb4, 0x01, 0xf3, 0x76, 0x2d, 0xe0, 0xb1, 0x60, 0x3b,
	0xe8, 0x27, 0x91, 0x4c, 0xc7, 0x35, 0x95, 0x2a, 0x14, 0xe7, 0xdf, 0x81, 0xc5, 0x9f, 0x7c, 0xfd,
	0xd1, 0x4f, 0x50, 0xf6, 0x2e, 0xd5, 0x5c, 0xb0, 0x6e, 0xa7, 0x8f, 0xec, 0x7f, 0x2f, 0xb8, 0x41,
	0x22, 0x5f, 0x44, 0x3f, 0xf0, 0xed, 0x91, 0xc7, 0x09, 0x75, 0x8b, 0x2f, 0x85, 0xdc, 0x58, 0xba,
	0x25, 0xea, 0x84, 0x66, 0xc8, 0x15, 0xc8, 0xaf, 0xf5, 0xa1, 0xd6, 0x34, 0x0c, 0x3c, 0xe5, 0x68,
	0xd0, 0xc8, 0x5e, 0xc2, 0x1f, 0xc6, 0x66, 0x52, 0xae, 0x2d, 0x39, 0x6d, 0x3b, 0xc4, 0x7d, 0xed,
	0x73, 0xa3, 0xaa, 0x5f, 0xe6, 0x7e, 0x90, 0xb0, 0x23, 0x1a, 0x52, 0x9a, 0x21, 0x3a, 0x94, 0x38,
	0x39, 0x5e, 0x3c, 0xf7, 0x72, 0x77, 0xda, 0xa4, 0x96, 0xc8, 0x19, 0xea, 0x00, 0x89, 0x3e, 0x23,
	0x6d, 0x80, 0x66, 0x88, 0x25, 0xfa, 0x65, 0xba, 0xc3, 0x8d, 0xef, 0xdd, 0x72, 0x7d, 0xe9, 0x16,
	0x2d, 0xc4, 0x39, 0x16, 0x2f, 0xf7, 0x80, 0xf3, 0x61, 0xa2, 0xb9, 0x68, 0xcb, 0x95, 0x0f, 0x12,
	0xc0, 0x8b, 0x3a, 0x2e, 0xcd, 0x90, 0xcf, 0x00, 0x81, 0x7c, 0xb2, 0x9b, 0xca, 0xa5, 0xa0, 0x7c,
	0x94, 0x12, 0xed, 0x93, 0xf5, 0x00, 0x02, 0x8f, 0x64, 0x27, 0xd1, 0x5e, 0xe0, 0xac, 0x9e, 0xc2,
	0x59, 0xc0, 0x61, 0x00, 0x04, 0x97, 0x2d, 0xd1, 0xd0, 0xdc, 0xe7, 0x8e, 0xac, 0x2c, 0xbf, 0x8e,
	0x33, 0x8e, 0x86, 0xb0, 0xde, 0xd4, 0xdc, 0x4c, 0x9e, 0x98, 0xc8, 0xa8, 0x2c, 0xcb, 0x59, 0xf4,
	0x13, 0x24, 0xd1, 0xdd, 0xcc, 0x17, 0x07, 0xcd, 0x90, 0x4b, 0x28, 0xa9, 0x6c, 0x60, 0x4e, 0xd8,
	0xef, 0xa2, 0x9c, 0x2b, 0x68, 0x2f, 0x8f, 0x1d, 0xf1, 0xe0, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x60, 0x1e, 0x40, 0xec, 0x59, 0x0d, 0x00, 0x00,
}
