// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/department/department.proto

package iunite_club_srv_organization_department

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "iunite.club/services/organization/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetDepartmentWithIDRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDepartmentWithIDRequest) Reset()         { *m = GetDepartmentWithIDRequest{} }
func (m *GetDepartmentWithIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetDepartmentWithIDRequest) ProtoMessage()    {}
func (*GetDepartmentWithIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{0}
}
func (m *GetDepartmentWithIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepartmentWithIDRequest.Unmarshal(m, b)
}
func (m *GetDepartmentWithIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepartmentWithIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetDepartmentWithIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepartmentWithIDRequest.Merge(dst, src)
}
func (m *GetDepartmentWithIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetDepartmentWithIDRequest.Size(m)
}
func (m *GetDepartmentWithIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepartmentWithIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepartmentWithIDRequest proto.InternalMessageInfo

func (m *GetDepartmentWithIDRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DepartmentResponse struct {
	Department           *proto1.Organization `protobuf:"bytes,1,opt,name=Department,proto3" json:"Department,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DepartmentResponse) Reset()         { *m = DepartmentResponse{} }
func (m *DepartmentResponse) String() string { return proto.CompactTextString(m) }
func (*DepartmentResponse) ProtoMessage()    {}
func (*DepartmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{1}
}
func (m *DepartmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentResponse.Unmarshal(m, b)
}
func (m *DepartmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentResponse.Marshal(b, m, deterministic)
}
func (dst *DepartmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentResponse.Merge(dst, src)
}
func (m *DepartmentResponse) XXX_Size() int {
	return xxx_messageInfo_DepartmentResponse.Size(m)
}
func (m *DepartmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentResponse proto.InternalMessageInfo

func (m *DepartmentResponse) GetDepartment() *proto1.Organization {
	if m != nil {
		return m.Department
	}
	return nil
}

type CreateDepartmentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentID             string   `protobuf:"bytes,2,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDepartmentRequest) Reset()         { *m = CreateDepartmentRequest{} }
func (m *CreateDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDepartmentRequest) ProtoMessage()    {}
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{2}
}
func (m *CreateDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepartmentRequest.Unmarshal(m, b)
}
func (m *CreateDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepartmentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepartmentRequest.Merge(dst, src)
}
func (m *CreateDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDepartmentRequest.Size(m)
}
func (m *CreateDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepartmentRequest proto.InternalMessageInfo

func (m *CreateDepartmentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateDepartmentRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *CreateDepartmentRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateDepartmentResponse struct {
	Department           *proto1.Organization `protobuf:"bytes,1,opt,name=Department,proto3" json:"Department,omitempty"`
	OK                   bool                 `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateDepartmentResponse) Reset()         { *m = CreateDepartmentResponse{} }
func (m *CreateDepartmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDepartmentResponse) ProtoMessage()    {}
func (*CreateDepartmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{3}
}
func (m *CreateDepartmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDepartmentResponse.Unmarshal(m, b)
}
func (m *CreateDepartmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDepartmentResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDepartmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDepartmentResponse.Merge(dst, src)
}
func (m *CreateDepartmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDepartmentResponse.Size(m)
}
func (m *CreateDepartmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDepartmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDepartmentResponse proto.InternalMessageInfo

func (m *CreateDepartmentResponse) GetDepartment() *proto1.Organization {
	if m != nil {
		return m.Department
	}
	return nil
}

func (m *CreateDepartmentResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type UpdateDepartmentRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentID             string   `protobuf:"bytes,3,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDepartmentRequest) Reset()         { *m = UpdateDepartmentRequest{} }
func (m *UpdateDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDepartmentRequest) ProtoMessage()    {}
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{4}
}
func (m *UpdateDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDepartmentRequest.Unmarshal(m, b)
}
func (m *UpdateDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDepartmentRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDepartmentRequest.Merge(dst, src)
}
func (m *UpdateDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDepartmentRequest.Size(m)
}
func (m *UpdateDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDepartmentRequest proto.InternalMessageInfo

func (m *UpdateDepartmentRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateDepartmentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateDepartmentRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *UpdateDepartmentRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateDepartmentResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDepartmentResponse) Reset()         { *m = UpdateDepartmentResponse{} }
func (m *UpdateDepartmentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDepartmentResponse) ProtoMessage()    {}
func (*UpdateDepartmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{5}
}
func (m *UpdateDepartmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDepartmentResponse.Unmarshal(m, b)
}
func (m *UpdateDepartmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDepartmentResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateDepartmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDepartmentResponse.Merge(dst, src)
}
func (m *UpdateDepartmentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDepartmentResponse.Size(m)
}
func (m *UpdateDepartmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDepartmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDepartmentResponse proto.InternalMessageInfo

func (m *UpdateDepartmentResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type RemoveDepartmentRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDepartmentRequest) Reset()         { *m = RemoveDepartmentRequest{} }
func (m *RemoveDepartmentRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveDepartmentRequest) ProtoMessage()    {}
func (*RemoveDepartmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{6}
}
func (m *RemoveDepartmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDepartmentRequest.Unmarshal(m, b)
}
func (m *RemoveDepartmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDepartmentRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveDepartmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDepartmentRequest.Merge(dst, src)
}
func (m *RemoveDepartmentRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveDepartmentRequest.Size(m)
}
func (m *RemoveDepartmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDepartmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDepartmentRequest proto.InternalMessageInfo

func (m *RemoveDepartmentRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RemoveDepartmentResponse struct {
	OK                   bool     `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveDepartmentResponse) Reset()         { *m = RemoveDepartmentResponse{} }
func (m *RemoveDepartmentResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveDepartmentResponse) ProtoMessage()    {}
func (*RemoveDepartmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{7}
}
func (m *RemoveDepartmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveDepartmentResponse.Unmarshal(m, b)
}
func (m *RemoveDepartmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveDepartmentResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveDepartmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveDepartmentResponse.Merge(dst, src)
}
func (m *RemoveDepartmentResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveDepartmentResponse.Size(m)
}
func (m *RemoveDepartmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveDepartmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveDepartmentResponse proto.InternalMessageInfo

func (m *RemoveDepartmentResponse) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

type DepartmentListByParentIDRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	MaxFlag              string   `protobuf:"bytes,3,opt,name=MaxFlag,proto3" json:"MaxFlag,omitempty"`
	MinFlag              string   `protobuf:"bytes,4,opt,name=MinFlag,proto3" json:"MinFlag,omitempty"`
	ParentID             string   `protobuf:"bytes,5,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	Search               string   `protobuf:"bytes,6,opt,name=Search,proto3" json:"Search,omitempty"`
	Spread               bool     `protobuf:"varint,7,opt,name=Spread,proto3" json:"Spread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepartmentListByParentIDRequest) Reset()         { *m = DepartmentListByParentIDRequest{} }
func (m *DepartmentListByParentIDRequest) String() string { return proto.CompactTextString(m) }
func (*DepartmentListByParentIDRequest) ProtoMessage()    {}
func (*DepartmentListByParentIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{8}
}
func (m *DepartmentListByParentIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentListByParentIDRequest.Unmarshal(m, b)
}
func (m *DepartmentListByParentIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentListByParentIDRequest.Marshal(b, m, deterministic)
}
func (dst *DepartmentListByParentIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentListByParentIDRequest.Merge(dst, src)
}
func (m *DepartmentListByParentIDRequest) XXX_Size() int {
	return xxx_messageInfo_DepartmentListByParentIDRequest.Size(m)
}
func (m *DepartmentListByParentIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentListByParentIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentListByParentIDRequest proto.InternalMessageInfo

func (m *DepartmentListByParentIDRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DepartmentListByParentIDRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DepartmentListByParentIDRequest) GetMaxFlag() string {
	if m != nil {
		return m.MaxFlag
	}
	return ""
}

func (m *DepartmentListByParentIDRequest) GetMinFlag() string {
	if m != nil {
		return m.MinFlag
	}
	return ""
}

func (m *DepartmentListByParentIDRequest) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *DepartmentListByParentIDRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *DepartmentListByParentIDRequest) GetSpread() bool {
	if m != nil {
		return m.Spread
	}
	return false
}

type DepartmentListResponse struct {
	Departments          []*proto1.Organization `protobuf:"bytes,1,rep,name=Departments,proto3" json:"Departments,omitempty"`
	Total                int64                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DepartmentListResponse) Reset()         { *m = DepartmentListResponse{} }
func (m *DepartmentListResponse) String() string { return proto.CompactTextString(m) }
func (*DepartmentListResponse) ProtoMessage()    {}
func (*DepartmentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_department_79db2891b9036c66, []int{9}
}
func (m *DepartmentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentListResponse.Unmarshal(m, b)
}
func (m *DepartmentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentListResponse.Marshal(b, m, deterministic)
}
func (dst *DepartmentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentListResponse.Merge(dst, src)
}
func (m *DepartmentListResponse) XXX_Size() int {
	return xxx_messageInfo_DepartmentListResponse.Size(m)
}
func (m *DepartmentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentListResponse proto.InternalMessageInfo

func (m *DepartmentListResponse) GetDepartments() []*proto1.Organization {
	if m != nil {
		return m.Departments
	}
	return nil
}

func (m *DepartmentListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*GetDepartmentWithIDRequest)(nil), "iunite.club.srv.organization.department.GetDepartmentWithIDRequest")
	proto.RegisterType((*DepartmentResponse)(nil), "iunite.club.srv.organization.department.DepartmentResponse")
	proto.RegisterType((*CreateDepartmentRequest)(nil), "iunite.club.srv.organization.department.CreateDepartmentRequest")
	proto.RegisterType((*CreateDepartmentResponse)(nil), "iunite.club.srv.organization.department.CreateDepartmentResponse")
	proto.RegisterType((*UpdateDepartmentRequest)(nil), "iunite.club.srv.organization.department.UpdateDepartmentRequest")
	proto.RegisterType((*UpdateDepartmentResponse)(nil), "iunite.club.srv.organization.department.UpdateDepartmentResponse")
	proto.RegisterType((*RemoveDepartmentRequest)(nil), "iunite.club.srv.organization.department.RemoveDepartmentRequest")
	proto.RegisterType((*RemoveDepartmentResponse)(nil), "iunite.club.srv.organization.department.RemoveDepartmentResponse")
	proto.RegisterType((*DepartmentListByParentIDRequest)(nil), "iunite.club.srv.organization.department.DepartmentListByParentIDRequest")
	proto.RegisterType((*DepartmentListResponse)(nil), "iunite.club.srv.organization.department.DepartmentListResponse")
}

func init() {
	proto.RegisterFile("proto/department/department.proto", fileDescriptor_department_79db2891b9036c66)
}

var fileDescriptor_department_79db2891b9036c66 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xf3, 0xd7, 0x32, 0x95, 0x10, 0x5a, 0x55, 0x8d, 0x65, 0x0e, 0x04, 0x5f, 0x80, 0x0a,
	0x39, 0x52, 0xb9, 0xc1, 0x81, 0x9f, 0x5a, 0x40, 0x68, 0x20, 0xd5, 0x02, 0xe2, 0xca, 0x36, 0x19,
	0xa5, 0x2b, 0x12, 0xdb, 0xec, 0x6e, 0x22, 0xfe, 0x5e, 0x04, 0x1e, 0xa1, 0xaf, 0xc2, 0x4b, 0x21,
	0xaf, 0x1d, 0x7b, 0xed, 0xe0, 0x36, 0x2e, 0xdc, 0xf6, 0x9b, 0x19, 0xcf, 0x7c, 0xdf, 0xec, 0x8c,
	0x17, 0x6e, 0x47, 0x22, 0x54, 0x61, 0x7f, 0x82, 0x11, 0x13, 0x6a, 0x8e, 0x81, 0x32, 0x8e, 0x9e,
	0xf6, 0x91, 0x3b, 0x7c, 0x11, 0x70, 0x85, 0xde, 0x78, 0xb6, 0x38, 0xf5, 0xa4, 0x58, 0x7a, 0xa1,
	0x98, 0xb2, 0x80, 0x7f, 0x63, 0x8a, 0x87, 0x81, 0x97, 0x87, 0x3b, 0x0f, 0x8d, 0xc0, 0xbe, 0x44,
	0xb1, 0xe4, 0x63, 0x94, 0x7d, 0x33, 0xba, 0x9f, 0x54, 0x2b, 0x24, 0xd0, 0x26, 0xf7, 0x3e, 0x38,
	0x2f, 0x50, 0xf9, 0x59, 0xb2, 0x0f, 0x5c, 0x9d, 0x0d, 0x7c, 0x8a, 0x9f, 0x17, 0x28, 0x15, 0xb9,
	0x0e, 0x8d, 0x81, 0x6f, 0x5b, 0x3d, 0xeb, 0xee, 0x35, 0xda, 0x18, 0xf8, 0xee, 0x47, 0x20, 0x79,
	0x28, 0x45, 0x19, 0x85, 0x81, 0x44, 0xf2, 0x0a, 0x20, 0xb7, 0xea, 0xe8, 0xdd, 0xc3, 0x03, 0xef,
	0x42, 0xf6, 0x23, 0x03, 0x50, 0xe3, 0x6b, 0xf7, 0x13, 0x74, 0x8f, 0x04, 0x32, 0x85, 0x66, 0x9d,
	0x84, 0x0c, 0x81, 0xd6, 0x1b, 0x36, 0xc7, 0x94, 0x8e, 0x3e, 0x13, 0x07, 0x76, 0x4e, 0x98, 0xc0,
	0x40, 0x0d, 0x7c, 0xbb, 0xa1, 0xed, 0x19, 0x26, 0x3d, 0xd8, 0xf5, 0x51, 0x8e, 0x05, 0x8f, 0xe2,
	0x2a, 0x76, 0x53, 0xbb, 0x4d, 0x93, 0xbb, 0x04, 0x7b, 0xbd, 0xd8, 0xff, 0x17, 0x15, 0xb7, 0x71,
	0x74, 0xac, 0xf9, 0xed, 0xd0, 0xc6, 0xe8, 0xd8, 0xfd, 0x0e, 0xdd, 0xf7, 0xd1, 0xe4, 0xaf, 0x22,
	0x4b, 0x1d, 0xcf, 0x44, 0x37, 0x2a, 0x44, 0x37, 0x2f, 0x16, 0xdd, 0x5a, 0x17, 0x7d, 0x00, 0xf6,
	0x7a, 0xf1, 0x54, 0x74, 0x42, 0xd4, 0xca, 0x88, 0xde, 0x83, 0x2e, 0xc5, 0x79, 0xb8, 0xbc, 0x9c,
	0x68, 0x9c, 0x76, 0x3d, 0xb4, 0x22, 0xed, 0x6f, 0x0b, 0x6e, 0xe5, 0x61, 0x43, 0x2e, 0xd5, 0xb3,
	0xaf, 0x2b, 0x05, 0xc6, 0x6d, 0x9f, 0xb0, 0x69, 0x72, 0xdb, 0x6d, 0xaa, 0xcf, 0x64, 0x0f, 0xda,
	0x43, 0x3e, 0xe7, 0x4a, 0x77, 0xa3, 0x4d, 0x13, 0x40, 0x6c, 0xd8, 0x7e, 0xcd, 0xbe, 0x3c, 0x9f,
	0xb1, 0x69, 0xda, 0x8d, 0x15, 0xd4, 0x1e, 0x1e, 0x68, 0x4f, 0x2b, 0xf5, 0x24, 0xb0, 0xd0, 0xc2,
	0x76, 0xa9, 0x85, 0xfb, 0xd0, 0x79, 0x8b, 0x4c, 0x8c, 0xcf, 0xec, 0x8e, 0xf6, 0xa4, 0x48, 0xdb,
	0x23, 0x81, 0x6c, 0x62, 0x6f, 0x6b, 0x25, 0x29, 0x72, 0x7f, 0xc0, 0x7e, 0x51, 0x4c, 0xa6, 0x7b,
	0x18, 0x5f, 0xc6, 0xca, 0x23, 0x6d, 0xab, 0xd7, 0xac, 0x39, 0x44, 0xe6, 0xe7, 0xb1, 0xfa, 0x77,
	0xa1, 0x62, 0x33, 0xad, 0xbe, 0x49, 0x13, 0x70, 0x78, 0xde, 0x31, 0x07, 0x95, 0xfc, 0xb4, 0xe0,
	0x46, 0x79, 0xa6, 0xc9, 0x13, 0x6f, 0xc3, 0x5f, 0x89, 0x57, 0xb1, 0x7b, 0xce, 0xd3, 0x7f, 0xc8,
	0x90, 0x34, 0xc3, 0xdd, 0xd2, 0xdc, 0xca, 0xa3, 0x57, 0x83, 0x5b, 0xc5, 0xca, 0xd4, 0xe0, 0x56,
	0x35, 0xf7, 0x29, 0xb7, 0xf2, 0xfc, 0xd6, 0xe0, 0x56, 0xb1, 0x25, 0x35, 0xb8, 0x55, 0x2d, 0x8f,
	0xbb, 0x45, 0xce, 0x2d, 0xb8, 0x59, 0xf8, 0x49, 0x17, 0x37, 0x86, 0xbc, 0xdc, 0xb8, 0xc8, 0x25,
	0x4b, 0xe7, 0x3c, 0xbe, 0x62, 0x26, 0x83, 0xec, 0x2f, 0x0b, 0xf6, 0x0a, 0x64, 0x7d, 0x54, 0x8c,
	0xcf, 0x24, 0x39, 0xda, 0x38, 0x77, 0xf5, 0x83, 0xe4, 0x3c, 0xba, 0x02, 0xc1, 0x9c, 0xdc, 0x69,
	0x47, 0x3f, 0x7a, 0x0f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x68, 0x38, 0x5e, 0x7e, 0x07,
	0x00, 0x00,
}
