// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/organization.proto

package iunite_club_srv_organization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organization struct {
	ID                   string       `protobuf:"bytes,9,opt,name=ID,proto3" json:"ID,omitempty"`
	Kind                 string       `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Slug                 string       `protobuf:"bytes,3,opt,name=Slug,proto3" json:"Slug,omitempty"`
	SchoolID             string       `protobuf:"bytes,4,opt,name=SchoolID,proto3" json:"SchoolID,omitempty"`
	Description          string       `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	ParentID             string       `protobuf:"bytes,6,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	ClubProfile          *ClubProfile `protobuf:"bytes,7,opt,name=ClubProfile,proto3" json:"ClubProfile,omitempty"`
	Jobs                 []*Job       `protobuf:"bytes,8,rep,name=Jobs,proto3" json:"Jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_0905f12c687fa3f6, []int{0}
}
func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (dst *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(dst, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Organization) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Organization) GetSchoolID() string {
	if m != nil {
		return m.SchoolID
	}
	return ""
}

func (m *Organization) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Organization) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *Organization) GetClubProfile() *ClubProfile {
	if m != nil {
		return m.ClubProfile
	}
	return nil
}

func (m *Organization) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Job struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_0905f12c687fa3f6, []int{1}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type Paperwork struct {
	FileID               string   `protobuf:"bytes,1,opt,name=FileID,proto3" json:"FileID,omitempty"`
	UploadAt             string   `protobuf:"bytes,2,opt,name=UploadAt,proto3" json:"UploadAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paperwork) Reset()         { *m = Paperwork{} }
func (m *Paperwork) String() string { return proto.CompactTextString(m) }
func (*Paperwork) ProtoMessage()    {}
func (*Paperwork) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_0905f12c687fa3f6, []int{2}
}
func (m *Paperwork) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paperwork.Unmarshal(m, b)
}
func (m *Paperwork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paperwork.Marshal(b, m, deterministic)
}
func (dst *Paperwork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paperwork.Merge(dst, src)
}
func (m *Paperwork) XXX_Size() int {
	return xxx_messageInfo_Paperwork.Size(m)
}
func (m *Paperwork) XXX_DiscardUnknown() {
	xxx_messageInfo_Paperwork.DiscardUnknown(m)
}

var xxx_messageInfo_Paperwork proto.InternalMessageInfo

func (m *Paperwork) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *Paperwork) GetUploadAt() string {
	if m != nil {
		return m.UploadAt
	}
	return ""
}

type ClubProfile struct {
	Logo                 string       `protobuf:"bytes,1,opt,name=Logo,proto3" json:"Logo,omitempty"`
	Scale                int32        `protobuf:"varint,2,opt,name=Scale,proto3" json:"Scale,omitempty"`
	Paperworks           []*Paperwork `protobuf:"bytes,3,rep,name=Paperworks,proto3" json:"Paperworks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClubProfile) Reset()         { *m = ClubProfile{} }
func (m *ClubProfile) String() string { return proto.CompactTextString(m) }
func (*ClubProfile) ProtoMessage()    {}
func (*ClubProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_organization_0905f12c687fa3f6, []int{3}
}
func (m *ClubProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClubProfile.Unmarshal(m, b)
}
func (m *ClubProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClubProfile.Marshal(b, m, deterministic)
}
func (dst *ClubProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClubProfile.Merge(dst, src)
}
func (m *ClubProfile) XXX_Size() int {
	return xxx_messageInfo_ClubProfile.Size(m)
}
func (m *ClubProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ClubProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ClubProfile proto.InternalMessageInfo

func (m *ClubProfile) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *ClubProfile) GetScale() int32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *ClubProfile) GetPaperworks() []*Paperwork {
	if m != nil {
		return m.Paperworks
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "iunite.club.srv.organization.Organization")
	proto.RegisterType((*Job)(nil), "iunite.club.srv.organization.Job")
	proto.RegisterType((*Paperwork)(nil), "iunite.club.srv.organization.Paperwork")
	proto.RegisterType((*ClubProfile)(nil), "iunite.club.srv.organization.ClubProfile")
}

func init() {
	proto.RegisterFile("proto/organization.proto", fileDescriptor_organization_0905f12c687fa3f6)
}

var fileDescriptor_organization_0905f12c687fa3f6 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0x49, 0xd2, 0xf6, 0xdf, 0x4e, 0xfe, 0x78, 0x58, 0x44, 0x16, 0xf1, 0x10, 0x73, 0xb1,
	0x5e, 0x22, 0x54, 0x3c, 0x8a, 0x88, 0x41, 0x49, 0x2b, 0x5a, 0x52, 0x7c, 0x80, 0x4d, 0xba, 0xd6,
	0xc5, 0x35, 0x13, 0x36, 0x89, 0x82, 0x27, 0x1f, 0xcb, 0xc7, 0x93, 0xdd, 0xb4, 0x61, 0xbd, 0x04,
	0x6f, 0xf3, 0xfd, 0x32, 0xdf, 0x4c, 0xe6, 0x4b, 0x80, 0x96, 0x0a, 0x6b, 0x3c, 0x43, 0xb5, 0x61,
	0x85, 0xf8, 0x64, 0xb5, 0xc0, 0x22, 0x32, 0x88, 0x1c, 0x89, 0xa6, 0x10, 0x35, 0x8f, 0x72, 0xd9,
	0x64, 0x51, 0xa5, 0xde, 0x23, 0xbb, 0x27, 0xfc, 0x76, 0xe1, 0xff, 0xa3, 0x05, 0xc8, 0x1e, 0xb8,
	0x49, 0x4c, 0x27, 0x81, 0x33, 0x9d, 0xa4, 0x6e, 0x12, 0x13, 0x02, 0x83, 0x85, 0x28, 0xd6, 0xd4,
	0x31, 0xc4, 0xd4, 0x9a, 0x3d, 0xb0, 0x37, 0x4e, 0xdd, 0x96, 0xe9, 0x5a, 0xb3, 0x95, 0x6c, 0x36,
	0xd4, 0x6b, 0x99, 0xae, 0xc9, 0x21, 0x8c, 0x57, 0xf9, 0x0b, 0xa2, 0x4c, 0x62, 0x3a, 0x30, 0xbc,
	0xd3, 0x24, 0x00, 0x3f, 0xe6, 0x55, 0xae, 0x44, 0xa9, 0xd7, 0xd2, 0xa1, 0x79, 0x6c, 0x23, 0xed,
	0x5e, 0x32, 0xc5, 0x8b, 0x3a, 0x89, 0xe9, 0xa8, 0x75, 0xef, 0x34, 0x59, 0x80, 0x7f, 0x23, 0x9b,
	0x6c, 0xa9, 0xf0, 0x59, 0x48, 0x4e, 0xff, 0x05, 0xce, 0xd4, 0x9f, 0x9d, 0x46, 0x7d, 0xa7, 0x46,
	0x96, 0x21, 0xb5, 0xdd, 0xe4, 0x02, 0x06, 0x73, 0xcc, 0x2a, 0x3a, 0x0e, 0xbc, 0xa9, 0x3f, 0x3b,
	0xee, 0x9f, 0x32, 0xc7, 0x2c, 0x35, 0xed, 0xe1, 0x25, 0x78, 0x73, 0xcc, 0xb6, 0x81, 0x39, 0x76,
	0x60, 0x7f, 0x09, 0x27, 0xbc, 0x82, 0xc9, 0x92, 0x95, 0x5c, 0x7d, 0xa0, 0x7a, 0x25, 0x07, 0x30,
	0xba, 0x15, 0x92, 0x77, 0x83, 0xb6, 0x4a, 0x67, 0xf0, 0x54, 0x4a, 0x64, 0xeb, 0xeb, 0x7a, 0x3b,
	0xb0, 0xd3, 0xe1, 0x97, 0xf3, 0x2b, 0x04, 0xbd, 0xe4, 0x1e, 0x37, 0xb8, 0xfb, 0x52, 0xba, 0x26,
	0xfb, 0x30, 0x5c, 0xe5, 0x4c, 0xb6, 0x6f, 0x33, 0x4c, 0x5b, 0x41, 0xee, 0x00, 0xba, 0xd5, 0x15,
	0xf5, 0xcc, 0xd9, 0x27, 0xfd, 0x67, 0x77, 0xfd, 0xa9, 0x65, 0xcd, 0x46, 0xe6, 0x17, 0x3b, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x02, 0x7d, 0xb6, 0x7b, 0x7e, 0x02, 0x00, 0x00,
}
